'use server';

type WordLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

const words = {
	A1: [
		{ eng: 'the', rus: 'этот' },
		{ eng: 'be', rus: 'быть / являться / находиться' },
		{ eng: 'to', rus: 'в направлении / чтобы' },
		{ eng: 'and', rus: 'и / а' },
		{ eng: 'a', rus: 'некий / один' },
		{ eng: 'of', rus: 'из / от / о' },
		{ eng: 'have', rus: 'иметь / обладать' },
		{ eng: 'I', rus: 'я' },
		{ eng: 'he', rus: 'он' },
		{ eng: 'you', rus: 'вы / ты' },
		{ eng: 'not', rus: 'не / ни' },
		{ eng: 'his', rus: 'его' },
		{ eng: 'it', rus: 'это / оно' },
		{ eng: 'do', rus: 'делать / заниматься' },
		{ eng: 'she', rus: 'она' },
		{ eng: 'in', rus: 'в / в течение' },
		{ eng: 'for', rus: 'для / на протяжении / за' },
		{ eng: 'with', rus: 'с / с помощью' },
		{ eng: 'her', rus: 'её' },
		{ eng: 'at', rus: 'на / в / у' },
		{ eng: 'but', rus: 'но' },
		{ eng: 'they', rus: 'они' },
		{ eng: 'that', rus: 'тот' },
		{ eng: 'back', rus: 'назад / обратно' },
		{ eng: 'him', rus: 'ему / его' },
		{ eng: 'we', rus: 'мы' },
		{ eng: 'can', rus: 'мочь / уметь' },
		{ eng: 'from', rus: 'от / из / у' },
		{ eng: 'there', rus: 'там / туда' },
		{ eng: 'go', rus: 'идти / ехать / проходить / уезжать' },
		{ eng: 'would', rus: 'бы' },
		{ eng: 'me', rus: 'меня / мне' },
		{ eng: 'will', rus: 'намереваться / собираться' },
		{ eng: 'on', rus: 'на / по' },
		{ eng: 'my', rus: 'мой / свой' },
		{ eng: 'what', rus: 'что' },
		{ eng: 'this', rus: 'это' },
		{ eng: 'get', rus: 'получать / становиться / добираться' },
		{ eng: 'know', rus: 'знать' },
		{ eng: 'as', rus: 'в качестве / так же ..., как' },
		{ eng: 'them', rus: 'их / им' },
		{ eng: 'see', rus: 'видеть / увидеть' },
		{ eng: 'then', rus: 'тогда / затем' },
		{ eng: 'look', rus: 'выглядеть / смотреть / взглянуть / глядеть' },
		{ eng: 'no', rus: 'нет' },
		{ eng: 'think', rus: 'думать' },
		{ eng: 'into', rus: 'в' },
		{ eng: 'come', rus: 'приходить / приезжать' },
		{ eng: 'say', rus: 'говорить / сказать' },
		{ eng: 'goodbye', rus: 'до свидания / прощай / пока' },
		{ eng: 'take', rus: 'взять или брать / занимать (время, место)' },
		{ eng: 'man', rus: 'мужчина / человек' },
		{ eng: 'make', rus: 'делать / изготавливать / заставлять' },
		{ eng: 'or', rus: 'или / либо' },
		{ eng: 'your', rus: 'ваш / твой' },
		{ eng: 'time', rus: 'время / количество раз' },
		{ eng: 'now', rus: 'теперь / сейчас' },
		{ eng: 'their', rus: 'их' },
		{ eng: 'about', rus: 'о / об' },
		{ eng: 'when', rus: 'когда' },
		{ eng: 'want', rus: 'хотеть' },
		{ eng: 'who', rus: 'кто / который' },
		{ eng: 'up', rus: 'вверх / выше / высоко' },
		{ eng: 'all', rus: 'все' },
		{ eng: 'more', rus: 'больший / дополнительный' },
		{ eng: 'tell', rus: 'рассказывать / поведать' },
		{ eng: 'here', rus: 'здесь / сюда' },
		{ eng: 'her', rus: 'ее / ей' },
		{ eng: 'some', rus: 'некоторый / несколько' },
		{ eng: 'like', rus: 'нравиться / любить' },
		{ eng: 'how', rus: 'как / насколько' },
		{ eng: 'hand', rus: 'рука / кисть руки' },
		{ eng: 'before', rus: 'перед чем-либо / до чего-либо' },
		{ eng: 'too', rus: 'слишком / тоже' },
		{ eng: 'eye', rus: 'глаз' },
		{ eng: 'give', rus: 'давать / отдавать / предоставлять' },
		{ eng: 'two', rus: 'два' },
		{ eng: 'us', rus: 'нас / нам' },
		{ eng: 'hello', rus: 'приветствие / привет' },
		{ eng: 'find', rus: 'находить / обнаруживать' },
		{ eng: 'other', rus: 'другой' },
		{ eng: 'thing', rus: 'вещь / штука' },
		{ eng: 'any', rus: 'любой / какой-нибудь' },
		{ eng: 'again', rus: 'снова / вновь' },
		{ eng: 'feel', rus: 'чувствовать / чувствовать себя / ощущать' },
		{ eng: 'only', rus: 'единственный' },
		{ eng: 'than', rus: 'чем / нежели' },
		{ eng: 'good', rus: 'хороший' },
		{ eng: 'something', rus: 'что-нибудь / кое-что' },
		{ eng: 'never', rus: 'никогда / никогда не' },
		{ eng: 'down', rus: 'вниз / внизу' },
		{ eng: 'well', rus: 'хорошо' },
		{ eng: 'very', rus: 'очень' },
		{ eng: 'face', rus: 'лицо / лицевая сторона' },
		{ eng: 'door', rus: 'дверь' },
		{ eng: 'our', rus: 'наш' },
		{ eng: 'hear', rus: 'слышать' },
		{ eng: 'head', rus: 'голова / глава' },
		{ eng: 'much', rus: 'много' },
		{ eng: 'little', rus: 'маленький / небольшой' },
		{ eng: 'day', rus: 'день / сутки' },
		{ eng: 'its', rus: 'его' },
		{ eng: 'people', rus: 'люди / народ' },
		{ eng: 'old', rus: 'старый / старший' },
		{ eng: 'where', rus: 'где / куда' },
		{ eng: 'why', rus: 'почему / зачем' },
		{ eng: 'one', rus: 'единственный / единый' },
		{ eng: 'one', rus: 'один' },
		{ eng: 'which', rus: 'который / какой из' },
		{ eng: 'need', rus: 'нуждаться / иметь потребность' },
		{ eng: 'room', rus: 'комната / помещение / пространство' },
		{ eng: 'own', rus: 'собственный' },
		{ eng: 'sit', rus: 'сидеть' },
		{ eng: 'because', rus: 'потому что / по причине / из-за' },
		{ eng: 'year', rus: 'год / курс обучения' },
		{ eng: 'put', rus: 'ставить / класть' },
		{ eng: 'hi', rus: 'привет / эй' },
		{ eng: 'woman', rus: 'женщина' },
		{ eng: 'begin', rus: 'начинать / приниматься' },
		{ eng: 'last', rus: 'последний / прошлый' },
		{ eng: 'anything', rus: 'что-нибудь' },
		{ eng: 'long', rus: 'длинный / долгий' },
		{ eng: 'place', rus: 'место' },
		{ eng: 'start', rus: 'начинать / стартовать / запускать' },
		{ eng: 'run', rus: 'бегать / работать' },
		{ eng: 'these', rus: 'эти' },
		{ eng: 'life', rus: 'жизнь' },
		{ eng: 'three', rus: 'три' },
		{ eng: 'leave', rus: 'оставлять / покидать' },
		{ eng: 'speak', rus: 'говорить / произносить' },
		{ eng: 'after', rus: 'после чего-либо / через сколько-то' },
		{ eng: 'wait', rus: 'ждать' },
		{ eng: 'use', rus: 'использовать / употреблять' },
		{ eng: 'night', rus: 'ночь / вечер' },
		{ eng: 'right', rus: 'правый / правильный' },
		{ eng: 'foot', rus: 'ступня / фут (0,304 м) / нога' },
		{ eng: 'word', rus: 'слово' },
		{ eng: 'watch', rus: 'наблюдать / смотреть' },
		{ eng: 'new', rus: 'новый' },
		{ eng: 'stop', rus: 'останавливать / прекращать' },
		{ eng: 'walk', rus: 'идти / ходить / гулять' },
		{ eng: 'arm', rus: 'рука' },
		{ eng: 'small', rus: 'маленький / небольшой' },
		{ eng: 'always', rus: 'всегда' },
		{ eng: 'both', rus: 'оба / обе' },
		{ eng: 'behind', rus: 'за / позади' },
		{ eng: 'OK', rus: 'окей' },
		{ eng: 'house', rus: 'дом / жилище' },
		{ eng: 'world', rus: 'мир' },
		{ eng: 'big', rus: 'большой / важный' },
		{ eng: 'great', rus: 'великий / отличный' },
		{ eng: 'really', rus: 'действительно / на самом деле' },
		{ eng: 'open', rus: 'открывать / раскрывать' },
		{ eng: 'about', rus: 'около / примерно' },
		{ eng: 'when', rus: 'когда / если' },
		{ eng: 'first', rus: 'первый' },
		{ eng: 'father', rus: 'отец / папа' },
		{ eng: 'every', rus: 'каждый / всякий' },
		{ eng: 'also', rus: 'также / еще' },
		{ eng: 'talk', rus: 'говорить / разговаривать' },
		{ eng: 'wall', rus: 'стена' },
		{ eng: 'work', rus: 'работа / деятельность' },
		{ eng: 'remember', rus: 'помнить / вспоминать' },
		{ eng: 'body', rus: 'тело / туловище' },
		{ eng: 'water', rus: 'вода / воды' },
		{ eng: 'work', rus: 'работать / трудиться' },
		{ eng: 'young', rus: 'молодой' },
		{ eng: 'until', rus: 'до' },
		{ eng: 'course', rus: 'курс / блюдо / курс обучения' },
		{ eng: 'between', rus: 'между' },
		{ eng: 'minute', rus: 'минута / момент' },
		{ eng: 'many', rus: 'многие / много' },
		{ eng: 'name', rus: 'имя / наименование / название' },
		{ eng: 'under', rus: 'под / ниже' },
		{ eng: 'lot', rus: 'большое количество / участок земли' },
		{ eng: 'die', rus: 'умирать / помирать / погибать' },
		{ eng: 'friend', rus: 'друг / подруга' },
		{ eng: 'more', rus: 'больше' },
		{ eng: 'send', rus: 'отправлять / посылать' },
		{ eng: 'car', rus: 'автомобиль / машина' },
		{ eng: 'girl', rus: 'девушка / девочка' },
		{ eng: 'hour', rus: 'час' },
		{ eng: 'May', rus: 'май' },
		{ eng: 'meet', rus: 'встречаться / встречать / знакомиться' },
		{ eng: 'end', rus: 'конец / окончание' },
		{ eng: 'live', rus: 'жить / существовать' },
		{ eng: 'understand', rus: 'понимать' },
		{ eng: 'show', rus: 'показывать / демонстрировать' },
		{ eng: 'late', rus: 'поздно / в конце' },
		{ eng: 'those', rus: 'те' },
		{ eng: 'those', rus: 'то' },
		{ eng: 'dark', rus: 'темный' },
		{ eng: 'help', rus: 'помощь' },
		{ eng: 'boy', rus: 'мальчик / пацан' },
		{ eng: 'hard', rus: 'жесткий / трудный' },
		{ eng: 'yes', rus: 'да' },
		{ eng: 'catch', rus: 'ловить / догонять' },
		{ eng: 'mother', rus: 'мать' },
		{ eng: 'bad', rus: 'плохой / дурной' },
		{ eng: 'open', rus: 'открытый' },
	],

	A2: [],

	B1: [],

	B2: [],

	C1: [],

	C2: [],
};

export async function GetWords(level: WordLevel) {
	const word = words[level][Math.floor(Math.random() * words[level].length)];
	console.log(Math.floor(Math.random() * words[level].length), word);
	return word;
}
