export const A1 = [
	{ eng: 'the', rus: 'этот' },
	{ eng: 'be', rus: 'быть / являться / находиться' },
	{ eng: 'to', rus: 'в направлении / чтобы' },
	{ eng: 'and', rus: 'и / а' },
	{ eng: 'a', rus: 'некий / один' },
	{ eng: 'of', rus: 'из / от / о' },
	{ eng: 'have', rus: 'иметь / обладать' },
	{ eng: 'I', rus: 'я' },
	{ eng: 'he', rus: 'он' },
	{ eng: 'you', rus: 'вы / ты' },
	{ eng: 'not', rus: 'не / ни' },
	{ eng: 'his', rus: 'его' },
	{ eng: 'it', rus: 'это / оно' },
	{ eng: 'do', rus: 'делать / заниматься' },
	{ eng: 'she', rus: 'она' },
	{ eng: 'in', rus: 'в / в течение' },
	{ eng: 'for', rus: 'для / на протяжении / за' },
	{ eng: 'with', rus: 'с / с помощью' },
	{ eng: 'her', rus: 'её' },
	{ eng: 'at', rus: 'на / в / у' },
	{ eng: 'but', rus: 'но' },
	{ eng: 'they', rus: 'они' },
	{ eng: 'that', rus: 'тот' },
	{ eng: 'back', rus: 'назад / обратно' },
	{ eng: 'him', rus: 'ему / его' },
	{ eng: 'we', rus: 'мы' },
	{ eng: 'can', rus: 'мочь / уметь' },
	{ eng: 'from', rus: 'от / из / у' },
	{ eng: 'there', rus: 'там / туда' },
	{ eng: 'go', rus: 'идти / ехать / проходить / уезжать' },
	{ eng: 'would', rus: 'бы' },
	{ eng: 'me', rus: 'меня / мне' },
	{ eng: 'will', rus: 'намереваться / собираться' },
	{ eng: 'on', rus: 'на / по' },
	{ eng: 'my', rus: 'мой / свой' },
	{ eng: 'what', rus: 'что' },
	{ eng: 'this', rus: 'это' },
	{ eng: 'get', rus: 'получать / становиться / добираться' },
	{ eng: 'know', rus: 'знать' },
	{ eng: 'as', rus: 'в качестве / так же ..., как' },
	{ eng: 'them', rus: 'их / им' },
	{ eng: 'see', rus: 'видеть / увидеть' },
	{ eng: 'then', rus: 'тогда / затем' },
	{ eng: 'look', rus: 'выглядеть / смотреть / взглянуть / глядеть' },
	{ eng: 'no', rus: 'нет' },
	{ eng: 'think', rus: 'думать' },
	{ eng: 'into', rus: 'в' },
	{ eng: 'come', rus: 'приходить / приезжать' },
	{ eng: 'say', rus: 'говорить / сказать' },
	{ eng: 'goodbye', rus: 'до свидания / прощай / пока' },
	{ eng: 'take', rus: 'взять или брать / занимать (время, место)' },
	{ eng: 'man', rus: 'мужчина / человек' },
	{ eng: 'make', rus: 'делать / изготавливать / заставлять' },
	{ eng: 'or', rus: 'или / либо' },
	{ eng: 'your', rus: 'ваш / твой' },
	{ eng: 'time', rus: 'время / количество раз' },
	{ eng: 'now', rus: 'теперь / сейчас' },
	{ eng: 'their', rus: 'их' },
	{ eng: 'about', rus: 'о / об' },
	{ eng: 'when', rus: 'когда' },
	{ eng: 'want', rus: 'хотеть' },
	{ eng: 'who', rus: 'кто / который' },
	{ eng: 'up', rus: 'вверх / выше / высоко' },
	{ eng: 'all', rus: 'все' },
	{ eng: 'more', rus: 'больший / дополнительный' },
	{ eng: 'tell', rus: 'рассказывать / поведать' },
	{ eng: 'here', rus: 'здесь / сюда' },
	{ eng: 'her', rus: 'ее / ей' },
	{ eng: 'some', rus: 'некоторый / несколько' },
	{ eng: 'like', rus: 'нравиться / любить' },
	{ eng: 'how', rus: 'как / насколько' },
	{ eng: 'hand', rus: 'рука / кисть руки' },
	{ eng: 'before', rus: 'перед чем-либо / до чего-либо' },
	{ eng: 'too', rus: 'слишком / тоже' },
	{ eng: 'eye', rus: 'глаз' },
	{ eng: 'give', rus: 'давать / отдавать / предоставлять' },
	{ eng: 'two', rus: 'два' },
	{ eng: 'us', rus: 'нас / нам' },
	{ eng: 'hello', rus: 'приветствие / привет' },
	{ eng: 'find', rus: 'находить / обнаруживать' },
	{ eng: 'other', rus: 'другой' },
	{ eng: 'thing', rus: 'вещь / штука' },
	{ eng: 'any', rus: 'любой / какой-нибудь' },
	{ eng: 'again', rus: 'снова / вновь' },
	{ eng: 'feel', rus: 'чувствовать / чувствовать себя / ощущать' },
	{ eng: 'only', rus: 'единственный' },
	{ eng: 'than', rus: 'чем / нежели' },
	{ eng: 'good', rus: 'хороший' },
	{ eng: 'something', rus: 'что-нибудь / кое-что' },
	{ eng: 'never', rus: 'никогда / никогда не' },
	{ eng: 'down', rus: 'вниз / внизу' },
	{ eng: 'well', rus: 'хорошо' },
	{ eng: 'very', rus: 'очень' },
	{ eng: 'face', rus: 'лицо / лицевая сторона' },
	{ eng: 'door', rus: 'дверь' },
	{ eng: 'our', rus: 'наш' },
	{ eng: 'hear', rus: 'слышать' },
	{ eng: 'head', rus: 'голова / глава' },
	{ eng: 'much', rus: 'много' },
	{ eng: 'little', rus: 'маленький / небольшой' },
	{ eng: 'day', rus: 'день / сутки' },
	{ eng: 'its', rus: 'его' },
	{ eng: 'people', rus: 'люди / народ' },
	{ eng: 'old', rus: 'старый / старший' },
	{ eng: 'where', rus: 'где / куда' },
	{ eng: 'why', rus: 'почему / зачем' },
	{ eng: 'one', rus: 'единственный / единый' },
	{ eng: 'one', rus: 'один' },
	{ eng: 'which', rus: 'который / какой из' },
	{ eng: 'need', rus: 'нуждаться / иметь потребность' },
	{ eng: 'room', rus: 'комната / помещение / пространство' },
	{ eng: 'own', rus: 'собственный' },
	{ eng: 'sit', rus: 'сидеть' },
	{ eng: 'because', rus: 'потому что / по причине / из-за' },
	{ eng: 'year', rus: 'год / курс обучения' },
	{ eng: 'put', rus: 'ставить / класть' },
	{ eng: 'hi', rus: 'привет / эй' },
	{ eng: 'woman', rus: 'женщина' },
	{ eng: 'begin', rus: 'начинать / приниматься' },
	{ eng: 'last', rus: 'последний / прошлый' },
	{ eng: 'anything', rus: 'что-нибудь' },
	{ eng: 'long', rus: 'длинный / долгий' },
	{ eng: 'place', rus: 'место' },
	{ eng: 'start', rus: 'начинать / стартовать / запускать' },
	{ eng: 'run', rus: 'бегать / работать' },
	{ eng: 'these', rus: 'эти' },
	{ eng: 'life', rus: 'жизнь' },
	{ eng: 'three', rus: 'три' },
	{ eng: 'leave', rus: 'оставлять / покидать' },
	{ eng: 'speak', rus: 'говорить / произносить' },
	{ eng: 'after', rus: 'после чего-либо / через сколько-то' },
	{ eng: 'wait', rus: 'ждать' },
	{ eng: 'use', rus: 'использовать / употреблять' },
	{ eng: 'night', rus: 'ночь / вечер' },
	{ eng: 'right', rus: 'правый / правильный' },
	{ eng: 'foot', rus: 'ступня / фут (0,304 м) / нога' },
	{ eng: 'word', rus: 'слово' },
	{ eng: 'watch', rus: 'наблюдать / смотреть' },
	{ eng: 'new', rus: 'новый' },
	{ eng: 'stop', rus: 'останавливать / прекращать' },
	{ eng: 'walk', rus: 'идти / ходить / гулять' },
	{ eng: 'arm', rus: 'рука' },
	{ eng: 'small', rus: 'маленький / небольшой' },
	{ eng: 'always', rus: 'всегда' },
	{ eng: 'both', rus: 'оба / обе' },
	{ eng: 'behind', rus: 'за / позади' },
	{ eng: 'OK', rus: 'окей' },
	{ eng: 'house', rus: 'дом / жилище' },
	{ eng: 'world', rus: 'мир' },
	{ eng: 'big', rus: 'большой / важный' },
	{ eng: 'great', rus: 'великий / отличный' },
	{ eng: 'really', rus: 'действительно / на самом деле' },
	{ eng: 'open', rus: 'открывать / раскрывать' },
	{ eng: 'about', rus: 'около / примерно' },
	{ eng: 'when', rus: 'когда / если' },
	{ eng: 'first', rus: 'первый' },
	{ eng: 'father', rus: 'отец / папа' },
	{ eng: 'every', rus: 'каждый / всякий' },
	{ eng: 'also', rus: 'также / еще' },
	{ eng: 'talk', rus: 'говорить / разговаривать' },
	{ eng: 'wall', rus: 'стена' },
	{ eng: 'work', rus: 'работа / деятельность' },
	{ eng: 'remember', rus: 'помнить / вспоминать' },
	{ eng: 'body', rus: 'тело / туловище' },
	{ eng: 'water', rus: 'вода / воды' },
	{ eng: 'work', rus: 'работать / трудиться' },
	{ eng: 'young', rus: 'молодой' },
	{ eng: 'until', rus: 'до' },
	{ eng: 'course', rus: 'курс / блюдо / курс обучения' },
	{ eng: 'between', rus: 'между' },
	{ eng: 'minute', rus: 'минута / момент' },
	{ eng: 'many', rus: 'многие / много' },
	{ eng: 'name', rus: 'имя / наименование / название' },
	{ eng: 'under', rus: 'под / ниже' },
	{ eng: 'lot', rus: 'большое количество / участок земли' },
	{ eng: 'die', rus: 'умирать / помирать / погибать' },
	{ eng: 'friend', rus: 'друг / подруга' },
	{ eng: 'more', rus: 'больше' },
	{ eng: 'send', rus: 'отправлять / посылать' },
	{ eng: 'car', rus: 'автомобиль / машина' },
	{ eng: 'girl', rus: 'девушка / девочка' },
	{ eng: 'hour', rus: 'час' },
	{ eng: 'May', rus: 'май' },
	{ eng: 'meet', rus: 'встречаться / встречать / знакомиться' },
	{ eng: 'end', rus: 'конец / окончание' },
	{ eng: 'live', rus: 'жить / существовать' },
	{ eng: 'understand', rus: 'понимать' },
	{ eng: 'show', rus: 'показывать / демонстрировать' },
	{ eng: 'late', rus: 'поздно / в конце' },
	{ eng: 'those', rus: 'те' },
	{ eng: 'those', rus: 'то' },
	{ eng: 'dark', rus: 'темный' },
	{ eng: 'help', rus: 'помощь' },
	{ eng: 'boy', rus: 'мальчик / пацан' },
	{ eng: 'hard', rus: 'жесткий / трудный' },
	{ eng: 'yes', rus: 'да' },
	{ eng: 'catch', rus: 'ловить / догонять' },
	{ eng: 'mother', rus: 'мать' },
	{ eng: 'bad', rus: 'плохой / дурной' },
	{ eng: 'open', rus: 'открытый' },
	{ eng: 'table', rus: 'стол / таблица' },
	{ eng: 'stay', rus: 'оставаться' },
	{ eng: 'part', rus: 'часть / роль / участие' },
	{ eng: 'better', rus: 'более хороший / лучше' },
	{ eng: 'question', rus: 'вопрос / расспрос' },
	{ eng: 'window', rus: 'окно / витрина' },
	{ eng: 'hair', rus: 'волос / волосы' },
	{ eng: 'wear', rus: 'одевать / носить' },
	{ eng: 'close', rus: 'близкий / тесный' },
	{ eng: 'light', rus: 'свет / огни чего-либо' },
	{ eng: 'together', rus: 'вместе' },
	{ eng: 'floor', rus: 'пол / этаж' },
	{ eng: 'morning', rus: 'утро' },
	{ eng: 'carry', rus: 'нести / проводить' },
	{ eng: 'city', rus: 'большой город' },
	{ eng: 'close', rus: 'закрывать / смыкать' },
	{ eng: 'bed', rus: 'кровать / постель / клумба / грядка' },
	{ eng: 'draw', rus: 'вытягивать / притягивать / рисовать' },
	{ eng: 'only', rus: 'только / лишь' },
	{ eng: 'four', rus: 'четыре' },
	{ eng: 'than', rus: 'чем / кроме' },
	{ eng: 'sleep', rus: 'спать' },
	{ eng: 'street', rus: 'улица' },
	{ eng: 'mouth', rus: 'рот / отверстие' },
	{ eng: 'thanks', rus: 'спасибо' },
	{ eng: 'chair', rus: 'стул / кресло' },
	{ eng: 'drive', rus: 'управлять автомобилем / ехать / везти / водить машину' },
	{ eng: 'change', rus: 'изменять / менять / переодевать' },
	{ eng: 'red', rus: 'красный / рыжий' },
	{ eng: 'five', rus: 'пять' },
	{ eng: 'learn', rus: 'учиться / изучать / узнавать' },
	{ eng: 'read', rus: 'читать / прочитать' },
	{ eng: 'listen', rus: 'слушать / выслушивать' },
	{ eng: 'same', rus: 'одинаковый / тот же самый' },
	{ eng: 'tree', rus: 'дерево' },
	{ eng: 'well', rus: 'хороший / здоровый' },
	{ eng: 'money', rus: 'деньги' },
	{ eng: 'next', rus: 'следующий / ближайший' },
	{ eng: 'eat', rus: 'есть / поедать' },
	{ eng: 'road', rus: 'дорога / путь' },
	{ eng: 'inside', rus: 'внутри / внутрь' },
	{ eng: 'write', rus: 'писать / записывать' },
	{ eng: 'leg', rus: 'нога / ножка' },
	{ eng: 'above', rus: 'выше / поверх / над' },
	{ eng: 'home', rus: 'дом / жилище' },
	{ eng: 'brother', rus: 'брат' },
	{ eng: 'week', rus: 'неделя' },
	{ eng: 'ten', rus: 'десять' },
	{ eng: 'family', rus: 'семья' },
	{ eng: 'son', rus: 'сын' },
	{ eng: 'book', rus: 'книга' },
	{ eng: 'near', rus: 'недалеко / близко' },
	{ eng: 'job', rus: 'работа / место работы' },
	{ eng: 'different', rus: 'разный / различный' },
	{ eng: 'ride', rus: 'кататься / ехать' },
	{ eng: 'short', rus: 'короткий' },
	{ eng: 'phone', rus: 'телефон' },
	{ eng: 'play', rus: 'играть' },
	{ eng: 'wife', rus: 'жена / супруга' },
	{ eng: 'answer', rus: 'ответ' },
	{ eng: 'where', rus: 'там, где / туда, куда' },
	{ eng: 'ready', rus: 'готовый / быть готовым' },
	{ eng: 'outside', rus: 'внешний' },
	{ eng: 'kind', rus: 'вид / тип' },
	{ eng: 'business', rus: 'бизнес / дело' },
	{ eng: 'this', rus: 'этот' },
	{ eng: 'black', rus: 'черный' },
	{ eng: 'blue', rus: 'синий / голубой' },
	{ eng: 'glass', rus: 'стекло / стакан / бокал' },
	{ eng: 'which', rus: 'который' },
	{ eng: 'problem', rus: 'проблема / задача' },
	{ eng: 'forget', rus: 'забывать' },
	{ eng: 'number', rus: 'номер / число' },
	{ eng: 'finish', rus: 'заканчивать / завершать / финишировать' },
	{ eng: 'easy', rus: 'легкий / нетрудный' },
	{ eng: 'half', rus: 'половина' },
	{ eng: 'horse', rus: 'лошадь / конь' },
	{ eng: 'drink', rus: 'пить / выпить' },
	{ eng: 'white', rus: 'белый' },
	{ eng: 'paper', rus: 'бумага / документ / газета' },
	{ eng: 'green', rus: 'зеленый' },
	{ eng: 'town', rus: 'небольшой город / городок' },
	{ eng: 'Miss', rus: 'мисс / барышня' },
	{ eng: 'sun', rus: 'солнце' },
	{ eng: 'month', rus: 'месяц' },
	{ eng: 'fly', rus: 'летать / прилететь' },
	{ eng: 'child', rus: 'ребенок / дитя' },
	{ eng: 'desk', rus: 'письменный стол / парта' },
	{ eng: 'sometimes', rus: 'иногда / временами' },
	{ eng: 'help', rus: 'помогать / оказывать помощь' },
	{ eng: 'grey', rus: 'серый / седой' },
	{ eng: 'mister', rus: 'мистер / господин' },
	{ eng: 'pay', rus: 'расплачиваться / платить' },
	{ eng: 'ear', rus: 'ухо / слух / колос / початок' },
	{ eng: 'travel', rus: 'путешествовать / перемещаться' },
	{ eng: 'wind', rus: 'ветер / дыхание' },
	{ eng: 'check', rus: 'проверять / сверять' },
	{ eng: 'six', rus: 'шесть' },
	{ eng: 'past', rus: 'мимо / за' },
	{ eng: 'early', rus: 'ранний / прежний' },
	{ eng: 'possible', rus: 'возможный / вероятный' },
	{ eng: 'late', rus: 'поздний / опаздывающий' },
	{ eng: 'sea', rus: 'море' },
	{ eng: 'second', rus: 'второй' },
	{ eng: 'person', rus: 'человек / личность' },
	{ eng: 'love', rus: 'любить' },
	{ eng: 'boat', rus: 'лодка / шлюпка' },
	{ eng: 'happy', rus: 'счастливый' },
	{ eng: 'answer', rus: 'отвечать' },
	{ eng: 'below', rus: 'ниже / внизу' },
	{ eng: 'tall', rus: 'высокий' },
	{ eng: 'dog', rus: 'собака / пес' },
	{ eng: "o'clock", rus: 'на часах / по часам' },
	{ eng: 'today', rus: 'сегодня / в наши дни' },
	{ eng: 'often', rus: 'часто / зачастую' },
	{ eng: 'important', rus: 'важный / значительный' },
	{ eng: 'buy', rus: 'покупать' },
	{ eng: 'mobile', rus: 'мобильный телефон / жилой автоприцеп' },
	{ eng: 'safe', rus: 'безопасный' },
	{ eng: 'food', rus: 'пища / еда' },
	{ eng: 'study', rus: 'изучать' },
	{ eng: 'left', rus: 'левый / левой' },
	{ eng: 'river', rus: 'река' },
	{ eng: 'hot', rus: 'горячий / жаркий' },
	{ eng: 'cold', rus: 'холодный / равнодушный' },
	{ eng: 'please', rus: 'пожалуйста' },
	{ eng: 'sister', rus: 'сестра' },
	{ eng: 'cannot', rus: 'не мочь' },
	{ eng: 'fine', rus: 'прекрасный / отличный' },
	{ eng: 'picture', rus: 'картина / изображение' },
	{ eng: 'quick', rus: 'быстрый / расторопный' },
	{ eng: 'behind', rus: 'сзади / позади' },
	{ eng: 'game', rus: 'игра / партия' },
	{ eng: 'sorry', rus: 'сожалеющий / огорченный' },
	{ eng: 'evening', rus: 'вечер' },
	{ eng: 'group', rus: 'группа / группировка' },
	{ eng: 'message', rus: 'сообщение / послание' },
	{ eng: 'nice', rus: 'приятный / хороший' },
	{ eng: 'wake', rus: 'просыпаться / будить' },
	{ eng: 'daughter', rus: 'дочь' },
	{ eng: 'choose', rus: 'выбирать / избирать' },
	{ eng: 'husband', rus: 'муж / супруг' },
	{ eng: 'kitchen', rus: 'кухня' },
	{ eng: 'tooth', rus: 'зуб / зубец' },
	{ eng: 'box', rus: 'коробка / ящик' },
	{ eng: 'bag', rus: 'сумка / мешок' },
	{ eng: 'country', rus: 'страна / сельская местность' },
	{ eng: 'letter', rus: 'письмо / буква' },
	{ eng: 'nose', rus: 'нос / носик' },
	{ eng: 'school', rus: 'школа' },
	{ eng: 'warm', rus: 'теплый' },
	{ eng: 'doctor', rus: 'доктор / врач' },
	{ eng: 'station', rus: 'станция / пункт' },
	{ eng: 'fast', rus: 'быстрый' },
	{ eng: 'tomorrow', rus: 'завтра' },
	{ eng: 'dear', rus: 'дорогой' },
	{ eng: 'animal', rus: 'животное / зверь' },
	{ eng: 'party', rus: 'вечеринка / партия' },
	{ eng: 'age', rus: 'возраст' },
	{ eng: 'knife', rus: 'нож' },
	{ eng: 'afternoon', rus: 'после полудня / полдень' },
	{ eng: 'key', rus: 'ключ / клавиша' },
	{ eng: 'clothes', rus: 'одежда' },
	{ eng: 'poor', rus: 'бедный / плохой' },
	{ eng: 'slow', rus: 'медленный / вялотекущий / несообразительный' },
	{ eng: 'enjoy', rus: 'наслаждаться / получать удовольствие' },
	{ eng: 'dinner', rus: 'ужин / обед' },
	{ eng: 'beautiful', rus: 'красивый / прекрасный' },
	{ eng: 'tonight', rus: 'сегодня вечером / сегодня ночью' },
	{ eng: 'noise', rus: 'шум' },
	{ eng: 'bar', rus: 'бар / брусок / пруток' },
	{ eng: 'coffee', rus: 'кофе' },
	{ eng: 'baby', rus: 'малыш' },
	{ eng: 'computer', rus: 'компьютер / вычислитель' },
	{ eng: 'rain', rus: 'дождь / град' },
	{ eng: 'until', rus: 'до тех пор, пока / до тех пор, пока не' },
	{ eng: 'taxi', rus: 'такси / вызов такси' },
	{ eng: 'sandwich', rus: 'бутерброд / сэндвич' },
	{ eng: 'conversation', rus: 'разговор / беседа' },
	{ eng: 'wrong', rus: 'неправильный / неверный' },
	{ eng: 'note', rus: 'записка / нота' },
	{ eng: 'many', rus: 'многие' },
	{ eng: 'under', rus: 'вниз / внизу' },
	{ eng: 'colour', rus: 'цвет / краситель' },
	{ eng: 'future', rus: 'будущее / фьючерс' },
	{ eng: 'teach', rus: 'учить / преподавать' },
	{ eng: 'cat', rus: 'кошка / кот' },
	{ eng: 'brown', rus: 'коричневый / загорелый / бурый' },
	{ eng: 'drink', rus: 'напиток / глоток' },
	{ eng: 'bird', rus: 'птица / пташка' },
	{ eng: 'hard', rus: 'упорно / трудно / сильно' },
	{ eng: 'eight', rus: 'восемь' },
	{ eng: 'kick', rus: 'пинать / лягать' },
	{ eng: 'seven', rus: 'семь' },
	{ eng: 'close', rus: 'близко / вплотную' },
	{ eng: 'present', rus: 'подарок / настоящее время' },
	{ eng: 'shirt', rus: 'рубашка / блуза' },
	{ eng: 'hotel', rus: 'отель / гостиница' },
	{ eng: 'difficult', rus: 'трудный' },
	{ eng: 'bottom', rus: 'нижняя часть / дно / подножие' },
	{ eng: 'bank', rus: 'банк / берег' },
	{ eng: 'best', rus: 'лучший / самый лучший' },
	{ eng: 'driver', rus: 'водитель / драйвер' },
	{ eng: 'no', rus: 'никакой' },
	{ eng: 'flat', rus: 'квартира / плоскость' },
	{ eng: 'cup', rus: 'чашка / стакан / кубок' },
	{ eng: 'closed', rus: 'закрытый / замкнутый' },
	{ eng: 'snow', rus: 'снег / снегопад' },
	{ eng: 'clock', rus: 'часы / циферблат' },
	{ eng: 'each', rus: 'каждый' },
	{ eng: 'yellow', rus: 'желтый / трусливый' },
	{ eng: 'clean', rus: 'чистый / опрятный' },
	{ eng: 'busy', rus: 'занятой / оживленный' },
	{ eng: 'interest', rus: 'интерес / увлечение' },
	{ eng: 'grass', rus: 'трава' },
	{ eng: 'summer', rus: 'лето' },
	{ eng: 'village', rus: 'деревня / село' },
	{ eng: 'language', rus: 'язык / речь' },
	{ eng: 'boot', rus: 'ботинок / багажник' },
	{ eng: 'hospital', rus: 'больница / госпиталь' },
	{ eng: 'winter', rus: 'зима' },
	{ eng: 'quarter', rus: 'квартал / четверть' },
	{ eng: 'music', rus: 'музыка / ноты' },
	{ eng: 'parent', rus: 'родитель' },
	{ eng: 'bedroom', rus: 'спальня / спальная' },
	{ eng: 'paint', rus: 'красить' },
	{ eng: 'jacket', rus: 'куртка / пиджак' },
	{ eng: 'board', rus: 'доска / борт' },
	{ eng: 'radio', rus: 'радио / радиоприемник' },
	{ eng: 'sing', rus: 'петь / воспевать' },
	{ eng: 'garden', rus: 'сад / парк' },
	{ eng: 'plane', rus: 'самолет / плоскость' },
	{ eng: 'fifteen', rus: 'пятнадцать' },
	{ eng: 'coat', rus: 'пальто / слой' },
	{ eng: 'page', rus: 'страница / паж' },
	{ eng: 'plate', rus: 'тарелка / пластина' },
	{ eng: 'shop', rus: 'магазин / лавка' },
	{ eng: 'beer', rus: 'пиво / кружка пива' },
	{ eng: 'beach', rus: 'пляж / берег моря' },
	{ eng: 'ball', rus: 'мяч / шар / бал' },
	{ eng: 'subject', rus: 'предмет / тема' },
	{ eng: 'dad', rus: 'папа' },
	{ eng: 'pizza', rus: 'пицца' },
	{ eng: 'yesterday', rus: 'вчера / совсем недавно' },
	{ eng: 'breakfast', rus: 'завтрак / утренний завтрак' },
	{ eng: 'shoe', rus: 'туфля / башмак' },
	{ eng: 'tea', rus: 'чай / чайный лист' },
	{ eng: 'camera', rus: 'камера / фотокамера' },
	{ eng: 'fish', rus: 'рыба / рыбная ловля' },
	{ eng: 'nine', rus: 'девять' },
	{ eng: 'July', rus: 'июль' },
	{ eng: 'dollar', rus: 'доллар' },
	{ eng: 'hat', rus: 'шляпа / шапка' },
	{ eng: 'cheese', rus: 'сыр / творог' },
	{ eng: 'inside', rus: 'внутренний / скрытый' },
	{ eng: 'inside', rus: 'внутри / в' },
	{ eng: 'visit', rus: 'посещать / навещать' },
	{ eng: 'fat', rus: 'тучный / толстый' },
	{ eng: 'funny', rus: 'смешной / странный' },
	{ eng: 'lunch', rus: 'обед / ланч' },
	{ eng: 'song', rus: 'песня / пение' },
	{ eng: 'store', rus: 'магазин / запас' },
	{ eng: 'wash', rus: 'мыть / стирать' },
	{ eng: 'plant', rus: 'растение / завод' },
	{ eng: 'juice', rus: 'сок' },
	{ eng: 'weather', rus: 'погода / непогода' },
	{ eng: 'twelve', rus: 'двенадцать' },
	{ eng: 'train', rus: 'поезд / состав' },
	{ eng: 'swim', rus: 'плыть / плавать' },
	{ eng: 'stop', rus: 'остановка / стоянка' },
	{ eng: 'fun', rus: 'забава / веселье / развлечение' },
	{ eng: 'class', rus: 'класс / урок / занятие' },
	{ eng: 'dance', rus: 'танцевать / плясать' },
	{ eng: 'outside', rus: 'на улице / снаружи' },
	{ eng: 'flower', rus: 'цветок' },
	{ eng: 'vegetable', rus: 'овощ' },
	{ eng: 'egg', rus: 'яйцо' },
	{ eng: 'test', rus: 'тест / контрольная работа' },
	{ eng: 'meal', rus: 'еда / трапеза / прием пищи' },
	{ eng: 'meat', rus: 'мясо' },
	{ eng: 'clean', rus: 'чистить / вычищать' },
	{ eng: 'excuse', rus: 'извинять / прощать' },
	{ eng: 'band', rus: 'группа / полоса' },
	{ eng: 'invite', rus: 'приглашать / просить' },
	{ eng: 'bathroom', rus: 'ванная комната / туалет' },
	{ eng: 'sad', rus: 'печальный / грустный' },
	{ eng: 'student', rus: 'студент / ученик' },
	{ eng: 'movie', rus: 'кино / фильм' },
	{ eng: 'beard', rus: 'борода / ость' },
	{ eng: 'hungry', rus: 'голодный' },
	{ eng: 'sugar', rus: 'сахар / сахароза' },
	{ eng: 'early', rus: 'рано / преждевременно' },
	{ eng: 'reading', rus: 'чтение / считывание' },
	{ eng: 'dance', rus: 'танец / пляска' },
	{ eng: 'pen', rus: 'ручка / перо' },
	{ eng: 'address', rus: 'адрес / обращение' },
	{ eng: 'bread', rus: 'хлеб / кусок хлеба' },
	{ eng: 'mom', rus: 'мама / мамочка' },
	{ eng: 'near', rus: 'возле' },
	{ eng: 'orange', rus: 'апельсин / оранжевый цвет' },
	{ eng: 'dine', rus: 'обедать / поужинать' },
	{ eng: 'date', rus: 'дата / свидание / финик' },
	{ eng: 'bus', rus: 'автобус' },
	{ eng: 'park', rus: 'парк / парковка' },
	{ eng: 'sweet', rus: 'сладкий / милый' },
	{ eng: 'clever', rus: 'умный / ловкий' },
	{ eng: 'some', rus: 'некоторые' },
	{ eng: 'restaurant', rus: 'ресторан / заведение' },
	{ eng: 'watch', rus: 'часы / вахта' },
	{ eng: 'farm', rus: 'ферма' },
	{ eng: 'photo', rus: 'фотография / фото' },
	{ eng: 'cross', rus: 'крест' },
	{ eng: 'interesting', rus: 'интересный' },
	{ eng: 'example', rus: 'пример / образец' },
	{ eng: 'dress', rus: 'платье / одежда' },
	{ eng: 'excited', rus: 'воодушевленный / взволнованный' },
	{ eng: 'eleven', rus: 'одиннадцать' },
	{ eng: 'lesson', rus: 'урок / занятие' },
	{ eng: 'shower', rus: 'душ / ливень' },
	{ eng: 'March', rus: 'март' },
	{ eng: 'university', rus: 'университет / университетская спортивная команда' },
	{ eng: 'Sunday', rus: 'воскресенье' },
	{ eng: 'internet', rus: 'интернет' },
	{ eng: 'favourite', rus: 'любимый / излюбленный' },
	{ eng: 'teacher', rus: 'учитель / преподаватель' },
	{ eng: 'cheap', rus: 'дешевый / низкий' },
	{ eng: 'fruit', rus: 'фрукт / фрукты' },
	{ eng: 'expensive', rus: 'дорогой / дорогостоящий' },
	{ eng: 'cook', rus: 'готовить пищу' },
	{ eng: 'player', rus: 'игрок / музыкант' },
	{ eng: 'film', rus: 'фильм / кино / пленка' },
	{ eng: 'famous', rus: 'знаменитый / известный' },
	{ eng: 'practise', rus: 'практиковать / тренироваться' },
	{ eng: 'adult', rus: 'взрослый человек / взрослый' },
	{ eng: 'sentence', rus: 'предложение в тексте / приговор суда' },
	{ eng: 'bath', rus: 'ванна / баня' },
	{ eng: 'television', rus: 'телевидение' },
	{ eng: 'skirt', rus: 'юбка' },
	{ eng: 'phone', rus: 'звонить' },
	{ eng: 'pants', rus: 'брюки / штаны' },
	{ eng: 'ticket', rus: 'билет / талон' },
	{ eng: 'T-shirt', rus: 'футболка / майка' },
	{ eng: 'glasses', rus: 'очки' },
	{ eng: 'Saturday', rus: 'суббота' },
	{ eng: 'jeans', rus: 'джинсы' },
	{ eng: 'trousers', rus: 'брюки / штаны' },
	{ eng: 'guitar', rus: 'гитара' },
	{ eng: 'apple', rus: 'яблоко / яблоня' },
	{ eng: 'slim', rus: 'стройный / тонкий' },
	{ eng: 'smoke', rus: 'курить / дымить' },
	{ eng: 'Friday', rus: 'пятница' },
	{ eng: 'milk', rus: 'молоко / латекс' },
	{ eng: 'eighteen', rus: 'восемнадцать' },
	{ eng: 'bored', rus: 'заскучавший' },
	{ eng: 'salt', rus: 'соль / поваренная соль' },
	{ eng: 'weekend', rus: 'выходной день' },
	{ eng: 'pig', rus: 'свинья' },
	{ eng: 'rain', rus: 'льет дождь / идет дождь' },
	{ eng: 'buck', rus: 'бакс / доллар' },
	{ eng: 'website', rus: 'сайт в Интернете / веб-сайт' },
	{ eng: 'what', rus: 'какой' },
	{ eng: 'Monday', rus: 'понедельник' },
	{ eng: 'sport', rus: 'спорт' },
	{ eng: 'fourteen', rus: 'четырнадцать' },
	{ eng: 'waiter', rus: 'официант' },
	{ eng: 'soup', rus: 'суп' },
	{ eng: 'factory', rus: 'завод / фабрика' },
	{ eng: 'sixteen', rus: 'шестнадцать' },
	{ eng: 'biscuit', rus: 'печенье / жесткое печенье' },
	{ eng: 'carrier', rus: 'перевозчик / курьер' },
	{ eng: 'downstairs', rus: 'вниз / вниз по лестнице' },
	{ eng: 'sheep', rus: 'овца / овчина' },
	{ eng: 'birthday', rus: 'день рождения / дата рождения' },
	{ eng: 'newspaper', rus: 'газета / газетка' },
	{ eng: 'holiday', rus: 'праздник / отпуск / каникулы' },
	{ eng: 'cake', rus: 'торт / кекс' },
	{ eng: 'smoking', rus: 'курение / копчение' },
	{ eng: 'toilet', rus: 'туалет / унитаз' },
	{ eng: 'pencil', rus: 'карандаш / кисть' },
	{ eng: 'October', rus: 'октябрь' },
	{ eng: 'bike', rus: 'велосипед / мотоцикл' },
	{ eng: 'thirteen', rus: 'тринадцать' },
	{ eng: 'exciting', rus: 'увлекательный' },
	{ eng: 'shopping', rus: 'покупка товаров в магазинах / шопинг' },
	{ eng: 'pet', rus: 'домашний питомец / домашнее животное' },
	{ eng: 'Tuesday', rus: 'вторник' },
	{ eng: 'seventeen', rus: 'семнадцать' },
	{ eng: 'dancing', rus: 'танец / пляска' },
	{ eng: 'bookcase', rus: 'книжный шкаф' },
	{ eng: 'boring', rus: 'скучный' },
	{ eng: 'vacation', rus: 'отпуск / каникулы' },
	{ eng: 'doll', rus: 'кукла' },
	{ eng: 'Thursday', rus: 'четверг' },
	{ eng: 'email', rus: 'электронная почта' },
	{ eng: 'blouse', rus: 'блузка / блуза' },
	{ eng: 'waitress', rus: 'официантка' },
	{ eng: 'cow', rus: 'корова / самка кита' },
	{ eng: 'chocolate', rus: 'шоколад / шоколадка' },
	{ eng: 'potato', rus: 'картофель / картофелина' },
	{ eng: 'Wednesday', rus: 'среда' },
	{ eng: 'nineteen', rus: 'девятнадцать' },
	{ eng: 'museum', rus: 'музей / музейное дело' },
	{ eng: 'agony', rus: 'мука / агония' },
	{ eng: 'August', rus: 'август' },
	{ eng: 'football', rus: 'футбол / футбольный мяч' },
	{ eng: 'refrigerator', rus: 'холодильник / рефрижератор' },
	{ eng: 'bean', rus: 'боб / фасоль' },
	{ eng: 'June', rus: 'июнь' },
	{ eng: 'butter', rus: 'масло / сливочное масло' },
	{ eng: 'mum', rus: 'мама' },
	{ eng: 'rice', rus: 'рис' },
	{ eng: 'tennis', rus: 'теннис' },
	{ eng: 'picnic', rus: 'пикник / удовольствие' },
	{ eng: 'zoo', rus: 'зоопарк / зоо' },
	{ eng: 'actress', rus: 'актриса / артистка' },
	{ eng: 'April', rus: 'апрель' },
	{ eng: 'chip', rus: 'обломок / чип' },
	{ eng: 'subway', rus: 'метро / подземный переход' },
	{ eng: 'paint', rus: 'краска / окраска' },
	{ eng: 'salvation', rus: 'спасение / спасение души' },
	{ eng: 'September', rus: 'сентябрь' },
	{ eng: 'November', rus: 'ноябрь' },
	{ eng: 'January', rus: 'январь' },
	{ eng: 'homework', rus: 'домашнее задание' },
	{ eng: 'tomato', rus: 'помидор / томат' },
	{ eng: 'December', rus: 'декабрь' },
	{ eng: 'classroom', rus: 'класс / классная комната' },
	{ eng: 'cafe', rus: 'кафе / кофейня' },
	{ eng: 'banana', rus: 'банан' },
	{ eng: 'bat', rus: 'летучая мышь / бита' },
	{ eng: 'all', rus: 'целый / весь' },
	{ eng: 'supermarket', rus: 'супермаркет / магазин самообслуживания' },
	{ eng: 'February', rus: 'февраль' },
	{ eng: 'dictionary', rus: 'словарь' },
	{ eng: 'lot', rus: 'многие' },
	{ eng: 'nationality', rus: 'гражданство / национальность' },
	{ eng: 'talking', rus: 'разговор / болтовня' },
	{ eng: 'scorpion', rus: 'скорпион / бич с металлическими шипами' },
	{ eng: 'eraser', rus: 'ластик / резинка' },
	{ eng: 'good', rus: 'хорошо' },
	{ eng: 'enough', rus: 'достаточное количество' },
	{ eng: 'both', rus: 'оба' },
	{ eng: 'Oh', rus: 'Ой' },
	{ eng: 'English', rus: 'английский язык / англичане' },
	{ eng: 'English', rus: 'английский' },
	{ eng: 'back', rus: 'задний / обратный' },
	{ eng: 'sorry', rus: 'извините / простите' },
	{ eng: 'more', rus: 'больше / более' },
];
