export const A2 = [
	{ eng: 'in', rus: 'внутрь / во время' },
	{ eng: 'that', rus: 'то / это / который' },
	{ eng: 'if', rus: 'если / ли' },
	{ eng: 'on', rus: 'далее' },
	{ eng: 'out', rus: 'вне / вон' },
	{ eng: 'as', rus: 'как' },
	{ eng: 'so', rus: 'так / настолько' },
	{ eng: 'by', rus: 'у / за' },
	{ eng: 'just', rus: 'просто / только что / как раз / всего лишь' },
	{ eng: 'all', rus: 'весь / полностью / совсем' },
	{ eng: 'one', rus: 'один / кто-то' },
	{ eng: 'up', rus: 'вверх по / снизу вверх' },
	{ eng: 'way', rus: 'путь / способ' },
	{ eng: 'turn', rus: 'поворачивать / сворачивать' },
	{ eng: 'through', rus: 'через / сквозь' },
	{ eng: 'even', rus: 'даже' },
	{ eng: 'over', rus: 'над / поверх' },
	{ eng: 'like', rus: 'подобно / словно' },
	{ eng: 'around', rus: 'вокруг / приблизительно' },
	{ eng: 'away', rus: 'прочь / далеко' },
	{ eng: 'still', rus: 'все еще / еще / до сих пор' },
	{ eng: 'off', rus: 'прочь' },
	{ eng: 'try', rus: 'пытаться / стараться' },
	{ eng: 'that', rus: 'что / чтобы' },
	{ eng: 'may', rus: 'можно ли / может быть' },
	{ eng: 'stand', rus: 'стоять / встать' },
	{ eng: 'keep', rus: 'хранить / держать / продолжать' },
	{ eng: 'down', rus: 'вниз по' },
	{ eng: 'let', rus: 'позволять' },
	{ eng: 'himself', rus: 'сам себя / он сам' },
	{ eng: 'ask', rus: 'спрашивать / просить / задавать вопрос' },
	{ eng: 'must', rus: 'должен' },
	{ eng: 'hold', rus: 'держать / хранить' },
	{ eng: 'move', rus: 'двигаться / перемещаться' },
	{ eng: 'should', rus: 'следовало бы / следует' },
	{ eng: 'out', rus: 'из' },
	{ eng: 'moment', rus: 'момент / мгновение' },
	{ eng: 'little', rus: 'мало / немного' },
	{ eng: 'nothing', rus: 'ничего / ничто' },
	{ eng: 'mean', rus: 'значить / означать / иметь в виду' },
	{ eng: 'against', rus: 'против / напротив / к' },
	{ eng: 'side', rus: 'сторона / бок' },
	{ eng: 'call', rus: 'называть / звать / звонить / вызвать' },
	{ eng: 'few', rus: 'несколько / немного' },
	{ eng: 'long', rus: 'долго / давно' },
	{ eng: 'enough', rus: 'достаточно' },
	{ eng: 'once', rus: 'однажды / один раз / прежде' },
	{ eng: 'bring', rus: 'приносить / привозить / приводить' },
	{ eng: 'while', rus: 'пока / в то время как' },
	{ eng: 'far', rus: 'далеко / гораздо / намного' },
	{ eng: 'fall', rus: 'падать / опускаться' },
	{ eng: 'so', rus: 'поэтому / так что' },
	{ eng: 'happen', rus: 'происходить / случаться' },
	{ eng: 'maybe', rus: 'может быть / возможно' },
	{ eng: 'after', rus: 'после / впоследствии' },
	{ eng: 'ever', rus: 'всегда / когда-либо' },
	{ eng: 'kill', rus: 'убивать / губить' },
	{ eng: 'almost', rus: 'почти / едва не' },
	{ eng: 'across', rus: 'через / поперек' },
	{ eng: 'mind', rus: 'возражать / помнить' },
	{ eng: 'pull', rus: 'тянуть / тащить' },
	{ eng: 'most', rus: 'многие / самый / наибольший' },
	{ eng: 'without', rus: 'без / вне' },
	{ eng: 'believe', rus: 'верить / считать / полагать' },
	{ eng: 'first', rus: 'впервые / сперва' },
	{ eng: 'lie', rus: 'лежать' },
	{ eng: 'follow', rus: 'следовать / сопровождать' },
	{ eng: 'sure', rus: 'уверенный' },
	{ eng: 'else', rus: 'еще' },
	{ eng: 'reach', rus: 'достигать / дотягиваться' },
	{ eng: 'right', rus: 'прямо / верно / направо' },
	{ eng: 'already', rus: 'уже' },
	{ eng: 'yet', rus: 'еще / уже' },
	{ eng: 'another', rus: 'другой / еще один' },
	{ eng: 'ship', rus: 'корабль / судно' },
	{ eng: 'such', rus: 'такой / подобный' },
	{ eng: 'shake', rus: 'трясти / качать / пожимать' },
	{ eng: 'left', rus: 'слева / налево' },
	{ eng: 'become', rus: 'становиться / превращаться' },
	{ eng: 'soon', rus: 'скоро / вскоре' },
	{ eng: 'pass', rus: 'проходить / передавать' },
	{ eng: 'air', rus: 'воздух / атмосфера' },
	{ eng: 'along', rus: 'вдоль' },
	{ eng: 'front', rus: 'передняя часть / фасад' },
	{ eng: 'return', rus: 'возвращать / возвращаться' },
	{ eng: 'dead', rus: 'мертвый' },
	{ eng: 'break', rus: 'ломать / разбивать / нарушать' },
	{ eng: 'set', rus: 'набор / комплект' },
	{ eng: 'everything', rus: 'всё' },
	{ eng: 'someone', rus: 'кто-то / некто' },
	{ eng: 'perhaps', rus: 'возможно / наверное' },
	{ eng: 'sound', rus: 'звук' },
	{ eng: 'quite', rus: 'довольно / вполне / совсем' },
	{ eng: 'herself', rus: 'себя' },
	{ eng: 'matter', rus: 'вопрос для рассмотрения / дело' },
	{ eng: 'since', rus: 'с тех пор, как / с / после' },
	{ eng: 'line', rus: 'линия / строка' },
	{ eng: 'probably', rus: 'вероятно / наверное' },
	{ eng: 'grow', rus: 'расти / выращивать / становиться' },
	{ eng: 'suppose', rus: 'полагать / предполагать' },
	{ eng: 'high', rus: 'высокий' },
	{ eng: 'lose', rus: 'терять / проигрывать' },
	{ eng: 'finger', rus: 'палец' },
	{ eng: 'over', rus: 'свыше / над' },
	{ eng: 'might', rus: 'можно / мочь' },
	{ eng: 'fire', rus: 'огонь / костер / пожар' },
	{ eng: 'idea', rus: 'идея / представление' },
	{ eng: 'case', rus: 'случай / ситуация / дело / футляр' },
	{ eng: 'laugh', rus: 'смеяться / хохотать' },
	{ eng: 'large', rus: 'большой' },
	{ eng: 'miss', rus: 'скучать / пропускать / промахиваться' },
	{ eng: 'myself', rus: 'себе / себя / сам' },
	{ eng: 'slowly', rus: 'медленно / неспешно' },
	{ eng: 'anyone', rus: 'любой / никто' },
	{ eng: 'real', rus: 'реальный / настоящий' },
	{ eng: 'guy', rus: 'парень' },
	{ eng: 'full', rus: 'полный / заполненный' },
	{ eng: 'ago', rus: 'назад / тому назад' },
	{ eng: 'office', rus: 'офис / кабинет' },
	{ eng: 'reason', rus: 'причина / повод' },
	{ eng: 'better', rus: 'лучше' },
	{ eng: 'rest', rus: 'оставшаяся часть / отдых' },
	{ eng: 'throw', rus: 'бросать / кидать' },
	{ eng: 'hundred', rus: 'сто' },
	{ eng: 'heart', rus: 'сердце / сердцевина' },
	{ eng: 'fact', rus: 'факт / данность' },
	{ eng: 'push', rus: 'толкать / нажимать' },
	{ eng: 'several', rus: 'несколько' },
	{ eng: 'decide', rus: 'решать / принимать решение' },
	{ eng: 'blood', rus: 'кровь' },
	{ eng: 'whole', rus: 'целый / весь' },
	{ eng: 'second', rus: 'секунда / мгновение' },
	{ eng: 'able', rus: 'способный / в состоянии' },
	{ eng: 'bit', rus: 'кусочек / немного / небольшое количество' },
	{ eng: 'sort', rus: 'сорт / вид / тип' },
	{ eng: 'war', rus: 'война / борьба' },
	{ eng: 'call', rus: 'вызов / телефонный звонок' },
	{ eng: 'beside', rus: 'рядом с / около' },
	{ eng: 'hope', rus: 'надеяться' },
	{ eng: 'point', rus: 'указывать' },
	{ eng: 'build', rus: 'строить / создавать' },
	{ eng: 'same', rus: 'тот же / то же самое' },
	{ eng: 'quickly', rus: 'быстро' },
	{ eng: 'deep', rus: 'глубокий / низкий' },
	{ eng: 'cut', rus: 'резать' },
	{ eng: 'finally', rus: 'окончательно / в конце концов / наконец-то' },
	{ eng: 'next', rus: 'рядом / далее / потом' },
	{ eng: 'story', rus: 'рассказ / история / сюжет' },
	{ eng: 'sound', rus: 'звучать' },
	{ eng: 'love', rus: 'любовь' },
	{ eng: 'guess', rus: 'полагать' },
	{ eng: 'hit', rus: 'ударять / поражать' },
	{ eng: 'fill', rus: 'заполнять / наполнять' },
	{ eng: 'everyone', rus: 'каждый / все' },
	{ eng: 'true', rus: 'истинный / правдивый' },
	{ eng: 'strong', rus: 'сильный / крепкий' },
	{ eng: 'continue', rus: 'продолжать / продолжаться' },
	{ eng: 'order', rus: 'приказ / заказ / порядок / ордер' },
	{ eng: 'strange', rus: 'странный / незнакомый' },
	{ eng: 'pretty', rus: 'хорошенький' },
	{ eng: 'home', rus: 'домой' },
	{ eng: 'clear', rus: 'ясный / явный / четкий' },
	{ eng: 'except', rus: 'за исключением / кроме' },
	{ eng: 'notice', rus: 'замечать / уведомлять' },
	{ eng: 'alone', rus: 'одинокий / один' },
	{ eng: 'shall', rus: 'следует' },
	{ eng: 'top', rus: 'верх / вершина' },
	{ eng: 'instead', rus: 'вместо / взамен' },
	{ eng: 'low', rus: 'низкий / невысокий' },
	{ eng: 'among', rus: 'среди / между' },
	{ eng: 'offer', rus: 'предлагать / возносить' },
	{ eng: 'wish', rus: 'желание / пожелание' },
	{ eng: 'heavy', rus: 'тяжелый / сильный' },
	{ eng: 'enter', rus: 'входить / вводить' },
	{ eng: 'hall', rus: 'прихожая / зал' },
	{ eng: 'space', rus: 'пространство / космос / промежуток' },
	{ eng: 'pain', rus: 'боль / страдание' },
	{ eng: 'arrive', rus: 'прибывать' },
	{ eng: 'sky', rus: 'небо' },
	{ eng: 'however', rus: 'однако / тем не менее' },
	{ eng: 'anyway', rus: 'в любом случае / так или иначе' },
	{ eng: 'cover', rus: 'покрывать / накрывать' },
	{ eng: 'save', rus: 'сохранять / спасать' },
	{ eng: 'kind', rus: 'добрый / любезный' },
	{ eng: 'spend', rus: 'тратить / проводить' },
	{ eng: 'corner', rus: 'угол / уголок' },
	{ eng: 'star', rus: 'звезда' },
	{ eng: 'itself', rus: 'себя / само себя' },
	{ eng: 'yourself', rus: 'ты сам / сам себя' },
	{ eng: 'figure', rus: 'рисунок / фигура' },
	{ eng: 'actually', rus: 'действительно / фактически / на самом деле' },
	{ eng: 'police', rus: 'полиция' },
	{ eng: 'themselves', rus: 'сами / сами себя' },
	{ eng: 'nearly', rus: 'почти / приблизительно' },
	{ eng: 'company', rus: 'компания / общество' },
	{ eng: 'exactly', rus: 'точно / именно / как раз' },
	{ eng: 'piece', rus: 'кусок / пьеса' },
	{ eng: 'explain', rus: 'объяснять / разъяснять' },
	{ eng: 'past', rus: 'прошлое / прошедшее время' },
	{ eng: 'use', rus: 'использование / применение' },
	{ eng: 'afraid', rus: 'испуганный / напуганный' },
	{ eng: 'thousand', rus: 'тысяча' },
	{ eng: 'bright', rus: 'яркий / светлый' },
	{ eng: 'pocket', rus: 'карман' },
	{ eng: 'sign', rus: 'знак / признак' },
	{ eng: 'somewhere', rus: 'где-то / куда-то' },
	{ eng: 'jump', rus: 'прыгать / подпрыгивать' },
	{ eng: 'wide', rus: 'широкий / большой' },
	{ eng: 'empty', rus: 'пустой / порожний' },
	{ eng: 'thank', rus: 'благодарить / выражать благодарность' },
	{ eng: 'nobody', rus: 'никто' },
	{ eng: 'somebody', rus: 'кто-то / кто-нибудь' },
	{ eng: 'cry', rus: 'кричать / плакать' },
	{ eng: 'news', rus: 'новость / известие' },
	{ eng: 'centre', rus: 'центр / середина' },
	{ eng: 'wood', rus: 'лес / древесина' },
	{ eng: 'hill', rus: 'холм / возвышенность' },
	{ eng: 'screen', rus: 'экран / ширма' },
	{ eng: 'mountain', rus: 'гора / куча' },
	{ eng: 'right', rus: 'право / правая сторона' },
	{ eng: 'south', rus: 'южное направление / юг страны' },
	{ eng: 'thin', rus: 'тонкий / худой' },
	{ eng: 'surprise', rus: 'сюрприз / удивление' },
	{ eng: 'dress', rus: 'одеваться / одевать' },
	{ eng: 'kiss', rus: 'целовать / поцеловать' },
	{ eng: 'serve', rus: 'служить / обслуживать / подавать' },
	{ eng: 'cold', rus: 'холод / простуда' },
	{ eng: 'show', rus: 'шоу / показ' },
	{ eng: 'dream', rus: 'мечта / сон' },
	{ eng: 'third', rus: 'третий' },
	{ eng: 'brain', rus: 'мозг / мозги' },
	{ eng: 'end', rus: 'заканчивать / покончить / положить конец' },
	{ eng: 'without', rus: 'снаружи / без того' },
	{ eng: 'glad', rus: 'радостный / довольный' },
	{ eng: 'fast', rus: 'быстро' },
	{ eng: 'middle', rus: 'середина / центр' },
	{ eng: 'form', rus: 'форма / бланк / вид' },
	{ eng: 'single', rus: 'один / единый / неженатый или незамужняя' },
	{ eng: 'thinking', rus: 'размышление / взгляды' },
	{ eng: 'agree', rus: 'соглашаться / договариваться' },
	{ eng: 'round', rus: 'круглый / круговой' },
	{ eng: 'pale', rus: 'бледный / слабый' },
	{ eng: 'sure', rus: 'уверенно / наверняка' },
	{ eng: 'text', rus: 'текст' },
	{ eng: "let's", rus: 'давай' },
	{ eng: 'simple', rus: 'простой / несложный' },
	{ eng: 'path', rus: 'тропинка / путь' },
	{ eng: 'discover', rus: 'делать открытие / обнаруживать / находить' },
	{ eng: 'search', rus: 'искать / обыскивать' },
	{ eng: 'angry', rus: 'сердитый / гневный' },
	{ eng: 'especially', rus: 'особенно / специально' },
	{ eng: 'tired', rus: 'усталый' },
	{ eng: 'level', rus: 'уровень / этаж' },
	{ eng: 'clearly', rus: 'очевидно / четко / явно' },
	{ eng: 'tone', rus: 'тон / оттенок' },
	{ eng: 'sell', rus: 'продавать' },
	{ eng: 'bottle', rus: 'бутылка / флакон' },
	{ eng: 'change', rus: 'сдача / изменение / смена' },
	{ eng: 'badly', rus: 'сильно / плохо' },
	{ eng: 'command', rus: 'команда / командование' },
	{ eng: 'whose', rus: 'чей' },
	{ eng: 'knock', rus: 'стучать / сбивать' },
	{ eng: 'silver', rus: 'серебро' },
	{ eng: 'bother', rus: 'беспокоить / надоедать' },
	{ eng: 'east', rus: 'восток' },
	{ eng: 'programme', rus: 'программа / передача' },
	{ eng: 'prepare', rus: 'подготавливать / готовить' },
	{ eng: 'ice', rus: 'лед' },
	{ eng: 'win', rus: 'выигрывать / побеждать' },
	{ eng: 'everybody', rus: 'каждый / все' },
	{ eng: 'deck', rus: 'палуба / колода' },
	{ eng: 'further', rus: 'дальнейший / дополнительный' },
	{ eng: 'storm', rus: 'буря / шторм' },
	{ eng: 'cool', rus: 'прохладный / клёвый / крутой' },
	{ eng: 'thirty', rus: 'тридцать' },
	{ eng: 'fifty', rus: 'пятьдесят' },
	{ eng: 'lost', rus: 'заблудившийся / потерянный' },
	{ eng: 'wild', rus: 'дикий / одичалый' },
	{ eng: 'loud', rus: 'громкий / шумный' },
	{ eng: 'uncle', rus: 'дядя' },
	{ eng: 'yours', rus: 'ваш / твой' },
	{ eng: 'contact', rus: 'контакт / связь' },
	{ eng: 'toy', rus: 'игрушка / забава' },
	{ eng: 'anywhere', rus: 'где угодно / куда-нибудь' },
	{ eng: 'size', rus: 'размер / формат' },
	{ eng: 'fresh', rus: 'свежий' },
	{ eng: 'sausage', rus: 'колбаса / сосиска' },
	{ eng: 'digital', rus: 'цифровой / пальцевидный' },
	{ eng: 'born', rus: 'родившийся / рожденный' },
	{ eng: 'belt', rus: 'ремень / пояс' },
	{ eng: 'race', rus: 'гонка / раса' },
	{ eng: 'railway', rus: 'железная дорога / железнодорожный путь' },
	{ eng: 'ring', rus: 'кольцо / круг' },
	{ eng: 'dream', rus: 'мечтать' },
	{ eng: 'entrance', rus: 'вход / вступление' },
	{ eng: 'luck', rus: 'удача / везение' },
	{ eng: 'possibly', rus: 'возможно / может быть' },
	{ eng: 'girlfriend', rus: 'подруга / любимая девушка' },
	{ eng: 'autumn', rus: 'осень / наступление старости' },
	{ eng: 'wet', rus: 'мокрый' },
	{ eng: 'dry', rus: 'сухой / засушливый' },
	{ eng: 'million', rus: 'миллион' },
	{ eng: 'careful', rus: 'осторожный / тщательный' },
	{ eng: 'wheel', rus: 'колесо / руль' },
	{ eng: 'sunny', rus: 'солнечный' },
	{ eng: 'perfect', rus: 'идеальный / совершенный' },
	{ eng: 'spell', rus: 'означать / произносить или писать слово по буквам' },
	{ eng: 'stomach', rus: 'желудок / живот' },
	{ eng: 'trip', rus: 'поездка / путешествие' },
	{ eng: 'lake', rus: 'озеро / лак для покраски' },
	{ eng: 'leather', rus: 'кожа / кожаное изделие' },
	{ eng: 'medicine', rus: 'медицина / лекарство' },
	{ eng: 'pilot', rus: 'пилот / летчик' },
	{ eng: 'nature', rus: 'природа / характер' },
	{ eng: 'fair', rus: 'справедливый / честный' },
	{ eng: 'castle', rus: 'замок / ладья' },
	{ eng: 'wooden', rus: 'деревянный / безжизненный' },
	{ eng: 'stair', rus: 'ступенька' },
	{ eng: 'poster', rus: 'плакат / афиша' },
	{ eng: 'bear', rus: 'медведь' },
	{ eng: 'ceiling', rus: 'потолок / перекрытие' },
	{ eng: 'metre', rus: 'метр / измерительный прибор' },
	{ eng: 'cheque', rus: 'чек' },
	{ eng: 'accident', rus: 'несчастный случай / случайное происшествие' },
	{ eng: 'defence', rus: 'оборона / защита' },
	{ eng: 'focus', rus: 'сфокусироваться / сосредоточиться' },
	{ eng: 'price', rus: 'цена / расценка' },
	{ eng: 'pool', rus: 'бассейн / пул' },
	{ eng: 'traffic', rus: 'дорожное движение' },
	{ eng: 'pack', rus: 'упаковывать' },
	{ eng: 'beginning', rus: 'начало / истоки' },
	{ eng: 'brush', rus: 'чистить щеткой' },
	{ eng: 'blanket', rus: 'одеяло / покрывало' },
	{ eng: 'baseball', rus: 'бейсбол / бейсбольный мяч' },
	{ eng: 'comfortable', rus: 'удобный / комфортный' },
	{ eng: 'opposite', rus: 'напротив / против' },
	{ eng: 'pray', rus: 'молиться / умолять' },
	{ eng: 'ourselves', rus: 'себя / себе' },
	{ eng: 'chain', rus: 'цепь / цепочка' },
	{ eng: 'elevator', rus: 'лифт / подъемник' },
	{ eng: 'forty', rus: 'сорок' },
	{ eng: 'dry', rus: 'сушить' },
	{ eng: 'aunt', rus: 'тётя' },
	{ eng: 'match', rus: 'матч / спичка / совпадение / пара, подходящая друг другу' },
	{ eng: 'alarm', rus: 'сигнал тревоги / сигнализация' },
	{ eng: 'secret', rus: 'секрет / тайна' },
	{ eng: 'describe', rus: 'описывать' },
	{ eng: 'pleasant', rus: 'приятный / милый' },
	{ eng: 'collect', rus: 'собирать' },
	{ eng: 'journey', rus: 'путешествие' },
	{ eng: 'boss', rus: 'босс / начальник' },
	{ eng: 'rock', rus: 'рок / скала / камень' },
	{ eng: 'various', rus: 'разный / различный' },
	{ eng: 'telephone', rus: 'телефон / телефонная связь' },
	{ eng: 'lamp', rus: 'лампа / фонарь' },
	{ eng: 'couch', rus: 'диван / кушетка' },
	{ eng: 'click', rus: 'щелкать / ладить' },
	{ eng: 'useful', rus: 'полезный / пригодный' },
	{ eng: 'bowl', rus: 'пиала / чаша' },
	{ eng: 'project', rus: 'проект / план' },
	{ eng: 'queen', rus: 'королева' },
	{ eng: 'department', rus: 'отдел / департамент' },
	{ eng: 'tool', rus: 'инструмент / средство' },
	{ eng: 'mix', rus: 'смешивать / перемешивать' },
	{ eng: 'partner', rus: 'партнер / компаньон' },
	{ eng: 'invitation', rus: 'приглашение / пригласительный билет' },
	{ eng: 'fourth', rus: 'четвертый' },
	{ eng: 'study', rus: 'исследование / изучение' },
	{ eng: 'dresser', rus: 'комод / костюмер' },
	{ eng: 'instrument', rus: 'инструмент / прибор' },
	{ eng: 'upset', rus: 'расстроенный / огорченный' },
	{ eng: 'record', rus: 'записывать / регистрировать' },
	{ eng: 'envelope', rus: 'конверт / оболочка' },
	{ eng: 'shelf', rus: 'полка / шельф' },
	{ eng: 'extra', rus: 'дополнительный / лишний' },
	{ eng: 'neighbour', rus: 'сосед' },
	{ eng: 'market', rus: 'рынок / базар' },
	{ eng: 'practise', rus: 'практика / тренировка' },
	{ eng: 'instruction', rus: 'инструкция / обучение' },
	{ eng: 'free', rus: 'свободно / бесплатно' },
	{ eng: 'upstairs', rus: 'наверх / наверху' },
	{ eng: 'awful', rus: 'ужасный / внушающий страх' },
	{ eng: 'complete', rus: 'завершать / выполнять / заканчивать' },
	{ eng: 'depend', rus: 'зависеть от' },
	{ eng: 'advice', rus: 'совет / консультация' },
	{ eng: 'brilliant', rus: 'блестящий / отличный' },
	{ eng: 'sweet', rus: 'сладкое / конфета' },
	{ eng: 'fashion', rus: 'мода / стиль' },
	{ eng: 'grandchild', rus: 'внук или внучка / внук' },
	{ eng: 'channel', rus: 'канал' },
	{ eng: 'magazine', rus: 'журнал / обойма' },
	{ eng: 'businessman', rus: 'бизнесмен / коммерсант' },
	{ eng: 'engineer', rus: 'инженер / машинист' },
	{ eng: 'assistant', rus: 'помощник / ассистент' },
	{ eng: 'electricity', rus: 'электричество / свет' },
	{ eng: 'desert', rus: 'пустыня / заслуга' },
	{ eng: 'swimming', rus: 'плавание' },
	{ eng: 'straight', rus: 'прямо' },
	{ eng: 'worried', rus: 'взволнованный / обеспокоенный' },
	{ eng: 'toe', rus: 'палец ноги / носок ботинка' },
	{ eng: 'highway', rus: 'автомагистраль / шоссе' },
	{ eng: 'worse', rus: 'более плохой / хуже' },
	{ eng: 'cupboard', rus: 'шкаф / буфет' },
	{ eng: 'speaker', rus: 'оратор / спикер' },
	{ eng: 'airport', rus: 'аэропорт' },
	{ eng: 'worker', rus: 'работник / рабочий' },
	{ eng: 'shame', rus: 'стыд' },
	{ eng: 'island', rus: 'остров' },
	{ eng: 'kilometre', rus: 'километр / километр пробега' },
	{ eng: 'cook', rus: 'повар / кухарка' },
	{ eng: 'polite', rus: 'вежливый / любезный' },
	{ eng: 'salad', rus: 'салат / зелень' },
	{ eng: 'drawing', rus: 'рисунок / рисование' },
	{ eng: 'pity', rus: 'жалость / сожаление' },
	{ eng: 'carpet', rus: 'ковер / напольное покрытие' },
	{ eng: 'round', rus: 'кругом / вокруг' },
	{ eng: 'teenager', rus: 'подросток / подростковый возраст' },
	{ eng: 'advanced', rus: 'продвинутый / передовой' },
	{ eng: 'break', rus: 'перерыв / нарушение' },
	{ eng: 'burger', rus: 'гамбургер / бутерброд' },
	{ eng: 'model', rus: 'модель / образец' },
	{ eng: 'sixty', rus: 'шестьдесят' },
	{ eng: 'lift', rus: 'лифт / подъем' },
	{ eng: 'unhappy', rus: 'несчастный / несчастливый' },
	{ eng: 'painting', rus: 'живопись / картина' },
	{ eng: 'capital', rus: 'столица / капитал' },
	{ eng: 'improve', rus: 'улучшать / совершенствовать' },
	{ eng: 'supper', rus: 'ужин' },
	{ eng: 'broken', rus: 'разбитый' },
	{ eng: 'mail', rus: 'почта / кольчуга' },
	{ eng: 'document', rus: 'документ' },
	{ eng: 'grandmother', rus: 'бабушка' },
	{ eng: 'national', rus: 'национальный / государственный' },
	{ eng: 'print', rus: 'печатать / распечатывать' },
	{ eng: 'adventure', rus: 'приключение / авантюра' },
	{ eng: 'cost', rus: 'стоить / обходиться' },
	{ eng: 'sofa', rus: 'диван / софа' },
	{ eng: 'manager', rus: 'менеджер / управляющий' },
	{ eng: 'tour', rus: 'тур / путешествие' },
	{ eng: 'chess', rus: 'шахматы' },
	{ eng: 'theatre', rus: 'театр / кинотеатр' },
	{ eng: 'tourist', rus: 'турист' },
	{ eng: 'borrow', rus: 'брать в долг / заимствовать' },
	{ eng: 'refer', rus: 'относиться / сослаться' },
	{ eng: 'amazing', rus: 'удивительный / изумительный' },
	{ eng: 'pound', rus: 'фунт (453,59 г) / фунт стерлингов' },
	{ eng: 'euro', rus: 'евро' },
	{ eng: 'monkey', rus: 'обезьяна' },
	{ eng: 'per', rus: 'в / за каждый' },
	{ eng: 'headache', rus: 'головная боль / помеха' },
	{ eng: 'theirs', rus: 'их' },
	{ eng: 'licence', rus: 'лицензия / удостоверение' },
	{ eng: 'battery', rus: 'батарейка / группа объектов / артиллерийская батарея' },
	{ eng: 'popular', rus: 'популярный / народный' },
	{ eng: 'cookie', rus: 'печенье / булочка' },
	{ eng: 'offer', rus: 'предложение (чего либо)' },
	{ eng: 'text', rus: 'отправлять сообщение / писать' },
	{ eng: 'coach', rus: 'тренер / автобус (туристический)' },
	{ eng: 'ID', rus: 'идентификатор / удостоверение личности' },
	{ eng: 'blonde', rus: 'белокурый' },
	{ eng: 'snake', rus: 'змея / змей' },
	{ eng: 'kick', rus: 'пинок / удар' },
	{ eng: 'wool', rus: 'шерсть / шерстяные изделия' },
	{ eng: 'delay', rus: 'отсрочивать / откладывать / задерживать' },
	{ eng: 'colleague', rus: 'коллега / сослуживец' },
	{ eng: 'variety', rus: 'разнообразие / вид' },
	{ eng: 'rent', rus: 'арендовать / брать в аренду' },
	{ eng: 'eighty', rus: 'восемьдесят' },
	{ eng: 'fan', rus: 'вентилятор / поклонник' },
	{ eng: 'average', rus: 'средний / обычный' },
	{ eng: 'mushroom', rus: 'гриб / выскочка' },
	{ eng: 'climbing', rus: 'альпинизм / восхождение' },
	{ eng: 'most', rus: 'самый / самого' },
	{ eng: 'examination', rus: 'экзамен / обследование' },
	{ eng: 'square', rus: 'квадратный / квадратичный' },
	{ eng: 'mouse', rus: 'мышь / подбитый глаз' },
	{ eng: 'make-up', rus: 'макияж / косметика' },
	{ eng: 'sweater', rus: 'свитер / эксплуататор' },
	{ eng: 'wash', rus: 'мытье / стирка' },
	{ eng: 'lazy', rus: 'ленивый / обленившийся' },
	{ eng: 'contact', rus: 'связываться / контактировать' },
	{ eng: 'shampoo', rus: 'шампунь / мытье головы' },
	{ eng: 'jewellery', rus: 'украшение / ювелирное изделия / драгоценность' },
	{ eng: 'noisy', rus: 'шумный' },
	{ eng: 'toast', rus: 'тост / гренок' },
	{ eng: 'worst', rus: 'наихудший' },
	{ eng: 'crisp', rus: 'хрустящий картофель / хрустящая корочка' },
	{ eng: 'seventh', rus: 'седьмой' },
	{ eng: 'identification', rus: 'идентификация / опознавание' },
	{ eng: 'cent', rus: 'цент' },
	{ eng: 'grade', rus: 'оценка / класс' },
	{ eng: 'kiss', rus: 'поцелуй' },
	{ eng: 'laptop', rus: 'портативный компьютер / переносной компьютер' },
	{ eng: 'spoon', rus: 'ложка / блесна' },
	{ eng: 'passport', rus: 'паспорт / паспортизация' },
	{ eng: 'armchair', rus: 'кресло' },
	{ eng: 'soap', rus: 'мыло' },
	{ eng: 'can', rus: 'жестяная банка / баллончик' },
	{ eng: 'balloon', rus: 'воздушный шар / баллон' },
	{ eng: 'scarf', rus: 'шарф' },
	{ eng: 'piano', rus: 'фортепиано / фортепьяно' },
	{ eng: 'well-known', rus: 'хорошо известный' },
	{ eng: 'purple', rus: 'фиолетовый / пурпурный' },
	{ eng: 'necklace', rus: 'ожерелье' },
	{ eng: 'half', rus: 'наполовину / вполовину' },
	{ eng: 'slice', rus: 'ломтик / кусок' },
	{ eng: 'keyboard', rus: 'клавиатура / синтезатор' },
	{ eng: 'popcorn', rus: 'попкорн / воздушная кукуруза' },
	{ eng: 'occupation', rus: 'оккупация / профессия' },
	{ eng: 'mechanic', rus: 'механик' },
	{ eng: 'cathedral', rus: 'собор / кафедральный собор' },
	{ eng: 'pop', rus: 'хлопок / газировка (лимонад)' },
	{ eng: 'granny', rus: 'бабушка' },
	{ eng: 'camp', rus: 'разбивать лагерь' },
	{ eng: 'sunglasses', rus: 'солнцезащитные очки' },
	{ eng: 'railroad', rus: 'железная дорога / железнодорожный путь' },
	{ eng: 'pepper', rus: 'перец / вспыльчивость' },
	{ eng: 'eighth', rus: 'восьмой' },
	{ eng: 'winner', rus: 'победитель / первый призер' },
	{ eng: 'opera', rus: 'опера / оперное искусство' },
	{ eng: 'pub', rus: 'пивная / паб' },
	{ eng: 'diary', rus: 'дневник / записная книжка' },
	{ eng: 'included', rus: 'включенный' },
	{ eng: 'dinosaur', rus: 'динозавр' },
	{ eng: 'lemon', rus: 'лимон / лимонный цвет' },
	{ eng: 'fried', rus: 'жареный' },
	{ eng: 'comic', rus: 'комик / комикс' },
	{ eng: 'ninth', rus: 'девятый' },
	{ eng: 'sneaker', rus: 'кроссовка / спортивная туфля / доносчик' },
	{ eng: 'receptionist', rus: 'портье / администратор' },
	{ eng: 'pasta', rus: 'макароны / макаронные изделия' },
	{ eng: 'photographer', rus: 'фотограф / фотокорреспондент' },
	{ eng: 'awesome', rus: 'устрашающий / потрясающий' },
	{ eng: 'dessert', rus: 'десерт / сладкое' },
	{ eng: 'receipt', rus: 'квитанция' },
	{ eng: 'duck', rus: 'утка' },
	{ eng: 'calendar', rus: 'календарь' },
	{ eng: 'tidy', rus: 'опрятный / аккуратный' },
	{ eng: 'mail', rus: 'посылать по почте / отправлять по почте' },
	{ eng: 'chef', rus: 'шеф-повар / главный повар' },
	{ eng: 'farm', rus: 'обрабатывать / обрабатывать землю' },
	{ eng: 'snow', rus: 'идет снег' },
	{ eng: 'grape', rus: 'виноград / виноградина' },
	{ eng: 'runner', rus: 'бегун' },
	{ eng: 'hobby', rus: 'хобби / увлечение' },
	{ eng: 'snack', rus: 'закуска / легкая закуска' },
	{ eng: 'roast', rus: 'печеный / жареный' },
	{ eng: 'jelly', rus: 'желе / студень' },
	{ eng: 'chemistry', rus: 'химия / химическая технология' },
	{ eng: 'album', rus: 'альбом / долгоиграющая пластинка' },
	{ eng: 'foggy', rus: 'туманный / неясный' },
	{ eng: 'mathematics', rus: 'математика' },
	{ eng: 'granddaughter', rus: 'внучка' },
	{ eng: 'cafeteria', rus: 'кафетерий / столовая' },
	{ eng: 'biology', rus: 'биология' },
	{ eng: 'stamp', rus: 'штамп / марка' },
	{ eng: 'cricket', rus: 'крикет / сверчок' },
	{ eng: 'kilo', rus: 'килограмм' },
	{ eng: 'cartoon', rus: 'мультфильм / карикатура' },
	{ eng: 'vocabulary', rus: 'лексика / словарь' },
	{ eng: 'graduate', rus: 'выпускник / окончивший университет' },
	{ eng: 'scissors', rus: 'ножницы' },
	{ eng: 'parking', rus: 'парковка / автостоянка' },
	{ eng: 'playground', rus: 'детская площадка / площадка для игр' },
	{ eng: 'lunchtime', rus: 'обеденное время / Обед' },
	{ eng: 'click', rus: 'щелчок' },
	{ eng: 'printer', rus: 'принтер / печатник' },
	{ eng: 'windy', rus: 'ветреный / обдуваемый ветром' },
	{ eng: 'roommate', rus: 'сосед по комнате / товарищ по комнате' },
	{ eng: 'comb', rus: 'расческа / гребень' },
	{ eng: 'minus', rus: 'без / минус' },
	{ eng: 'scooter', rus: 'мотороллер / самокат' },
	{ eng: 'gram', rus: 'грамм / мелкий горошек' },
	{ eng: 'chemist', rus: 'аптекарь / химик' },
	{ eng: 'pear', rus: 'груша / грушевое дерево' },
	{ eng: 'bookstore', rus: 'книжный магазин' },
	{ eng: 'curry', rus: 'карри / блюдо, приправленное карри' },
	{ eng: 'soccer', rus: 'футбол / соккер' },
	{ eng: 'restroom', rus: 'туалет / комната отдыха' },
	{ eng: 'cinema', rus: 'кинотеатр / кино' },
	{ eng: 'lemonade', rus: 'лимонад' },
	{ eng: 'downtown', rus: 'в деловой части города / в центре города' },
	{ eng: 'singular', rus: 'единственный в своем роде / исключительный' },
	{ eng: 'tidy', rus: 'убирать / приводить в порядок' },
	{ eng: 'tram', rus: 'трамвай / трамвайная линия' },
	{ eng: 'mosque', rus: 'мечеть' },
	{ eng: 'omelette', rus: 'омлет / яичница' },
	{ eng: 'roundabout', rus: 'карусель / кольцевая транспортная развязка' },
	{ eng: 'comparative', rus: 'сравнительная степень / компаративистика' },
	{ eng: 'volleyball', rus: 'волейбол' },
	{ eng: 'toothache', rus: 'зубная боль' },
	{ eng: 'surname', rus: 'фамилия / прозвище' },
	{ eng: 'bookshop', rus: 'книжный магазин' },
	{ eng: 'semester', rus: 'семестр / полугодие' },
	{ eng: 'petrol', rus: 'бензин / нефть' },
	{ eng: 'photography', rus: 'фотография / фотографирование' },
	{ eng: 'washing-up', rus: 'мытье посуды' },
	{ eng: 'spelling', rus: 'написание / правописание' },
	{ eng: 'guidebook', rus: 'путеводитель' },
	{ eng: 'granddad', rus: 'дедушка' },
	{ eng: 'diploma', rus: 'диплом / свидетельство' },
	{ eng: 'email', rus: 'отправлять электронную почту' },
	{ eng: 'quiz', rus: 'викторина' },
	{ eng: 'skateboard', rus: 'скейтборд / роликовая доска для катания' },
	{ eng: 'cooker', rus: 'кухонная плита' },
	{ eng: 'kilogram', rus: 'килограмм' },
	{ eng: 'beginner', rus: 'начинающий' },
	{ eng: 'pop', rus: 'популярный / эстрадный' },
	{ eng: 'noun', rus: 'существительное / имя существительное' },
	{ eng: 'weekday', rus: 'будний день / рабочий день' },
	{ eng: 'rugby', rus: 'регби' },
	{ eng: 'weekly', rus: 'еженедельно' },
	{ eng: 'disco', rus: 'дискотека' },
	{ eng: 'motorway', rus: 'автомагистраль' },
	{ eng: 'schoolchild', rus: 'школьник / школьница' },
	{ eng: 'singular', rus: 'единственное число (грамматика)' },
	{ eng: 'maths', rus: 'математика' },
	{ eng: 'grandad', rus: 'дедушка' },
	{ eng: 'stomachache', rus: 'боль в желудке / боль в животе' },
	{ eng: 'superlative', rus: 'превосходная степень / высшая точка' },
	{ eng: 'footballer', rus: 'футболист' },
	{ eng: 'salesperson', rus: 'продавец / торговый агент' },
	{ eng: 'badminton', rus: 'бадминтон / крюшон из красного вина' },
	{ eng: 'adverb', rus: 'наречие' },
	{ eng: 'headteacher', rus: 'директор школы' },
	{ eng: 'yeah', rus: 'да' },
	{ eng: 'alternative', rus: 'альтернатива / допустимый вариант' },
	{ eng: 'most', rus: 'большинство / большая часть' },
	{ eng: 'for', rus: 'по причине' },
];
