export const A2 = [
	{ eng: 'in', rus: 'внутрь / во время' },
	{ eng: 'that', rus: 'то / это / который' },
	{ eng: 'if', rus: 'если / ли' },
	{ eng: 'on', rus: 'далее' },
	{ eng: 'out', rus: 'вне / вон' },
	{ eng: 'as', rus: 'как' },
	{ eng: 'so', rus: 'так / настолько' },
	{ eng: 'by', rus: 'у / за' },
	{ eng: 'just', rus: 'просто / только что / как раз / всего лишь' },
	{ eng: 'all', rus: 'весь / полностью / совсем' },
	{ eng: 'one', rus: 'один / кто-то' },
	{ eng: 'up', rus: 'вверх по / снизу вверх' },
	{ eng: 'way', rus: 'путь / способ' },
	{ eng: 'turn', rus: 'поворачивать / сворачивать' },
	{ eng: 'through', rus: 'через / сквозь' },
	{ eng: 'even', rus: 'даже' },
	{ eng: 'over', rus: 'над / поверх' },
	{ eng: 'like', rus: 'подобно / словно' },
	{ eng: 'around', rus: 'вокруг / приблизительно' },
	{ eng: 'away', rus: 'прочь / далеко' },
	{ eng: 'still', rus: 'все еще / еще / до сих пор' },
	{ eng: 'off', rus: 'прочь' },
	{ eng: 'try', rus: 'пытаться / стараться' },
	{ eng: 'that', rus: 'что / чтобы' },
	{ eng: 'may', rus: 'можно ли / может быть' },
	{ eng: 'stand', rus: 'стоять / встать' },
	{ eng: 'keep', rus: 'хранить / держать / продолжать' },
	{ eng: 'down', rus: 'вниз по' },
	{ eng: 'let', rus: 'позволять' },
	{ eng: 'himself', rus: 'сам себя / он сам' },
	{ eng: 'ask', rus: 'спрашивать / просить / задавать вопрос' },
	{ eng: 'must', rus: 'должен' },
	{ eng: 'hold', rus: 'держать / хранить' },
	{ eng: 'move', rus: 'двигаться / перемещаться' },
	{ eng: 'should', rus: 'следовало бы / следует' },
	{ eng: 'out', rus: 'из' },
	{ eng: 'moment', rus: 'момент / мгновение' },
	{ eng: 'little', rus: 'мало / немного' },
	{ eng: 'nothing', rus: 'ничего / ничто' },
	{ eng: 'mean', rus: 'значить / означать / иметь в виду' },
	{ eng: 'against', rus: 'против / напротив / к' },
	{ eng: 'side', rus: 'сторона / бок' },
	{ eng: 'call', rus: 'называть / звать / звонить / вызвать' },
	{ eng: 'few', rus: 'несколько / немного' },
	{ eng: 'long', rus: 'долго / давно' },
	{ eng: 'enough', rus: 'достаточно' },
	{ eng: 'once', rus: 'однажды / один раз / прежде' },
	{ eng: 'bring', rus: 'приносить / привозить / приводить' },
	{ eng: 'while', rus: 'пока / в то время как' },
	{ eng: 'far', rus: 'далеко / гораздо / намного' },
	{ eng: 'fall', rus: 'падать / опускаться' },
	{ eng: 'so', rus: 'поэтому / так что' },
	{ eng: 'happen', rus: 'происходить / случаться' },
	{ eng: 'maybe', rus: 'может быть / возможно' },
	{ eng: 'after', rus: 'после / впоследствии' },
	{ eng: 'ever', rus: 'всегда / когда-либо' },
	{ eng: 'kill', rus: 'убивать / губить' },
	{ eng: 'almost', rus: 'почти / едва не' },
	{ eng: 'across', rus: 'через / поперек' },
	{ eng: 'mind', rus: 'возражать / помнить' },
	{ eng: 'pull', rus: 'тянуть / тащить' },
	{ eng: 'most', rus: 'многие / самый / наибольший' },
	{ eng: 'without', rus: 'без / вне' },
	{ eng: 'believe', rus: 'верить / считать / полагать' },
	{ eng: 'first', rus: 'впервые / сперва' },
	{ eng: 'lie', rus: 'лежать' },
	{ eng: 'follow', rus: 'следовать / сопровождать' },
	{ eng: 'sure', rus: 'уверенный' },
	{ eng: 'else', rus: 'еще' },
	{ eng: 'reach', rus: 'достигать / дотягиваться' },
	{ eng: 'right', rus: 'прямо / верно / направо' },
	{ eng: 'already', rus: 'уже' },
	{ eng: 'yet', rus: 'еще / уже' },
	{ eng: 'another', rus: 'другой / еще один' },
	{ eng: 'ship', rus: 'корабль / судно' },
	{ eng: 'such', rus: 'такой / подобный' },
	{ eng: 'shake', rus: 'трясти / качать / пожимать' },
	{ eng: 'left', rus: 'слева / налево' },
	{ eng: 'become', rus: 'становиться / превращаться' },
	{ eng: 'soon', rus: 'скоро / вскоре' },
	{ eng: 'pass', rus: 'проходить / передавать' },
	{ eng: 'air', rus: 'воздух / атмосфера' },
	{ eng: 'along', rus: 'вдоль' },
	{ eng: 'front', rus: 'передняя часть / фасад' },
	{ eng: 'return', rus: 'возвращать / возвращаться' },
	{ eng: 'dead', rus: 'мертвый' },
	{ eng: 'break', rus: 'ломать / разбивать / нарушать' },
	{ eng: 'set', rus: 'набор / комплект' },
	{ eng: 'everything', rus: 'всё' },
	{ eng: 'someone', rus: 'кто-то / некто' },
	{ eng: 'perhaps', rus: 'возможно / наверное' },
	{ eng: 'sound', rus: 'звук' },
	{ eng: 'quite', rus: 'довольно / вполне / совсем' },
	{ eng: 'herself', rus: 'себя' },
	{ eng: 'matter', rus: 'вопрос для рассмотрения / дело' },
	{ eng: 'since', rus: 'с тех пор, как / с / после' },
	{ eng: 'line', rus: 'линия / строка' },
	{ eng: 'probably', rus: 'вероятно / наверное' },
	{ eng: 'grow', rus: 'расти / выращивать / становиться' },
	{ eng: 'suppose', rus: 'полагать / предполагать' },
	{ eng: 'high', rus: 'высокий' },
	{ eng: 'lose', rus: 'терять / проигрывать' },
	{ eng: 'finger', rus: 'палец' },
	{ eng: 'over', rus: 'свыше / над' },
	{ eng: 'might', rus: 'можно / мочь' },
	{ eng: 'fire', rus: 'огонь / костер / пожар' },
	{ eng: 'idea', rus: 'идея / представление' },
	{ eng: 'case', rus: 'случай / ситуация / дело / футляр' },
	{ eng: 'laugh', rus: 'смеяться / хохотать' },
	{ eng: 'large', rus: 'большой' },
	{ eng: 'miss', rus: 'скучать / пропускать / промахиваться' },
	{ eng: 'myself', rus: 'себе / себя / сам' },
	{ eng: 'slowly', rus: 'медленно / неспешно' },
	{ eng: 'anyone', rus: 'любой / никто' },
	{ eng: 'real', rus: 'реальный / настоящий' },
	{ eng: 'guy', rus: 'парень' },
	{ eng: 'full', rus: 'полный / заполненный' },
	{ eng: 'ago', rus: 'назад / тому назад' },
	{ eng: 'office', rus: 'офис / кабинет' },
	{ eng: 'reason', rus: 'причина / повод' },
	{ eng: 'better', rus: 'лучше' },
	{ eng: 'rest', rus: 'оставшаяся часть / отдых' },
	{ eng: 'throw', rus: 'бросать / кидать' },
	{ eng: 'hundred', rus: 'сто' },
	{ eng: 'heart', rus: 'сердце / сердцевина' },
	{ eng: 'fact', rus: 'факт / данность' },
	{ eng: 'push', rus: 'толкать / нажимать' },
	{ eng: 'several', rus: 'несколько' },
	{ eng: 'decide', rus: 'решать / принимать решение' },
	{ eng: 'blood', rus: 'кровь' },
	{ eng: 'whole', rus: 'целый / весь' },
	{ eng: 'second', rus: 'секунда / мгновение' },
	{ eng: 'able', rus: 'способный / в состоянии' },
	{ eng: 'bit', rus: 'кусочек / немного / небольшое количество' },
	{ eng: 'sort', rus: 'сорт / вид / тип' },
	{ eng: 'war', rus: 'война / борьба' },
	{ eng: 'call', rus: 'вызов / телефонный звонок' },
	{ eng: 'beside', rus: 'рядом с / около' },
	{ eng: 'hope', rus: 'надеяться' },
	{ eng: 'point', rus: 'указывать' },
	{ eng: 'build', rus: 'строить / создавать' },
	{ eng: 'same', rus: 'тот же / то же самое' },
	{ eng: 'quickly', rus: 'быстро' },
	{ eng: 'deep', rus: 'глубокий / низкий' },
	{ eng: 'cut', rus: 'резать' },
	{ eng: 'finally', rus: 'окончательно / в конце концов / наконец-то' },
	{ eng: 'next', rus: 'рядом / далее / потом' },
	{ eng: 'story', rus: 'рассказ / история / сюжет' },
	{ eng: 'sound', rus: 'звучать' },
	{ eng: 'love', rus: 'любовь' },
	{ eng: 'guess', rus: 'полагать' },
	{ eng: 'hit', rus: 'ударять / поражать' },
	{ eng: 'fill', rus: 'заполнять / наполнять' },
	{ eng: 'everyone', rus: 'каждый / все' },
	{ eng: 'true', rus: 'истинный / правдивый' },
	{ eng: 'strong', rus: 'сильный / крепкий' },
	{ eng: 'continue', rus: 'продолжать / продолжаться' },
	{ eng: 'order', rus: 'приказ / заказ / порядок / ордер' },
	{ eng: 'strange', rus: 'странный / незнакомый' },
	{ eng: 'pretty', rus: 'хорошенький' },
	{ eng: 'home', rus: 'домой' },
	{ eng: 'clear', rus: 'ясный / явный / четкий' },
	{ eng: 'except', rus: 'за исключением / кроме' },
	{ eng: 'notice', rus: 'замечать / уведомлять' },
	{ eng: 'alone', rus: 'одинокий / один' },
	{ eng: 'shall', rus: 'следует' },
	{ eng: 'top', rus: 'верх / вершина' },
	{ eng: 'instead', rus: 'вместо / взамен' },
	{ eng: 'low', rus: 'низкий / невысокий' },
	{ eng: 'among', rus: 'среди / между' },
	{ eng: 'offer', rus: 'предлагать / возносить' },
	{ eng: 'wish', rus: 'желание / пожелание' },
	{ eng: 'heavy', rus: 'тяжелый / сильный' },
	{ eng: 'enter', rus: 'входить / вводить' },
	{ eng: 'hall', rus: 'прихожая / зал' },
	{ eng: 'space', rus: 'пространство / космос / промежуток' },
	{ eng: 'pain', rus: 'боль / страдание' },
	{ eng: 'arrive', rus: 'прибывать' },
	{ eng: 'sky', rus: 'небо' },
	{ eng: 'however', rus: 'однако / тем не менее' },
	{ eng: 'anyway', rus: 'в любом случае / так или иначе' },
	{ eng: 'cover', rus: 'покрывать / накрывать' },
	{ eng: 'save', rus: 'сохранять / спасать' },
	{ eng: 'kind', rus: 'добрый / любезный' },
	{ eng: 'spend', rus: 'тратить / проводить' },
	{ eng: 'corner', rus: 'угол / уголок' },
	{ eng: 'star', rus: 'звезда' },
	{ eng: 'itself', rus: 'себя / само себя' },
	{ eng: 'yourself', rus: 'ты сам / сам себя' },
	{ eng: 'figure', rus: 'рисунок / фигура' },
	{ eng: 'actually', rus: 'действительно / фактически / на самом деле' },
	{ eng: 'police', rus: 'полиция' },
	{ eng: 'themselves', rus: 'сами / сами себя' },
	{ eng: 'nearly', rus: 'почти / приблизительно' },
	{ eng: 'company', rus: 'компания / общество' },
	{ eng: 'exactly', rus: 'точно / именно / как раз' },
	{ eng: 'piece', rus: 'кусок / пьеса' },
	{ eng: 'explain', rus: 'объяснять / разъяснять' },
	{ eng: 'past', rus: 'прошлое / прошедшее время' },
	{ eng: 'use', rus: 'использование / применение' },
];
