export const B1 = [
	{ eng: 'seem', rus: 'казаться' },
	{ eng: 'towards', rus: 'к / по направлению к' },
	{ eng: 'voice', rus: 'голос' },
	{ eng: 'but', rus: 'кроме / за исключением' },
	{ eng: 'smile', rus: 'улыбаться' },
	{ eng: 'that', rus: 'так' },
	{ eng: 'though', rus: 'несмотря на то, что / хотя' },
	{ eng: 'wonder', rus: 'желать знать / интересоваться' },
	{ eng: 'shoulder', rus: 'плечо / обочина дороги' },
	{ eng: 'realise', rus: 'осознавать / понимать / реализовывать' },
	{ eng: 'pick', rus: 'выбирать / подбирать / собирать' },
	{ eng: 'others', rus: 'другие' },
	{ eng: 'step', rus: 'шагать / ступать' },
	{ eng: 'suddenly', rus: 'внезапно / вдруг' },
	{ eng: 'drop', rus: 'ронять / бросать / падать' },
	{ eng: 'glance', rus: 'взглянуть / бросить взгляд' },
	{ eng: 'stone', rus: 'камень / косточка плода' },
	{ eng: 'human', rus: 'человеческое существо / человек' },
	{ eng: 'death', rus: 'смерть' },
	{ eng: 'ground', rus: 'земля / почва / основа' },
	{ eng: 'power', rus: 'мощность / власть / сила' },
	{ eng: 'raise', rus: 'поднимать / повышать' },
	{ eng: 'appear', rus: 'появляться / казаться' },
	{ eng: 'lead', rus: 'возглавлять / вести за собой' },
	{ eng: 'chance', rus: 'шанс / возможность' },
	{ eng: 'rise', rus: 'подниматься / повышаться' },
	{ eng: 'either', rus: 'любой из двух / любой' },
	{ eng: 'point', rus: 'точка / момент / смысл' },
	{ eng: 'expect', rus: 'ожидать' },
	{ eng: 'by', rus: 'мимо' },
	{ eng: 'gun', rus: 'пистолет / пушка' },
	{ eng: 'hang', rus: 'висеть / повесить' },
	{ eng: 'sense', rus: 'чувство / ощущение / смысл / толк' },
	{ eng: 'thought', rus: 'мысль / дума' },
	{ eng: 'breath', rus: 'дыхание / вздох' },
	{ eng: 'rather', rus: 'скорее / довольно' },
	{ eng: 'step', rus: 'шаг / ступень' },
	{ eng: 'remain', rus: 'оставаться' },
	{ eng: 'lip', rus: 'губа' },
	{ eng: 'trouble', rus: 'беда / неприятность' },
	{ eng: 'talk', rus: 'разговор / беседа' },
	{ eng: 'beyond', rus: 'за пределами / вне / за' },
	{ eng: 'couple', rus: 'пара' },
	{ eng: 'lift', rus: 'поднять / приподнять' },
	{ eng: 'ahead', rus: 'впереди / вперед' },
	{ eng: 'roll', rus: 'сворачивать / катить' },
	{ eng: 'wave', rus: 'махать' },
	{ eng: 'whatever', rus: 'что бы ни / все, что' },
	{ eng: 'hide', rus: 'скрывать / прятать' },
	{ eng: 'fear', rus: 'страх / боязнь' },
	{ eng: 'officer', rus: 'офицер / чиновник' },
	{ eng: 'care', rus: 'забота / внимание' },
	{ eng: 'hope', rus: 'надежда / упование' },
	{ eng: 'edge', rus: 'край / кромка / преимущество' },
	{ eng: 'shoot', rus: 'стрелять / прострелить / расстреливать' },
	{ eng: 'silence', rus: 'тишина / молчание' },
	{ eng: 'within', rus: 'в пределах / в рамках / в' },
	{ eng: 'certain', rus: 'определенный / уверенный / некоторый' },
	{ eng: 'slip', rus: 'скользить / выскальзывать / поскальзываться' },
	{ eng: 'kid', rus: 'малыш / дитя / малышка' },
	{ eng: 'mile', rus: 'миля' },
	{ eng: 'none', rus: 'никто / ни один / ничто' },
	{ eng: 'up', rus: 'поднимающийся вверх / сведущий' },
	{ eng: 'truth', rus: 'правда / истина' },
	{ eng: 'over', rus: 'законченный / чрезмерный' },
	{ eng: 'strike', rus: 'наносить удар / ударять / поражать / поджигать' },
	{ eng: 'shadow', rus: 'тень' },
	{ eng: 'attention', rus: 'внимание / забота' },
	{ eng: 'soldier', rus: 'солдат / военный' },
	{ eng: 'system', rus: 'система' },
	{ eng: 'sight', rus: 'взгляд / зрение' },
	{ eng: 'hand', rus: 'вручать / протягивать' },
	{ eng: 'allow', rus: 'разрешать / позволять' },
	{ eng: 'manage', rus: 'справиться / суметь / управлять' },
	{ eng: 'state', rus: 'государство / состояние' },
	{ eng: 'consider', rus: 'рассматривать' },
	{ eng: 'enemy', rus: 'враг / противник' },
	{ eng: 'pause', rus: 'останавливаться / делать паузу' },
	{ eng: 'grab', rus: 'хватать / захватывать / выхватывать' },
	{ eng: 'doubt', rus: 'сомнение' },
	{ eng: 'land', rus: 'земля / суша' },
	{ eng: 'beneath', rus: 'под / ниже' },
	{ eng: 'imagine', rus: 'воображать / представлять себе' },
	{ eng: 'light', rus: 'зажигать / освещать' },
	{ eng: 'area', rus: 'область / зона / ареал' },
	{ eng: 'burn', rus: 'гореть / сжигать' },
	{ eng: 'blow', rus: 'дуть / взрывать' },
	{ eng: 'position', rus: 'положение / позиция' },
	{ eng: 'silent', rus: 'тихий / молчаливый' },
	{ eng: 'skin', rus: 'кожа / шкура' },
	{ eng: 'throat', rus: 'горло / глотка' },
	{ eng: 'whether', rus: 'или / ли' },
	{ eng: 'press', rus: 'нажимать / давить' },
	{ eng: 'knee', rus: 'колено / наколенник' },
	{ eng: 'touch', rus: 'трогать / касаться' },
	{ eng: 'thick', rus: 'толстый / густой' },
	{ eng: 'alive', rus: 'живой' },
	{ eng: 'face', rus: 'встречаться / сталкиваться' },
	{ eng: 'approach', rus: 'приближаться / подходить' },
	{ eng: 'general', rus: 'общий / главный' },
	{ eng: 'lock', rus: 'запирать / запирать на ключ' },
	{ eng: 'metal', rus: 'металл' },
	{ eng: 'battle', rus: 'битва / сражение' },
	{ eng: 'recognise', rus: 'распознавать / признавать' },
	{ eng: 'tear', rus: 'рвать / разрывать' },
	{ eng: 'although', rus: 'хотя / если бы даже' },
	{ eng: 'planet', rus: 'планета' },
	{ eng: 'creature', rus: 'создание / тварь' },
	{ eng: 'army', rus: 'армия / войско' },
	{ eng: 'wish', rus: 'желать / хотеть' },
	{ eng: 'distance', rus: 'расстояние / дистанция' },
	{ eng: 'still', rus: 'неподвижный / негазированный' },
	{ eng: 'huge', rus: 'огромный' },
	{ eng: 'ring', rus: 'звонить / звенеть' },
	{ eng: 'name', rus: 'давать имя / называть' },
	{ eng: 'prove', rus: 'доказывать / подтверждать' },
	{ eng: 'attack', rus: 'приступ / нападение / атака' },
	{ eng: 'stuff', rus: 'штуковина / вещица' },
	{ eng: 'somehow', rus: 'каким-то образом / как-нибудь' },
	{ eng: 'clear', rus: 'очищать / прояснять' },
	{ eng: 'off', rus: 'от / прочь / с' },
	{ eng: 'dozen', rus: 'дюжина / масса' },
	{ eng: 'situation', rus: 'ситуация / положение дел' },
	{ eng: 'crew', rus: 'экипаж / команда' },
	{ eng: 'main', rus: 'главный / основной' },
	{ eng: 'accept', rus: 'принимать / признавать' },
	{ eng: 'service', rus: 'обслуживание / служба' },
	{ eng: 'smoke', rus: 'дым / курение' },
	{ eng: 'security', rus: 'безопасность / охрана' },
	{ eng: 'disappear', rus: 'исчезать / скрываться' },
	{ eng: 'indeed', rus: 'на самом деле / действительно' },
	{ eng: 'destroy', rus: 'уничтожать / разрушать' },
	{ eng: 'cheek', rus: 'щека / наглость' },
	{ eng: 'unless', rus: 'если не / пока не' },
	{ eng: 'tiny', rus: 'крошечный' },
	{ eng: 'trust', rus: 'доверять / верить' },
	{ eng: 'surely', rus: 'несомненно / определенно / обязательно' },
	{ eng: 'hardly', rus: 'едва / вряд ли' },
	{ eng: 'completely', rus: 'совершенно / полностью' },
	{ eng: 'admit', rus: 'признавать / сознаваться' },
	{ eng: 'shape', rus: 'форма / фигура / силуэт' },
	{ eng: 'effort', rus: 'усилие / попытка' },
	{ eng: 'suggest', rus: 'предлагать / подсказывать' },
	{ eng: 'much', rus: 'намного / сильно' },
	{ eng: 'remove', rus: 'снимать / устранять / удалять' },
	{ eng: 'bone', rus: 'кость / костяк' },
	{ eng: 'action', rus: 'действие / акция' },
	{ eng: 'duty', rus: 'обязанность / пошлина' },
	{ eng: 'pour', rus: 'наливать / разливать' },
	{ eng: 'drag', rus: 'тянуть / затягиваться' },
	{ eng: 'besides', rus: 'кроме / помимо' },
	{ eng: 'crowd', rus: 'толпа' },
	{ eng: 'sharp', rus: 'острый / резкий' },
	{ eng: 'rush', rus: 'ринуться / бросаться / мчаться / торопить' },
	{ eng: 'protect', rus: 'защищать' },
	{ eng: 'good', rus: 'благо / добро' },
	{ eng: 'look', rus: 'взгляд / выражение / внешний вид' },
	{ eng: 'beat', rus: 'бить / биться' },
	{ eng: 'truck', rus: 'грузовик / тележка' },
	{ eng: 'mention', rus: 'упоминать' },
	{ eng: 'breathe', rus: 'дышать / вдыхать' },
	{ eng: 'ought', rus: 'следует / должен' },
	{ eng: 'rest', rus: 'отдыхать' },
	{ eng: 'tear', rus: 'слеза' },
	{ eng: 'fool', rus: 'дурак / глупец' },
	{ eng: 'refuse', rus: 'отказываться / отказывать' },
	{ eng: 'track', rus: 'путь / дорожка' },
	{ eng: 'earth', rus: 'земля / почва' },
	{ eng: 'worry', rus: 'беспокойство / волнение' },
	{ eng: 'pay', rus: 'оплата / зарплата' },
	{ eng: 'charge', rus: 'обвинение / заряд' },
	{ eng: 'warn', rus: 'предупреждать / предостерегать' },
	{ eng: 'court', rus: 'суд / корт' },
	{ eng: 'figure', rus: 'полагать' },
	{ eng: 'weight', rus: 'вес / тяжесть' },
	{ eng: 'stupid', rus: 'глупый / дурацкий' },
	{ eng: 'private', rus: 'частный / личный' },
	{ eng: 'murder', rus: 'умышленное убийство' },
	{ eng: 'remind', rus: 'напоминать' },
	{ eng: 'directly', rus: 'непосредственно / прямо' },
	{ eng: 'smell', rus: 'запах / обоняние' },
	{ eng: 'care', rus: 'заботиться' },
	{ eng: 'live', rus: 'живой / реальный' },
	{ eng: 'obviously', rus: 'явно / очевидно' },
	{ eng: 'touch', rus: 'прикосновение / след' },
	{ eng: 'loose', rus: 'свободный / рыхлый' },
	{ eng: 'shine', rus: 'сиять / светить' },
	{ eng: 'despite', rus: 'несмотря на' },
	{ eng: 'tie', rus: 'связывать / завязывать / привязывать' },
	{ eng: 'scene', rus: 'сцена / место / пейзаж' },
	{ eng: 'few', rus: 'немногие / немногочисленный' },
	{ eng: 'narrow', rus: 'узкий / ограниченный' },
	{ eng: 'leader', rus: 'лидер / руководитель' },
	{ eng: 'effect', rus: 'последствие / влияние / эффект' },
	{ eng: 'energy', rus: 'энергия' },
	{ eng: 'tongue', rus: 'язык' },
	{ eng: 'dig', rus: 'копать / выкапывать / рыть' },
	{ eng: 'camp', rus: 'лагерь / стан' },
	{ eng: 'wing', rus: 'крыло / фланг' },
	{ eng: 'speed', rus: 'скорость' },
	{ eng: 'personal', rus: 'личный / персональный' },
	{ eng: 'government', rus: 'правительство' },
	{ eng: 'avoid', rus: 'избегать' },
	{ eng: 'serious', rus: 'серьезный / нешуточный' },
	{ eng: 'record', rus: 'запись / рекорд' },
	{ eng: 'spot', rus: 'место / пятно' },
	{ eng: 'quietly', rus: 'тихо / спокойно' },
	{ eng: 'provide', rus: 'предоставлять / обеспечивать / предусматривать' },
	{ eng: 'purpose', rus: 'цель / назначение' },
	{ eng: 'require', rus: 'требовать / нуждаться' },
	{ eng: 'promise', rus: 'обещать' },
	{ eng: 'folk', rus: 'народ' },
	{ eng: 'wrap', rus: 'обертывать / завернуть' },
	{ eng: 'van', rus: 'фургон / автофургон' },
	{ eng: 'act', rus: 'акт / поступок / действие' },
	{ eng: 'act', rus: 'действовать / вести себя' },
	{ eng: 'freeze', rus: 'замораживать / застывать' },
	{ eng: 'train', rus: 'обучать / тренировать' },
	{ eng: 'necessary', rus: 'необходимый / нужный' },
	{ eng: 'operation', rus: 'операция / эксплуатация' },
	{ eng: 'calm', rus: 'спокойный / невозмутимый / безветренный' },
	{ eng: 'knowledge', rus: 'знание / знания' },
	{ eng: 'fold', rus: 'складывать / сгибать' },
	{ eng: 'handle', rus: 'ручка / рукоятка' },
	{ eng: 'forever', rus: 'вечно / навсегда' },
	{ eng: 'attack', rus: 'нападать / атаковать' },
	{ eng: 'stick', rus: 'застревать / придерживаться / приклеивать' },
	{ eng: 'experience', rus: 'опыт / переживание / впечатление' },
	{ eng: 'cabin', rus: 'кабина / хижина' },
	{ eng: 'rule', rus: 'правило / правление' },
	{ eng: 'ancient', rus: 'древний / старинный' },
	{ eng: 'familiar', rus: 'знакомый / привычный' },
	{ eng: 'iron', rus: 'железо / утюг' },
	{ eng: 'dust', rus: 'пыль / прах' },
	{ eng: 'bell', rus: 'звонок / колокол' },
	{ eng: 'decision', rus: 'решение / определение' },
	{ eng: 'event', rus: 'событие / случай / мероприятие' },
	{ eng: 'impossible', rus: 'невозможный / невыносимый' },
	{ eng: 'unit', rus: 'блок / модуль / подразделение' },
	{ eng: 'create', rus: 'создавать / творить' },
	{ eng: 'powerful', rus: 'мощный / могущественный / влиятельный' },
	{ eng: 'tunnel', rus: 'туннель / тоннель' },
	{ eng: 'pleasure', rus: 'удовольствие / радость' },
	{ eng: 'float', rus: 'плыть / плавать' },
	{ eng: 'obvious', rus: 'очевидный' },
	{ eng: 'exist', rus: 'существовать' },
	{ eng: 'smell', rus: 'пахнуть / чувствовать запах' },
	{ eng: 'asleep', rus: 'спящий / затекший' },
	{ eng: 'ghost', rus: 'призрак / привидение' },
	{ eng: 'count', rus: 'считать / рассчитывать' },
	{ eng: 'shock', rus: 'шок / потрясение' },
	{ eng: 'peace', rus: 'покой / мир' },
	{ eng: 'local', rus: 'местный / локальный' },
	{ eng: 'bet', rus: 'держать пари / спорить' },
	{ eng: 'visit', rus: 'посещение / визит' },
	{ eng: 'forehead', rus: 'лоб / передняя часть' },
	{ eng: 'form', rus: 'формировать / образовывать' },
	{ eng: 'stir', rus: 'размешивать / помешивать' },
	{ eng: 'vehicle', rus: 'транспортное средство / автомобиль' },
	{ eng: 'escape', rus: 'совершать побег / убегать' },
	{ eng: 'involve', rus: 'вовлекать / включать в себя' },
	{ eng: 'priest', rus: 'священник' },
	{ eng: 'crash', rus: 'разбивать / врезаться' },
	{ eng: 'stick', rus: 'палка' },
	{ eng: 'mostly', rus: 'в основном / главным образом / по большей части' },
	{ eng: 'feed', rus: 'кормить' },
	{ eng: 'chin', rus: 'подбородок' },
	{ eng: 'common', rus: 'общий / распространенный' },
	{ eng: 'plain', rus: 'простой (без рисунка) / незамысловатый' },
	{ eng: 'once', rus: 'как только' },
	{ eng: 'giant', rus: 'гигант / великан' },
	{ eng: 'bury', rus: 'хоронить / погребать' },
	{ eng: 'while', rus: 'некоторое время' },
	{ eng: 'inch', rus: 'дюйм (2,54 см)' },
	{ eng: 'crime', rus: 'преступление / преступность' },
	{ eng: 'button', rus: 'кнопка / пуговица' },
	{ eng: 'suffer', rus: 'страдать' },
	{ eng: 'set', rus: 'устанавливать / ставить / назначать' },
	{ eng: 'sand', rus: 'песок / гравий' },
	{ eng: 'produce', rus: 'производить / предъявлять' },
	{ eng: 'temple', rus: 'висок / храм' },
	{ eng: 'account', rus: 'счет / отчет' },
	{ eng: 'valley', rus: 'долина / ендова' },
	{ eng: 'bite', rus: 'кусать / укусить' },
	{ eng: 'pattern', rus: 'узор / шаблон / закономерность' },
	{ eng: 'murder', rus: 'убивать' },
	{ eng: 'contain', rus: 'содержать / сдерживать / содержаться' },
	{ eng: 'pretend', rus: 'притворяться / делать вид' },
	{ eng: 'marry', rus: 'жениться / выходить замуж' },
	{ eng: 'virus', rus: 'вирус / зараза' },
	{ eng: 'perfectly', rus: 'отлично / совершенно' },
	{ eng: 'lawyer', rus: 'юрист / адвокат' },
	{ eng: 'intend', rus: 'намереваться / предназначать' },
	{ eng: 'either', rus: 'либо / или' },
	{ eng: 'weak', rus: 'слабый / слабовольный' },
	{ eng: 'after', rus: 'после того как' },
	{ eng: 'smile', rus: 'улыбка' },
	{ eng: 'detective', rus: 'детектив / сыщик' },
	{ eng: 'result', rus: 'результат / следствие' },
	{ eng: 'smart', rus: 'сообразительный / умный' },
	{ eng: 'particular', rus: 'конкретный / особый' },
	{ eng: 'aim', rus: 'прицеливать / целиться' },
	{ eng: 'things', rus: 'дела / обстоятельства' },
	{ eng: 'rider', rus: 'всадник / мотоциклист' },
	{ eng: 'charge', rus: 'обвинять / заряжать' },
	{ eng: 'broad', rus: 'широкий / ясно выраженный' },
	{ eng: 'wonder', rus: 'чудо / изумление' },
	{ eng: 'natural', rus: 'природный / естественный' },
	{ eng: 'arrange', rus: 'устраивать / договариваться' },
	{ eng: 'surround', rus: 'окружать' },
	{ eng: 'object', rus: 'объект / предмет' },
	{ eng: 'flow', rus: 'течь / струиться' },
	{ eng: 'promise', rus: 'обещание / перспектива' },
	{ eng: 'curious', rus: 'любопытный / странный' },
	{ eng: 'replace', rus: 'заменять / замещать' },
	{ eng: 'feeling', rus: 'чувство / ощущение / предчувствие' },
	{ eng: 'cover', rus: 'обложка / покрывало' },
	{ eng: 'cry', rus: 'крик / плач' },
	{ eng: 'particularly', rus: 'особенно / очень' },
	{ eng: 'tent', rus: 'палатка / навес' },
	{ eng: 'cave', rus: 'пещера / полость' },
	{ eng: 'argue', rus: 'спорить / приводить доводы' },
	{ eng: 'complete', rus: 'полный / законченный' },
	{ eng: 'public', rus: 'общественный / публичный / государственный' },
	{ eng: 'equipment', rus: 'оборудование / экипировка' },
	{ eng: 'attempt', rus: 'попытка / покушение' },
	{ eng: 'length', rus: 'длина / продолжительность' },
	{ eng: 'section', rus: 'раздел / секция' },
	{ eng: 'support', rus: 'поддержка / помощь' },
	{ eng: 'branch', rus: 'ветка / ветвь / филиал' },
	{ eng: 'breast', rus: 'грудь / молочная железа' },
	{ eng: 'proper', rus: 'правильный / настоящий' },
	{ eng: 'range', rus: 'диапазон / ряд / дистанция' },
	{ eng: 'respect', rus: 'уважение / отношение / почтение' },
	{ eng: 'recover', rus: 'восстанавливаться / выздоравливать' },
	{ eng: 'nervous', rus: 'нервный / нервозный' },
	{ eng: 'leaf', rus: 'лист / створка' },
	{ eng: 'possibility', rus: 'возможность / вероятность' },
	{ eng: 'plenty', rus: 'многие / множество' },
	{ eng: 'mind', rus: 'ум / разум / мнение' },
	{ eng: 'rough', rus: 'грубый / черновой / неровный' },
	{ eng: 'row', rus: 'ряд / ссора' },
	{ eng: 'note', rus: 'замечать / отмечать' },
	{ eng: 'monster', rus: 'чудовище / монстр' },
	{ eng: 'deliver', rus: 'доставлять' },
	{ eng: 'condition', rus: 'состояние / условие' },
	{ eng: 'report', rus: 'отчитываться / докладывать / сообщать' },
	{ eng: 'relax', rus: 'расслабляться / отдыхать' },
	{ eng: 'tight', rus: 'плотный / тугой' },
	{ eng: 'judge', rus: 'судья / эксперт' },
	{ eng: 'laboratory', rus: 'лаборатория / рабочее пространство печи' },
	{ eng: 'softly', rus: 'мягко / тихо' },
	{ eng: 'heel', rus: 'каблук / пятка' },
	{ eng: 'sign', rus: 'подписывать / расписываться' },
	{ eng: 'switch', rus: 'переключаться / переключать' },
	{ eng: 'convince', rus: 'убеждать' },
	{ eng: 'port', rus: 'порт / портовый город' },
	{ eng: 'insist', rus: 'настаивать / утверждать' },
	{ eng: 'fully', rus: 'полностью / совершенно' },
	{ eng: 'universe', rus: 'вселенная / мир' },
	{ eng: 'backwards', rus: 'в обратном направлении / назад' },
	{ eng: 'connection', rus: 'соединение / связь' },
	{ eng: 'worth', rus: 'имеющий ценность / стоящий' },
	{ eng: 'first', rus: 'первое число / высшая оценка / первое место' },
	{ eng: 'bay', rus: 'бухта / отсек' },
	{ eng: 'process', rus: 'процесс / способ' },
	{ eng: 'shore', rus: 'побережье / берег' },
	{ eng: 'welcome', rus: 'желанный / приятный' },
	{ eng: 'proud', rus: 'гордый / надменный' },
	{ eng: 'advantage', rus: 'преимущество / перевес' },
	{ eng: 'opportunity', rus: 'возможность / удобный случай' },
	{ eng: 'ordinary', rus: 'обычный / обыкновенный' },
	{ eng: 'fix', rus: 'исправлять / чинить' },
	{ eng: 'concentrate', rus: 'концентрироваться / сосредоточиваться' },
	{ eng: 'trick', rus: 'трюк / уловка' },
	{ eng: 'bomb', rus: 'бомба' },
	{ eng: 'gentle', rus: 'нежный / мягкий' },
	{ eng: 'marriage', rus: 'брак / женитьба' },
	{ eng: 'skill', rus: 'навык / умение' },
	{ eng: 'nearby', rus: 'близлежащий / близкий' },
	{ eng: 'heavily', rus: 'сильно / тяжело' },
	{ eng: 'upper', rus: 'верхний / высший' },
	{ eng: 'scared', rus: 'испуганный' },
	{ eng: 'communication', rus: 'коммуникация / связь' },
	{ eng: 'dirt', rus: 'грязь / включения' },
	{ eng: 'deserve', rus: 'заслуживать' },
	{ eng: 'ability', rus: 'способность / умение / возможность' },
	{ eng: 'hunt', rus: 'охотиться / искать' },
	{ eng: 'opinion', rus: 'мнение' },
	{ eng: 'smooth', rus: 'гладкий / плавный' },
	{ eng: 'favour', rus: 'одолжение / благосклонность' },
	{ eng: 'mess', rus: 'беспорядок / передряга' },
	{ eng: 'beauty', rus: 'красота / красавица' },
	{ eng: 'ugly', rus: 'уродливый / безобразный' },
	{ eng: 'briefly', rus: 'кратко / вкратце / ненадолго' },
	{ eng: 'character', rus: 'характер / символ' },
	{ eng: 'own', rus: 'владеть' },
	{ eng: 'yet', rus: 'тем не менее / но' },
	{ eng: 'therefore', rus: 'поэтому / по этой причине' },
	{ eng: 'elbow', rus: 'локоть' },
	{ eng: 'taste', rus: 'вкус / склонность' },
	{ eng: 'unable', rus: 'неспособный' },
	{ eng: 'fault', rus: 'вина / дефект' },
	{ eng: 'stream', rus: 'поток / ручей' },
	{ eng: 'fight', rus: 'бороться / драться' },
	{ eng: 'expected', rus: 'ожидаемый / предполагаемый' },
	{ eng: 'within', rus: 'в пределах / внутри' },
	{ eng: 'absolutely', rus: 'абсолютно / совершенно' },
	{ eng: 'explode', rus: 'взрываться / взрывать' },
	{ eng: 'angel', rus: 'ангел' },
	{ eng: 'central', rus: 'центральный' },
	{ eng: 'hug', rus: 'обнимать' },
	{ eng: 'argument', rus: 'спор / аргументация' },
	{ eng: 'awake', rus: 'активный / бодрствующий' },
	{ eng: 'enormous', rus: 'огромный' },
	{ eng: 'design', rus: 'проектировать / конструировать' },
	{ eng: 'surface', rus: 'поверхность' },
	{ eng: 'due', rus: 'надлежащий / ожидаемый' },
	{ eng: 'height', rus: 'высота / рост' },
	{ eng: 'owe', rus: 'быть должником / задолжать' },
	{ eng: 'control', rus: 'управлять / контролировать' },
	{ eng: 'damage', rus: 'урон / повреждение' },
	{ eng: 'operate', rus: 'оперировать / производить операции / работать' },
	{ eng: 'reply', rus: 'отвечать' },
	{ eng: 'tip', rus: 'чаевые / кончик / совет' },
	{ eng: 'spill', rus: 'проливать / рассыпать' },
	{ eng: 'locate', rus: 'размещать / определять местонахождение' },
	{ eng: 'coast', rus: 'побережье' },
	{ eng: 'society', rus: 'общество / общественность' },
	{ eng: 'reply', rus: 'ответ / отклик' },
	{ eng: 'pure', rus: 'чистый' },
	{ eng: 'blind', rus: 'слепой / глухой' },
	{ eng: 'accompany', rus: 'сопровождать' },
	{ eng: 'succeed', rus: 'преуспевать / добиваться успеха' },
	{ eng: 'research', rus: 'исследование' },
	{ eng: 'demand', rus: 'требовать / нуждаться' },
	{ eng: 'lie', rus: 'лгать' },
	{ eng: 'professor', rus: 'профессор' },
	{ eng: 'route', rus: 'маршрут / путь' },
	{ eng: 'series', rus: 'серия / ряд' },
	{ eng: 'explanation', rus: 'объяснение / разъяснение' },
	{ eng: 'sleeve', rus: 'рукав / втулка' },
	{ eng: 'credit', rus: 'кредит / зачет' },
	{ eng: 'candle', rus: 'свеча / свечка' },
	{ eng: 'political', rus: 'политический / государственный' },
	{ eng: 'pile', rus: 'куча / груда' },
	{ eng: 'bleed', rus: 'кровоточить / истекать кровью' },
	{ eng: 'emergency', rus: 'авария / чрезвычайное положение' },
	{ eng: 'taste', rus: 'пробовать на вкус / иметь вкус' },
	{ eng: 'fairly', rus: 'довольно / справедливо' },
	{ eng: 'direct', rus: 'направлять' },
	{ eng: 'hidden', rus: 'скрытый / тайный' },
	{ eng: 'grateful', rus: 'благодарный / признательный' },
	{ eng: 'property', rus: 'собственность / имущество / свойство' },
	{ eng: 'hardware', rus: 'аппаратура / аппаратные средства' },
	{ eng: 'pot', rus: 'горшок / кастрюля' },
	{ eng: 'display', rus: 'дисплей / показ' },
	{ eng: 'dark', rus: 'темнота / тьма' },
	{ eng: 'attend', rus: 'присутствовать / посещать' },
	{ eng: 'thumb', rus: 'большой палец руки' },
	{ eng: 'access', rus: 'доступ / подход' },
	{ eng: 'since', rus: 'поскольку' },
	{ eng: 'breathing', rus: 'дыхание / придыхание' },
	{ eng: 'guilty', rus: 'виновный / виноватый' },
	{ eng: 'confirm', rus: 'подтверждать' },
	{ eng: 'previous', rus: 'предыдущий / прежний' },
	{ eng: 'issue', rus: 'вопрос / проблема' },
	{ eng: 'navy', rus: 'морское ведомство / флотилия / темно-синий цвет' },
	{ eng: 'cab', rus: 'такси / кабина' },
	{ eng: 'frame', rus: 'рамка / рама' },
	{ eng: 'lack', rus: 'нехватка / отсутствие' },
	{ eng: 'support', rus: 'поддерживать / содействовать' },
	{ eng: 'cage', rus: 'клетка / садок' },
	{ eng: 'background', rus: 'фон / задний план' },
	{ eng: 'season', rus: 'сезон / время года' },
	{ eng: 'lover', rus: 'любовник / любитель' },
	{ eng: 'period', rus: 'период / срок / промежуток времени' },
	{ eng: 'search', rus: 'поиск / досмотр / обыск' },
	{ eng: 'comment', rus: 'комментарий / высказывание' },
	{ eng: 'apply', rus: 'применять / обращаться' },
	{ eng: 'nasty', rus: 'отвратительный / противный / ужасный' },
	{ eng: 'burning', rus: 'обжигающий / жгучий / разгоряченный' },
	{ eng: 'fur', rus: 'мех / шерсть' },
	{ eng: 'inform', rus: 'информировать / сообщать' },
	{ eng: 'brief', rus: 'краткий / короткий' },
	{ eng: 'ankle', rus: 'щиколотка / лодыжка' },
	{ eng: 'used', rus: 'используемый' },
	{ eng: 'conference', rus: 'конференция / совещание' },
	{ eng: 'criminal', rus: 'преступник / уголовник' },
	{ eng: 'turn', rus: 'поворот / очередь' },
	{ eng: 'responsible', rus: 'ответственный / достойный доверия' },
	{ eng: 'anxious', rus: 'тревожный / беспокойный' },
	{ eng: 'writer', rus: 'писатель / автор' },
	{ eng: 'owner', rus: 'владелец / хозяин' },
	{ eng: 'humour', rus: 'юмор / настроение' },
	{ eng: 'occasion', rus: 'случай / повод' },
	{ eng: 'arrival', rus: 'прибытие / приезд' },
	{ eng: 'location', rus: 'расположение / положение' },
	{ eng: 'border', rus: 'граница / бордюр' },
	{ eng: 'gap', rus: 'разрыв / пробел' },
	{ eng: 'silly', rus: 'глупый / дурацкий' },
	{ eng: 'request', rus: 'запрос / просьба' },
	{ eng: 'jet', rus: 'реактивный самолет / струя / сопло' },
	{ eng: 'register', rus: 'регистрировать / отмечать' },
	{ eng: 'social', rus: 'общественный / социальный' },
	{ eng: 'rail', rus: 'рельс / перила' },
	{ eng: 'rob', rus: 'грабить' },
	{ eng: 'progress', rus: 'прогресс / успехи' },
	{ eng: 'material', rus: 'материал / вещество' },
	{ eng: 'recent', rus: 'недавний / последний' },
	{ eng: 'altogether', rus: 'совсем / в целом' },
	{ eng: 'challenge', rus: 'сложная задача / вызов' },
	{ eng: 'frightened', rus: 'испуганный / напуганный' },
	{ eng: 'corridor', rus: 'коридор / транспортный коридор' },
	{ eng: 'expert', rus: 'эксперт / специалист' },
	{ eng: 'collar', rus: 'воротник / ошейник' },
	{ eng: 'useless', rus: 'бесполезный / никуда не годный' },
	{ eng: 'silk', rus: 'шелк / шелковая нить' },
	{ eng: 'suggestion', rus: 'предложение / совет' },
	{ eng: 'fetch', rus: 'приносить' },
	{ eng: 'exhausted', rus: 'измученный' },
	{ eng: 'routine', rus: 'заведенный порядок / рутина' },
	{ eng: 'intelligent', rus: 'интеллигентный / умный' },
	{ eng: 'cable', rus: 'канат / кабель / кабельтов' },
	{ eng: 'whole', rus: 'целое / совокупность' },
	{ eng: 'reporter', rus: 'репортер / корреспондент' },
	{ eng: 'raw', rus: 'сырой / необработанный' },
	{ eng: 'link', rus: 'ссылка / связь' },
	{ eng: 'test', rus: 'проверять / испытывать' },
	{ eng: 'uncomfortable', rus: 'неудобный / неблагоустроенный' },
	{ eng: 'liquid', rus: 'жидкость / влага / плавный звук' },
	{ eng: 'near', rus: 'ближний / близкий' },
	{ eng: 'someday', rus: 'когда-нибудь / однажды / когда-то' },
	{ eng: 'sidewalk', rus: 'тротуар / пешеходная дорожка' },
	{ eng: 'match', rus: 'соответствовать / совпадать / подходить друг другу' },
	{ eng: 'safely', rus: 'безопасно / надежно' },
	{ eng: 'robot', rus: 'робот' },
	{ eng: 'clap', rus: 'хлопать / аплодировать' },
	{ eng: 'direct', rus: 'прямой / непосредственный' },
	{ eng: 'weigh', rus: 'весить / взвешивать' },
	{ eng: 'disc', rus: 'диск / круг' },
	{ eng: 'role', rus: 'роль / функция' },
	{ eng: 'successful', rus: 'успешный / удачливый' },
	{ eng: 'run', rus: 'бег / пробежка' },
	{ eng: 'contract', rus: 'контракт / договор' },
	{ eng: 'imagination', rus: 'воображение / творческая фантазия' },
	{ eng: 'agency', rus: 'агентство' },
	{ eng: 'achieve', rus: 'достигать / добиваться' },
	{ eng: 'accent', rus: 'акцент / ударение' },
	{ eng: 'jail', rus: 'тюрьма' },
	{ eng: 'rarely', rus: 'редко / нечасто' },
	{ eng: 'entry', rus: 'вход / запись / вступление' },
	{ eng: 'terribly', rus: 'ужасно / очень' },
	{ eng: 'eastern', rus: 'восточный' },
	{ eng: 'painful', rus: 'болезненный' },
	{ eng: 'expedition', rus: 'экспедиция' },
	{ eng: 'wherever', rus: 'куда / где' },
	{ eng: 'option', rus: 'выбор / вариант' },
	{ eng: 'conclusion', rus: 'умозаключение / вывод / заключение' },
	{ eng: 'miserable', rus: 'несчастный / жалкий' },
	{ eng: 'yawn', rus: 'зевать / распахивать / зиять' },
	{ eng: 'declare', rus: 'объявлять / заявлять' },
	{ eng: 'organisation', rus: 'организация' },
	{ eng: 'explore', rus: 'исследовать / выяснять' },
	{ eng: 'involved', rus: 'сложный' },
	{ eng: 'cottage', rus: 'коттедж / изба' },
	{ eng: 'approve', rus: 'утверждать / одобрять' },
	{ eng: 'benefit', rus: 'выгода / привилегия / пособие' },
	{ eng: 'firm', rus: 'фирма / торговый дом' },
	{ eng: 'underneath', rus: 'под' },
	{ eng: 'apologise', rus: 'извиняться / просить прощения' },
	{ eng: 'permit', rus: 'разрешать / позволять' },
	{ eng: 'select', rus: 'выбирать' },
	{ eng: 'surprise', rus: 'удивлять' },
	{ eng: 'description', rus: 'описание / изображение' },
	{ eng: 'selfish', rus: 'эгоистичный / эгоистический' },
	{ eng: 'flood', rus: 'затоплять / наводнять' },
	{ eng: 'shave', rus: 'брить / сбривать' },
	{ eng: 'culture', rus: 'культура / разведение' },
	{ eng: 'confident', rus: 'уверенный / самоуверенный' },
	{ eng: 'bucket', rus: 'ведро / ковш' },
	{ eng: 'cut', rus: 'порез / доля / разрез' },
	{ eng: 'population', rus: 'численность населения / популяция' },
	{ eng: 'pretty', rus: 'довольно / достаточно' },
	{ eng: 'politics', rus: 'политика / политическая деятельность' },
	{ eng: 'persuade', rus: 'убеждать / уговаривать' },
	{ eng: 'fortunately', rus: 'к счастью / по счастливой случайности' },
	{ eng: 'traveler', rus: 'путешественник / путник' },
	{ eng: 'mild', rus: 'мягкий / умеренный' },
	{ eng: 'ruin', rus: 'руины / развалины' },
	{ eng: 'ceremony', rus: 'церемония / обряд' },
	{ eng: 'complicated', rus: 'сложный / запутанный' },
	{ eng: 'low', rus: 'низко' },
	{ eng: 'religion', rus: 'религия / культ' },
	{ eng: 'spoil', rus: 'портить / портиться' },
	{ eng: 'article', rus: 'статья / предмет' },
	{ eng: 'wave', rus: 'волна / взмах' },
	{ eng: 'sunset', rus: 'заход солнца / закат' },
	{ eng: 'annoy', rus: 'раздражать / досаждать' },
	{ eng: 'pin', rus: 'прикалывать / прижимать' },
	{ eng: 'please', rus: 'радовать / угождать' },
	{ eng: 'region', rus: 'регион' },
	{ eng: 'rescue', rus: 'спасать' },
	{ eng: 'steep', rus: 'крутой / отвесный' },
	{ eng: 'patient', rus: 'пациент / больной' },
	{ eng: 'partly', rus: 'частично / отчасти' },
	{ eng: 'pill', rus: 'таблетка / пилюля' },
	{ eng: 'cheerful', rus: 'бодрый / веселый' },
	{ eng: 'unlikely', rus: 'маловероятный / невероятный' },
	{ eng: 'drop', rus: 'падение / капля' },
	{ eng: 'experiment', rus: 'эксперимент / опыт' },
	{ eng: 'retire', rus: 'уходить на пенсию / уходить в отставку' },
	{ eng: 'penny', rus: 'пенни / пенс' },
	{ eng: 'punish', rus: 'наказывать / карать' },
	{ eng: 'reader', rus: 'читатель / чтец' },
	{ eng: 'flag', rus: 'флаг' },
	{ eng: 'friendship', rus: 'дружба / дружелюбие' },
	{ eng: 'pregnant', rus: 'беременная / напряженный (момент ожидания)' },
	{ eng: 'scientific', rus: 'научный / ученый' },
	{ eng: 'employ', rus: 'использовать / предоставлять работу' },
	{ eng: 'sandy', rus: 'песчаный / песочного цвета' },
	{ eng: 'peaceful', rus: 'мирный / спокойный' },
	{ eng: 'hunger', rus: 'голод / жажда' },
	{ eng: 'kindly', rus: 'доброжелательно / любезно' },
	{ eng: 'enquiry', rus: 'запрос / вопрос' },
	{ eng: 'pavement', rus: 'тротуар / мостовая' },
	{ eng: 'calm', rus: 'успокаивать / успокоиться' },
	{ eng: 'tax', rus: 'налог / сбор' },
	{ eng: 'amazed', rus: 'пораженный' },
	{ eng: 'ashamed', rus: 'пристыженный / стыдящийся' },
	{ eng: 'cotton', rus: 'хлопок / вата' },
	{ eng: 'surprisingly', rus: 'удивительно / неожиданно' },
	{ eng: 'addition', rus: 'дополнение / сложение' },
	{ eng: 'guess', rus: 'догадка / предположение' },
	{ eng: 'fasten', rus: 'застегивать / скреплять' },
	{ eng: 'fish', rus: 'ловить рыбу / рыбачить' },
	{ eng: 'publish', rus: 'публиковать / издавать' },
	{ eng: 'defeat', rus: 'поражение / разгром' },
	{ eng: 'gallery', rus: 'галерея / галерка' },
	{ eng: 'racing', rus: 'гонка / состязание' },
	{ eng: 'continent', rus: 'континент' },
	{ eng: 'positive', rus: 'позитивный / уверенный / положительный' },
	{ eng: 'satisfied', rus: 'довольный / удовлетворенный' },
	{ eng: 'organise', rus: 'организовывать / устраивать / приводить в порядок' },
	{ eng: 'pin', rus: 'штифт / булавка' },
	{ eng: 'grant', rus: 'грант / стипендия' },
	{ eng: 'author', rus: 'автор / создатель' },
	{ eng: 'shocked', rus: 'потрясенный' },
	{ eng: 'preparation', rus: 'подготовка / препарат' },
	{ eng: 'handkerchief', rus: 'носовой платок / шейный платок' },
	{ eng: 'education', rus: 'образование' },
	{ eng: 'powder', rus: 'порошок / пудра' },
	{ eng: 'product', rus: 'продукт / продукция' },
	{ eng: 'politely', rus: 'вежливо / любезно' },
	{ eng: 'employee', rus: 'служащий / работник' },
	{ eng: 'schedule', rus: 'расписание / план' },
	{ eng: 'working', rus: 'рабочий / связанный с работой' },
	{ eng: 'poem', rus: 'стихотворение / поэма' },
	{ eng: 'reward', rus: 'награда / вознаграждение' },
	{ eng: 'fall', rus: 'падение / осень' },
	{ eng: 'jar', rus: 'банка / сосуд' },
	{ eng: 'bold', rus: 'смелый / храбрый' },
	{ eng: 'fountain', rus: 'фонтан / источник' },
	{ eng: 'charming', rus: 'обаятельный / очаровательный' },
	{ eng: 'extraordinary', rus: 'весьма необычный / чрезвычайный' },
	{ eng: 'spy', rus: 'шпион' },
	{ eng: 'attraction', rus: 'привлекательность / притяжение' },
	{ eng: 'delivery', rus: 'доставка / поставка' },
	{ eng: 'helpful', rus: 'полезный' },
	{ eng: 'technique', rus: 'техника / технический прием' },
	{ eng: 'flood', rus: 'наводнение / поток' },
	{ eng: 'keen', rus: 'острый / увлеченный' },
	{ eng: 'supposed', rus: 'мнимый / предполагаемый' },
	{ eng: 'tissue', rus: 'ткань / бумажный носовой платок' },
	{ eng: 'permanent', rus: 'постоянный' },
	{ eng: 'bald', rus: 'лысый / голый' },
	{ eng: 'mainly', rus: 'в основном / главным образом' },
	{ eng: 'shut', rus: 'закрытый' },
	{ eng: 'trash', rus: 'мусор / хлам' },
	{ eng: 'accurate', rus: 'точный' },
	{ eng: 'murderer', rus: 'убийца / душегуб' },
	{ eng: 'nephew', rus: 'племянник' },
	{ eng: 'old-fashioned', rus: 'старомодный' },
	{ eng: 'honestly', rus: 'честно / искренне' },
	{ eng: 'elderly', rus: 'пожилой' },
	{ eng: 'ladder', rus: 'трап / приставная лестница' },
	{ eng: 'hurt', rus: 'раненый / оскорбленный' },
	{ eng: 'elder', rus: 'старший' },
	{ eng: 'politician', rus: 'политик / политикан' },
	{ eng: 'bargain', rus: 'сделка / выгодная покупка' },
	{ eng: 'fine', rus: 'штраф / пеня' },
	{ eng: 'ambition', rus: 'цель / честолюбие' },
	{ eng: 'independent', rus: 'независимый / самостоятельный' },
	{ eng: 'single', rus: 'номер для одного / запись одной песни' },
	{ eng: 'frequently', rus: 'часто / зачастую' },
	{ eng: 'plenty', rus: 'изобилие / множество' },
	{ eng: 'suitable', rus: 'подходящий' },
	{ eng: 'windshield', rus: 'ветровое стекло / лобовое стекло' },
	{ eng: 'tape', rus: 'лента / пленка' },
	{ eng: 'magnificent', rus: 'великолепный / величественный' },
	{ eng: 'herb', rus: 'пряная или лекарственная трава' },
	{ eng: 'content', rus: 'содержание / содержимое' },
	{ eng: 'romantic', rus: 'романтический / романтичный' },
	{ eng: 'flu', rus: 'грипп' },
	{ eng: 'rebuild', rus: 'перестраивать / реконструировать / восстанавливать' },
	{ eng: 'candidate', rus: 'кандидат / претендент' },
	{ eng: 'bride', rus: 'невеста / новобрачная' },
	{ eng: 'cancel', rus: 'отменять / аннулировать' },
	{ eng: 'someplace', rus: 'какое-нибудь место / где-нибудь' },
	{ eng: 'guard', rus: 'стража / охрана' },
	{ eng: 'grave', rus: 'могила / смерть' },
	{ eng: 'backpack', rus: 'рюкзак' },
	{ eng: 'interval', rus: 'интервал / промежуток' },
	{ eng: 'entertain', rus: 'развлекать / принимать' },
	{ eng: 'nearby', rus: 'неподалеку / поблизости' },
	{ eng: 'barman', rus: 'бармен / буфетчик' },
	{ eng: 'pass', rus: 'проход / пропуск' },
	{ eng: 'hopeless', rus: 'безнадежный / безвыходный' },
	{ eng: 'relaxed', rus: 'расслабленный / непринужденный' },
	{ eng: 'bee', rus: 'пчела / пчелка' },
	{ eng: 'pan', rus: 'кастрюля / поддон' },
	{ eng: 'sum', rus: 'сумма / итог' },
	{ eng: 'olive', rus: 'оливка / маслина' },
	{ eng: 'antique', rus: 'антиквариат' },
	{ eng: 'dislike', rus: 'не любить / испытывать неприязнь' },
	{ eng: 'initial', rus: 'инициал / начальная буква' },
	{ eng: 'lecture', rus: 'лекция / нотация' },
	{ eng: 'translation', rus: 'перевод / трансляция' },
	{ eng: 'embassy', rus: 'посольство / посланцы' },
	{ eng: 'election', rus: 'выборы / избрание' },
	{ eng: 'middle-aged', rus: 'среднего возраста / средних лет' },
	{ eng: 'depressed', rus: 'подавленный / унылый' },
	{ eng: 'reasonably', rus: 'разумно / рассудительно' },
	{ eng: 'engineering', rus: 'инженерия / инженерная работа' },
	{ eng: 'covered', rus: 'покрытый' },
	{ eng: 'drive', rus: 'поездка / дорога' },
	{ eng: 'delighted', rus: 'довольный / радостный' },
	{ eng: 'delicious', rus: 'очень вкусный / восхитительный' },
	{ eng: 'marvellous', rus: 'изумительный / чудесный' },
	{ eng: 'jog', rus: 'бегать трусцой / подталкивать' },
	{ eng: 'sir', rus: 'сэр / сударь' },
	{ eng: 'exit', rus: 'выходить / покидать' },
	{ eng: 'profession', rus: 'профессия / исповедание' },
	{ eng: 'madam', rus: 'мадам / госпожа' },
	{ eng: 'comb', rus: 'расчесывать / прочесывать' },
	{ eng: 'cattle', rus: 'крупный рогатый скот / скотина' },
	{ eng: 'roll', rus: 'рулон / список' },
	{ eng: 'pump', rus: 'насос / помпа' },
	{ eng: 'puppy', rus: 'щенок' },
	{ eng: 'champion', rus: 'чемпион / победитель' },
	{ eng: 'convenient', rus: 'удобный / подходящий' },
	{ eng: 'sticky', rus: 'липкий / клейкий' },
	{ eng: 'secretly', rus: 'тайно' },
	{ eng: 'correctly', rus: 'правильно / корректно' },
	{ eng: 'entertainment', rus: 'развлечение' },
	{ eng: 'sunrise', rus: 'восход солнца' },
	{ eng: 'knit', rus: 'вязать' },
	{ eng: 'quantity', rus: 'количество / величина' },
	{ eng: 'secondary', rus: 'вторичный / второстепенный' },
	{ eng: 'server', rus: 'сервер / официант' },
	{ eng: 'baggage', rus: 'багаж / обоз' },
	{ eng: 'tense', rus: 'напряженный / натянутый' },
	{ eng: 'drama', rus: 'драма / драматургия' },
	{ eng: 'debate', rus: 'обсуждать / обдумывать' },
	{ eng: 'dolphin', rus: 'дельфин / макрель' },
	{ eng: 'ant', rus: 'муравей' },
	{ eng: 'pitcher', rus: 'кувшин / питчер' },
	{ eng: 'bacon', rus: 'бекон / свиная грудинка' },
	{ eng: 'southwest', rus: 'юго-запад' },
	{ eng: 'musician', rus: 'музыкант' },
	{ eng: 'jug', rus: 'кувшин / тюрьма' },
	{ eng: 'hurricane', rus: 'ураган / буря' },
	{ eng: 'reservation', rus: 'бронирование / предварительный заказ' },
	{ eng: 'maximum', rus: 'максимальный / высший' },
	{ eng: 'promote', rus: 'способствовать / содействовать' },
	{ eng: 'objective', rus: 'объективный / целевой' },
	{ eng: 'ache', rus: 'боль' },
	{ eng: 'regularly', rus: 'регулярно / часто' },
	{ eng: 'mend', rus: 'починить / поправляться' },
	{ eng: 'following', rus: 'следующий / последующий' },
	{ eng: 'pipe', rus: 'курительная трубка / труба' },
	{ eng: 'designer', rus: 'дизайнер / проектировщик' },
	{ eng: 'fare', rus: 'плата за проезд / стоимость проезда' },
	{ eng: 'present', rus: 'присутствующий / настоящий' },
	{ eng: 'festival', rus: 'фестиваль / празднество' },
	{ eng: 'ski', rus: 'лыжа' },
	{ eng: 'improvement', rus: 'улучшение' },
	{ eng: 'deaf', rus: 'глухой' },
	{ eng: 'frozen', rus: 'замерзший / мерзлый' },
	{ eng: 'frightening', rus: 'пугающий / страшный' },
	{ eng: 'colourful', rus: 'красочный' },
	{ eng: 'celebration', rus: 'празднование / торжество' },
	{ eng: 'butcher', rus: 'мясник' },
	{ eng: 'final', rus: 'финал / выпускные экзамены' },
	{ eng: 'flavour', rus: 'вкус / аромат' },
	{ eng: 'southeast', rus: 'юго-восток' },
	{ eng: 'regarding', rus: 'относительно / о' },
	{ eng: 'pleasantly', rus: 'приятно / любезно' },
	{ eng: 'visa', rus: 'виза / прописка' },
	{ eng: 'exercise', rus: 'упражняться / заниматься спортом' },
	{ eng: 'resort', rus: 'курорт / прибежище' },
	{ eng: 'spider', rus: 'паук / паукообразное' },
	{ eng: 'blog', rus: 'блог / веблог' },
	{ eng: 'strict', rus: 'строгий / точный' },
	{ eng: 'diet', rus: 'диета / диетическое питание' },
	{ eng: 'donkey', rus: 'осел' },
	{ eng: 'bomb', rus: 'бомбить' },
	{ eng: 'spectacular', rus: 'впечатляющий / захватывающий' },
	{ eng: 'admission', rus: 'признание / право войти / допуск' },
	{ eng: 'unfair', rus: 'несправедливый / нечестный' },
	{ eng: 'compete', rus: 'конкурировать / соревноваться' },
	{ eng: 'waterfall', rus: 'водопад' },
	{ eng: 'frequent', rus: 'частый / часто встречающийся' },
	{ eng: 'normal', rus: 'нормаль / нормальное состояние' },
	{ eng: 'disappointed', rus: 'разочарованный / несбывшийся' },
	{ eng: 'sail', rus: 'уходить в плавание / совершать плавание / плавать под парусами' },
	{ eng: 'total', rus: 'итог / общая сумма' },
	{ eng: 'creative', rus: 'творческий / созидательный' },
	{ eng: 'fly', rus: 'муха / полет' },
	{ eng: 'journalist', rus: 'журналист / газетчик' },
	{ eng: 'meaning', rus: 'значение / смысл' },
	{ eng: 'handwriting', rus: 'почерк / рукопись' },
	{ eng: 'dangerously', rus: 'опасно / угрожающе' },
	{ eng: 'salary', rus: 'зарплата' },
	{ eng: 'crash', rus: 'крах / авария' },
	{ eng: 'rose', rus: 'роза' },
	{ eng: 'review', rus: 'обзор / отзыв' },
	{ eng: 'annoyed', rus: 'раздраженный / недовольный' },
	{ eng: 'amazingly', rus: 'удивительно' },
	{ eng: 'palace', rus: 'дворец' },
	{ eng: 'accidentally', rus: 'случайно / нечаянно' },
	{ eng: 'wherever', rus: 'где бы ни / везде' },
	{ eng: 'wardrobe', rus: 'гардероб / шкаф' },
	{ eng: 'diagram', rus: 'диаграмма / схема' },
	{ eng: 'pedestrian', rus: 'пешеход' },
	{ eng: 'instructor', rus: 'преподаватель / инструктор' },
	{ eng: 'deposit', rus: 'депозит / задаток' },
	{ eng: 'cosy', rus: 'уютный' },
	{ eng: 'employment', rus: 'работа / использование' },
	{ eng: 'achievement', rus: 'достижение / успех' },
	{ eng: 'leisure', rus: 'досуг / свободное время' },
	{ eng: 'amusing', rus: 'забавный' },
	{ eng: 'architect', rus: 'архитектор / создатель' },
	{ eng: 'cultural', rus: 'культурный / искусственно выращиваемый' },
	{ eng: 'excitedly', rus: 'азартно / взволнованно' },
	{ eng: 'cruise', rus: 'круиз / плавание' },
	{ eng: 'buyer', rus: 'покупатель / скупщик' },
	{ eng: 'salesman', rus: 'продавец / коммивояжер' },
	{ eng: 'specially', rus: 'специально' },
	{ eng: 'messy', rus: 'грязный / беспорядочный' },
	{ eng: 'parrot', rus: 'попугай' },
	{ eng: 'brand', rus: 'совершенно новый' },
	{ eng: 'teenage', rus: 'юношеский' },
	{ eng: 'certificate', rus: 'сертификат / свидетельство' },
	{ eng: 'spice', rus: 'пряность' },
	{ eng: 'accurately', rus: 'точно / аккуратно' },
	{ eng: 'firework', rus: 'фейерверк / салют' },
	{ eng: 'postpone', rus: 'откладывать / отсрочивать' },
	{ eng: 'monthly', rus: 'ежемесячный / месячный' },
	{ eng: 'vegetarian', rus: 'вегетарианец' },
	{ eng: 'scenery', rus: 'пейзаж / вид' },
	{ eng: 'face-to-face', rus: 'лицом к лицу' },
	{ eng: 'finish', rus: 'финиш / окончание / отделка / поверхность' },
	{ eng: 'sandal', rus: 'сандал / сандалия' },
	{ eng: 'paragraph', rus: 'пункт / абзац' },
	{ eng: 'aim', rus: 'цель / прицел' },
	{ eng: 'user', rus: 'пользователь / человек' },
	{ eng: 'diving', rus: 'прыжки в воду / подводное плавание' },
	{ eng: 'shout', rus: 'крик / окрик' },
	{ eng: 'recipe', rus: 'рецепт / способ' },
	{ eng: 'salon', rus: 'салон / салон красоты' },
	{ eng: 'disabled', rus: 'имеющий ограниченные возможности / неработоспособный' },
	{ eng: 'ceremonial', rus: 'церемониальный / парадный' },
	{ eng: 'examiner', rus: 'экзаменатор / эксперт' },
	{ eng: 'unlucky', rus: 'неудачный / несчастливый' },
	{ eng: 'currency', rus: 'валюта' },
	{ eng: 'double', rus: 'вдвое / вдвойне' },
	{ eng: 'unimportant', rus: 'неважный' },
	{ eng: 'presentation', rus: 'презентация / подача' },
	{ eng: 'comedy', rus: 'комедия / комичный случай' },
	{ eng: 'supporter', rus: 'сторонник / болельщик' },
	{ eng: 'advert', rus: 'объявление / рекламное объявление' },
	{ eng: 'essay', rus: 'очерк / попытка' },
	{ eng: 'salmon', rus: 'лосось / семга' },
	{ eng: 'revise', rus: 'пересматривать / исправлять' },
	{ eng: 'extra', rus: 'дополнительно / особо' },
	{ eng: 'correction', rus: 'коррекция / исправление' },
	{ eng: 'update', rus: 'обновлять / модернизировать' },
	{ eng: 'composition', rus: 'состав / сочинение' },
	{ eng: 'grill', rus: 'жарить / допрашивать' },
	{ eng: 'shark', rus: 'акула / шулер' },
	{ eng: 'softness', rus: 'мягкость' },
	{ eng: 'cabbage', rus: 'кочанная капуста / кочан' },
	{ eng: 'refund', rus: 'компенсация / возврат (денег)' },
	{ eng: 'unfriendly', rus: 'недружелюбный / недружественный' },
	{ eng: 'barber', rus: 'мужской парикмахер' },
	{ eng: 'peanut', rus: 'арахис / орешек арахиса' },
	{ eng: 'passive', rus: 'пассивный / страдательный' },
	{ eng: 'humid', rus: 'влажный' },
	{ eng: 'yoga', rus: 'йога' },
	{ eng: 'tour', rus: 'гастролировать / совершать путешествие' },
	{ eng: 'shrimp', rus: 'креветка (маленькая)' },
	{ eng: 'lottery', rus: 'лотерея / проведение лотереи' },
	{ eng: 'fashionable', rus: 'модный / светский' },
	{ eng: 'pea', rus: 'горох / горошина' },
	{ eng: 'campsite', rus: 'туристический лагерь / кемпинг' },
	{ eng: 'blank', rus: 'пустой / незаполненный' },
	{ eng: 'microwave', rus: 'микроволновая печь / микроволны' },
	{ eng: 'hug', rus: 'объятие / крепкое объятие' },
	{ eng: 'tin', rus: 'олово / консервная банка' },
	{ eng: 'crossing', rus: 'переход / переправа' },
	{ eng: 'plenty', rus: 'достаточно / довольно' },
	{ eng: 'prescription', rus: 'рецепт (на лекарство) / рекомендация' },
	{ eng: 'untidy', rus: 'неопрятный / беспорядочный' },
	{ eng: 'divorced', rus: 'разведенный' },
	{ eng: 'webcam', rus: 'веб-камера / вебкамера' },
	{ eng: 'outdoors', rus: 'на свежем воздухе / на улице' },
	{ eng: 'ending', rus: 'окончание / заключительная часть' },
	{ eng: 'full-time', rus: 'полностью занятый / на полный рабочий день' },
	{ eng: 'competitor', rus: 'конкурент' },
	{ eng: 'alphabet', rus: 'алфавит / азбука' },
	{ eng: 'tiger', rus: 'тигр' },
	{ eng: 'historic', rus: 'исторический / исторически установленный' },
	{ eng: 'handheld', rus: 'портативный / ручной' },
	{ eng: 'anniversary', rus: 'годовщина' },
	{ eng: 'takeaway', rus: 'еда на вынос / готовая еда' },
	{ eng: 'seller', rus: 'продавец' },
	{ eng: 'challenging', rus: 'сложный / вызывающий' },
	{ eng: 'boxing', rus: 'бокс / упаковка' },
	{ eng: 'biography', rus: 'биография / жизнеописание' },
	{ eng: 'tuna', rus: 'тунец' },
	{ eng: 'romance', rus: 'роман / романтика' },
	{ eng: 'recycle', rus: 'повторно использовать / перерабатывать' },
	{ eng: 'wildlife', rus: 'живая природа / дикое животное' },
	{ eng: 'repair', rus: 'ремонт / восстановление' },
	{ eng: 'hostel', rus: 'хостел / недорогая гостиница' },
	{ eng: 'spicy', rus: 'пряный / острый' },
	{ eng: 'performer', rus: 'исполнитель / актер' },
	{ eng: 'coconut', rus: 'кокос / кокосовый орех' },
	{ eng: 'monthly', rus: 'ежемесячно' },
	{ eng: 'pollution', rus: 'загрязнение / осквернение' },
	{ eng: 'gaol', rus: 'тюрьма / тюремное заключение' },
	{ eng: 'brochure', rus: 'брошюра / проспект' },
	{ eng: 'economics', rus: 'экономика' },
	{ eng: 'documentary', rus: 'документальный фильм' },
	{ eng: 'nightclub', rus: 'ночной клуб' },
	{ eng: 'part-time', rus: 'не полностью занятый / внештатный' },
	{ eng: 'dishwasher', rus: 'посудомоечная машина / посудомойка' },
	{ eng: 'download', rus: 'скачивание / загрузка' },
	{ eng: 'lighter', rus: 'зажигалка' },
	{ eng: 'calculator', rus: 'калькулятор / вычислительный прибор' },
	{ eng: 'possessive', rus: 'притяжательный / собственнический' },
	{ eng: 'coloured', rus: 'цветной' },
	{ eng: 'thriller', rus: 'триллер / остросюжетный фильм' },
	{ eng: 'saleswoman', rus: 'продавщица' },
	{ eng: 'underline', rus: 'подчеркивать / выделить' },
	{ eng: 'iron', rus: 'гладить / утюжить' },
	{ eng: 'windsurfing', rus: 'виндсерфинг' },
	{ eng: 'fitness', rus: 'пригодность / фитнес' },
	{ eng: 'unemployed', rus: 'нетрудоустроенный / неработающий' },
	{ eng: 'babysit', rus: 'сидеть с детьми / присматривать за ребенком' },
	{ eng: 'stressed', rus: 'подверженный стрессу' },
	{ eng: 'revision', rus: 'пересмотр / переработка' },
	{ eng: 'cucumber', rus: 'огурец' },
	{ eng: 'skate', rus: 'кататься на коньках / скользить' },
	{ eng: 'squash', rus: 'тыква / сквош' },
	{ eng: 'giraffe', rus: 'жираф / жирафа' },
	{ eng: 'disappointing', rus: 'разочаровывающий / неутешительный' },
	{ eng: 'pronoun', rus: 'местоимение' },
	{ eng: 'championship', rus: 'чемпионат / звание чемпиона' },
	{ eng: 'underpants', rus: 'трусы / кальсоны' },
	{ eng: 'unwell', rus: 'нездоровый' },
	{ eng: 'pullover', rus: 'пуловер / свитер' },
	{ eng: 'unemployment', rus: 'безработица' },
	{ eng: 'hairdresser', rus: 'парикмахер / парикмахерша' },
	{ eng: 'consonant', rus: 'согласный звук / согласная буква' },
	{ eng: 'punctuation', rus: 'пунктуация / знак препинания' },
	{ eng: 'photocopy', rus: 'ксерокопия / фотокопия' },
	{ eng: 'principal', rus: 'главный / основной' },
	{ eng: 'recycling', rus: 'переработка / повторное использование' },
	{ eng: 'barbecue', rus: 'жарить / жарить на открытом огне' },
	{ eng: 'curriculum', rus: 'учебный план / программа' },
	{ eng: 'check-in', rus: 'регистрация / проверки' },
	{ eng: 'saucepan', rus: 'кастрюля' },
	{ eng: 'uncountable', rus: 'неисчислимый' },
	{ eng: 'top', rus: 'сверху' },
	{ eng: 'intermission', rus: 'антракт / перерыв' },
	{ eng: 'sunbathe', rus: 'загорать' },
	{ eng: 'guitarist', rus: 'гитарист' },
	{ eng: 'broccoli', rus: 'брокколи' },
	{ eng: 'abbreviation', rus: 'аббревиатура / сокращение' },
	{ eng: 'dustbin', rus: 'мусорный бак / свалка' },
	{ eng: 'gymnastics', rus: 'гимнастика / упражнение' },
	{ eng: 'internationally', rus: 'по всему миру / международно / на международном уровне' },
	{ eng: 'pantyhose', rus: 'колготки' },
	{ eng: 'athletics', rus: 'легкая атлетика / атлетика' },
	{ eng: 'farming', rus: 'занятие сельским хозяйством / фермерство' },
	{ eng: 'contents', rus: 'содержание / содержимое' },
	{ eng: 'broiler', rus: 'жаровня / бройлер' },
	{ eng: 'furthest', rus: 'самый дальний / наиболее далекий' },
	{ eng: 'tearing', rus: 'разрыв / разрывание' },
	{ eng: 'infinitive', rus: 'инфинитив / неопределенная форма глагола' },
	{ eng: 'modal', rus: 'модальный' },
	{ eng: 'part-time', rus: 'по совместительству / на полставки' },
	{ eng: 'recycled', rus: 'повторно используемый / переработанный' },
	{ eng: 'like', rus: 'так же, как / так, будто' },
	{ eng: 'prisoner', rus: 'заключенный / пленник' },
	{ eng: 'quality', rus: 'качественный' },
	{ eng: 'CV', rus: 'резюме' },
	{ eng: 'as', rus: 'как / когда / в то время, как' },
];
