export const B2 = [
	{ eng: 'stare', rus: 'пристально смотреть / пялиться / уставиться' },
	{ eng: 'nod', rus: 'кивать' },
	{ eng: 'though', rus: 'несмотря на это / однако' },
	{ eng: 'upon', rus: 'на / сразу после' },
	{ eng: 'lean', rus: 'наклоняться / опираться' },
	{ eng: 'head', rus: 'направляться / возглавлять' },
	{ eng: 'spread', rus: 'распространяться / разводить / раздвигать' },
	{ eng: 'weapon', rus: 'оружие / вооружение' },
	{ eng: 'control', rus: 'контроль / управление' },
	{ eng: 'force', rus: 'сила / принуждение' },
	{ eng: 'gaze', rus: 'вглядываться / смотреть пристально' },
	{ eng: 'nor', rus: 'ни' },
	{ eng: 'swing', rus: 'раскачиваться / размахивать / качать' },
	{ eng: 'master', rus: 'мастер / господин' },
	{ eng: 'slide', rus: 'скользить / сунуть' },
	{ eng: 'darkness', rus: 'темнота / тьма' },
	{ eng: 'chest', rus: 'грудь / грудная клетка / сундук' },
	{ eng: 'place', rus: 'помещать / размещать' },
	{ eng: 'settle', rus: 'улаживать / устраиваться / успокаивать / договариваться' },
	{ eng: 'simply', rus: 'просто / несложно' },
	{ eng: 'deal', rus: 'сделка / договор' },
	{ eng: 'expression', rus: 'выражение / выражение лица' },
	{ eng: 'lay', rus: 'класть' },
	{ eng: 'way', rus: 'далеко / слишком' },
	{ eng: 'even', rus: 'ровный / четный' },
	{ eng: 'gather', rus: 'собирать' },
	{ eng: 'flash', rus: 'сверкать / вспыхивать / мелькать' },
	{ eng: 'slightly', rus: 'немного / слегка' },
	{ eng: 'shot', rus: 'выстрел / удар / глоток' },
	{ eng: 'stretch', rus: 'растягивать / натягивать' },
	{ eng: 'sigh', rus: 'вздыхать / охать' },
	{ eng: 'bear', rus: 'нести / терпеть' },
	{ eng: 'bend', rus: 'гнуть / сгибать' },
	{ eng: 'aside', rus: 'в сторону / в стороне' },
	{ eng: 'strength', rus: 'сила / прочность' },
	{ eng: 'off', rus: 'выключенный / снятый' },
	{ eng: 'agent', rus: 'агент / действующее вещество' },
	{ eng: 'seek', rus: 'искать / стремиться' },
	{ eng: 'ignore', rus: 'игнорировать / пренебрегать' },
	{ eng: 'neither', rus: 'ни' },
	{ eng: 'whisper', rus: 'шептать / нашептывать' },
	{ eng: 'aware', rus: 'осведомленный / находящийся в курсе' },
	{ eng: 'assume', rus: 'предполагать / принимать' },
	{ eng: 'struggle', rus: 'бороться / стараться изо всех сил' },
	{ eng: 'down', rus: 'опущенный / спускающийся' },
	{ eng: 'entire', rus: 'целый / весь' },
	{ eng: 'lower', rus: 'опускать / понижать' },
	{ eng: 'anger', rus: 'гнев / злость' },
	{ eng: 'sweep', rus: 'обводить / проноситься' },
	{ eng: 'barely', rus: 'едва / только' },
	{ eng: 'burst', rus: 'разрываться / врываться / переполняться' },
	{ eng: 'chief', rus: 'начальник / вождь' },
	{ eng: 'spirit', rus: 'дух' },
	{ eng: 'dare', rus: 'сметь / дерзать' },
	{ eng: 'cell', rus: 'клетка / сота / камера' },
	{ eng: 'fade', rus: 'блекнуть / угасать / исчезать' },
	{ eng: 'major', rus: 'крупный / основной' },
	{ eng: 'movement', rus: 'движение / передвижение' },
	{ eng: 'survive', rus: 'выживать / переживать' },
	{ eng: 'faint', rus: 'едва заметный / слабый / неясный' },
	{ eng: 'blink', rus: 'моргать / мерцать / мигать' },
	{ eng: 'merely', rus: 'лишь / только / просто' },
	{ eng: 'fellow', rus: 'принадлежащий к той же группе / ближний' },
	{ eng: 'evidence', rus: 'свидетельство / данные' },
	{ eng: 'flame', rus: 'пламя / огонь' },
	{ eng: 'instant', rus: 'мгновенный / немедленный' },
	{ eng: 'rub', rus: 'тереть' },
	{ eng: 'gently', rus: 'осторожно / мягко / нежно' },
	{ eng: 'whom', rus: 'кого / кому' },
	{ eng: 'release', rus: 'выпускать / освобождать' },
	{ eng: 'swallow', rus: 'глотать / поглощать' },
	{ eng: 'vanish', rus: 'исчезать / пропадать' },
	{ eng: 'swear', rus: 'клясться / ругаться' },
	{ eng: 'back', rus: 'поддерживать / пятиться' },
	{ eng: 'wipe', rus: 'вытирать / протирать' },
	{ eng: 'cause', rus: 'причинять / быть причиной' },
	{ eng: 'odd', rus: 'странный / нечетный / необычный' },
	{ eng: 'base', rus: 'база / основание' },
	{ eng: 'vision', rus: 'видение / зрение' },
	{ eng: 'recall', rus: 'припоминать / вспоминать / вызывать обратно / отзывать' },
	{ eng: 'slam', rus: 'захлопывать / хлопать' },
	{ eng: 'otherwise', rus: 'иначе / в остальном / в противном случае' },
	{ eng: 'risk', rus: 'риск / угроза' },
	{ eng: 'belong', rus: 'быть своим' },
	{ eng: 'honour', rus: 'честь / почет' },
	{ eng: 'reveal', rus: 'раскрывать / разоблачать / выявлять' },
	{ eng: 'escape', rus: 'побег / бегство' },
	{ eng: 'hesitate', rus: 'колебаться / сомневаться' },
	{ eng: 'wrist', rus: 'запястье / манжета' },
	{ eng: 'examine', rus: 'рассматривать / осматривать / исследовать / изучать' },
	{ eng: 'slight', rus: 'легкий / незначительный' },
	{ eng: 'yell', rus: 'орать / кричать' },
	{ eng: 'relief', rus: 'облегчение / помощь' },
	{ eng: 'suspect', rus: 'подозревать' },
	{ eng: 'muscle', rus: 'мышца / мускул' },
	{ eng: 'servant', rus: 'слуга / прислуга / служащий' },
	{ eng: 'pound', rus: 'бить / колотить' },
	{ eng: 'distant', rus: 'далекий / дальний' },
	{ eng: 'gentleman', rus: 'джентльмен / господин' },
	{ eng: 'alien', rus: 'чужестранец / инопланетянин' },
	{ eng: 'far', rus: 'дальний / далекий' },
	{ eng: 'emerge', rus: 'появляться / возникать' },
	{ eng: 'cause', rus: 'причина / повод' },
	{ eng: 'entirely', rus: 'полностью / целиком' },
	{ eng: 'mission', rus: 'миссия / командировка' },
	{ eng: 'tap', rus: 'постукивать' },
	{ eng: 'reach', rus: 'досягаемость' },
	{ eng: 'bullet', rus: 'пуля / ядро' },
	{ eng: 'concern', rus: 'касаться / затрагивать' },
	{ eng: 'occur', rus: 'приходить в голову / происходить' },
	{ eng: 'steel', rus: 'сталь / огниво' },
	{ eng: 'military', rus: 'военный / воинский' },
	{ eng: 'regard', rus: 'относиться / рассматривать' },
	{ eng: 'shiver', rus: 'дрожать / вздрагивать' },
	{ eng: 'crack', rus: 'разбивать / трескаться / трещать' },
	{ eng: 'twisted', rus: 'извилистый / кривой' },
	{ eng: 'spot', rus: 'замечать / обнаруживать' },
	{ eng: 'crawl', rus: 'ползать / ползти' },
	{ eng: 'touched', rus: 'слегка помешанный' },
	{ eng: 'manner', rus: 'манера / способ' },
	{ eng: 'tremble', rus: 'дрожать / трепетать' },
	{ eng: 'treat', rus: 'относиться к / обращаться с / лечить' },
	{ eng: 'rope', rus: 'веревка / канат' },
	{ eng: 'wound', rus: 'ранить / поранить' },
	{ eng: 'target', rus: 'цель / мишень' },
	{ eng: 'male', rus: 'мужчина / самец' },
	{ eng: 'found', rus: 'основывать' },
	{ eng: 'tail', rus: 'хвост / конец' },
	{ eng: 'threat', rus: 'угроза / опасность' },
	{ eng: 'truly', rus: 'действительно / в самом деле' },
	{ eng: 'squeeze', rus: 'выжимать / сдавливать' },
	{ eng: 'grip', rus: 'захватывать / схватить' },
	{ eng: 'wander', rus: 'бродить / блуждать' },
	{ eng: 'jaw', rus: 'челюсть / зажим' },
	{ eng: 'silently', rus: 'молча / потихоньку' },
	{ eng: 'pressure', rus: 'давление / воздействие' },
	{ eng: 'extend', rus: 'продлевать / вытягивать' },
	{ eng: 'trail', rus: 'тропа / след' },
	{ eng: 'indicate', rus: 'указывать / показывать' },
	{ eng: 'eventually', rus: 'в конце концов / в итоге' },
	{ eng: 'fear', rus: 'бояться / страшиться' },
	{ eng: 'rear', rus: 'задний' },
	{ eng: 'supply', rus: 'припасы / запас' },
	{ eng: 'wound', rus: 'рана / ранение' },
	{ eng: 'load', rus: 'загружать / заряжать' },
	{ eng: 'slave', rus: 'раб' },
	{ eng: 'mass', rus: 'масса / месса' },
	{ eng: 'dawn', rus: 'рассвет / заря' },
	{ eng: 'cast', rus: 'актерский состав / гипс' },
	{ eng: 'female', rus: 'женщина / самка' },
	{ eng: 'bare', rus: 'голый / пустой' },
	{ eng: 'response', rus: 'ответ / отклик' },
	{ eng: 'task', rus: 'задание / задача' },
	{ eng: 'companion', rus: 'компаньон / спутник' },
	{ eng: 'eyebrow', rus: 'бровь' },
	{ eng: 'need', rus: 'необходимость / нужда' },
	{ eng: 'respond', rus: 'реагировать' },
	{ eng: 'kneel', rus: 'опускаться на колени / становиться на колени' },
	{ eng: 'pack', rus: 'пакет / пачка' },
	{ eng: 'council', rus: 'консилиум / совет / совещание' },
	{ eng: 'data', rus: 'данные / факты' },
	{ eng: 'source', rus: 'источник / первоисточник / исток' },
	{ eng: 'lead', rus: 'лидерство / поводок' },
	{ eng: 'pace', rus: 'темп / скорость' },
	{ eng: 'evil', rus: 'злой / дурной' },
	{ eng: 'threaten', rus: 'угрожать / запугивать' },
	{ eng: 'intelligence', rus: 'интеллект / разведка' },
	{ eng: 'authority', rus: 'власть / авторитет / полномочие' },
	{ eng: 'glance', rus: 'быстрый взгляд / взгляд' },
	{ eng: 'hood', rus: 'капюшон / капот' },
	{ eng: 'physical', rus: 'физический / материальный' },
	{ eng: 'rip', rus: 'рвать / распиливать вдоль волокон' },
	{ eng: 'reaction', rus: 'реакция / противодействие' },
	{ eng: 'instantly', rus: 'немедленно / тотчас' },
	{ eng: 'devil', rus: 'черт / дьявол' },
	{ eng: 'tale', rus: 'рассказ / сказка' },
	{ eng: 'slap', rus: 'хлопать / шлепать' },
	{ eng: 'bound', rus: 'обязанный / связанный' },
	{ eng: 'visible', rus: 'видимый / зримый' },
	{ eng: 'safety', rus: 'безопасность' },
	{ eng: 'loss', rus: 'потеря / убыток' },
	{ eng: 'witness', rus: 'свидетель / заверитель' },
	{ eng: 'emotion', rus: 'эмоция / чувство' },
	{ eng: 'terror', rus: 'ужас / террор' },
	{ eng: 'victim', rus: 'жертва / потерпевший' },
	{ eng: 'arrow', rus: 'стрелка / стрела' },
	{ eng: 'tough', rus: 'трудный / жесткий' },
	{ eng: 'steady', rus: 'устойчивый / стабильный' },
	{ eng: 'bloody', rus: 'кровавый / окровавленный' },
	{ eng: 'fighting', rus: 'бой / схватка' },
	{ eng: 'paw', rus: 'лапа / ручища' },
	{ eng: 'signal', rus: 'сигнал / знак' },
	{ eng: 'thus', rus: 'таким образом / так' },
	{ eng: 'horror', rus: 'ужас / отвращение' },
	{ eng: 'wise', rus: 'мудрый / разумный' },
	{ eng: 'smash', rus: 'разбивать вдребезги / разгромить' },
	{ eng: 'feature', rus: 'особенность / черты лица' },
	{ eng: 'inner', rus: 'внутренний / сокровенный' },
	{ eng: 'seize', rus: 'хватать / охватывать' },
	{ eng: 'mark', rus: 'отмечать / помечать' },
	{ eng: 'question', rus: 'задавать вопрос / подвергать сомнению' },
	{ eng: 'desire', rus: 'желание / вожделение' },
	{ eng: 'deeply', rus: 'глубоко / серьезно' },
	{ eng: 'mask', rus: 'маска / противогаз' },
	{ eng: 'passage', rus: 'проход / прохождение' },
	{ eng: 'claim', rus: 'заявлять / утверждать / претендовать' },
	{ eng: 'beam', rus: 'луч / балка' },
	{ eng: 'sunlight', rus: 'солнечный свет / солнечные лучи' },
	{ eng: 'great', rus: 'здорово / замечательно' },
	{ eng: 'whoever', rus: 'кто бы ни / тот, кто' },
	{ eng: 'scratch', rus: 'царапать / чесать' },
	{ eng: 'pop', rus: 'совать (помещать) / хлопать' },
	{ eng: 'disturb', rus: 'беспокоить / тревожить' },
	{ eng: 'shell', rus: 'оболочка / раковина' },
	{ eng: 'harm', rus: 'вред / ущерб' },
	{ eng: 'mist', rus: 'туман / пасмурность' },
	{ eng: 'collapse', rus: 'рухнуть / рушиться / разваливаться' },
	{ eng: 'reflect', rus: 'отражать / размышлять' },
	{ eng: 'vast', rus: 'огромный / обширный' },
	{ eng: 'sake', rus: 'благо / польза' },
	{ eng: 'worth', rus: 'ценность / значимость' },
	{ eng: 'rage', rus: 'ярость / гнев' },
	{ eng: 'appreciate', rus: 'оценивать по достоинству / быть признательным' },
	{ eng: 'standard', rus: 'стандарт / мерка' },
	{ eng: 'sweat', rus: 'потеть / запотевать' },
	{ eng: 'descend', rus: 'спускаться' },
	{ eng: 'armed', rus: 'вооруженный' },
	{ eng: 'deny', rus: 'отрицать / отказывать' },
	{ eng: 'frighten', rus: 'пугать / страшить' },
	{ eng: 'closely', rus: 'близко / внимательно' },
	{ eng: 'capture', rus: 'захватывать / запечатлевать' },
	{ eng: 'observe', rus: 'наблюдать / соблюдать' },
	{ eng: 'identify', rus: 'идентифицировать / опознавать' },
	{ eng: 'trust', rus: 'доверие' },
	{ eng: 'assure', rus: 'заверить / уверять' },
	{ eng: 'massive', rus: 'массивный / огромный' },
	{ eng: 'medical', rus: 'медицинский' },
	{ eng: 'device', rus: 'устройство / приспособление' },
	{ eng: 'reality', rus: 'реальность / действительность' },
	{ eng: 'trace', rus: 'след / отпечаток' },
	{ eng: 'circumstance', rus: 'обстоятельство / обстановка' },
	{ eng: 'cloth', rus: 'ткань' },
	{ eng: 'block', rus: 'блокировать / преграждать' },
	{ eng: 'mutter', rus: 'бормотать' },
	{ eng: 'wire', rus: 'провод / проволока' },
	{ eng: 'punch', rus: 'пробивать / нажимать (кнопку и т.п.)' },
	{ eng: 'gear', rus: 'снаряжение / передача' },
	{ eng: 'handle', rus: 'справляться с / управляться' },
	{ eng: 'structure', rus: 'строение / структура' },
	{ eng: 'nerve', rus: 'нерв / нервы' },
	{ eng: 'client', rus: 'клиент' },
	{ eng: 'balance', rus: 'равновесие / баланс / остаток на счете' },
	{ eng: 'beg', rus: 'умолять / просить' },
	{ eng: 'strain', rus: 'напрягать / стремиться / стараться' },
	{ eng: 'maintain', rus: 'поддерживать / сохранять' },
	{ eng: 'pride', rus: 'гордость / прайд' },
	{ eng: 'rapidly', rus: 'быстро / стремительно' },
	{ eng: 'heal', rus: 'исцелять / излечивать' },
	{ eng: 'code', rus: 'код / кодекс' },
	{ eng: 'statement', rus: 'заявление / констатация' },
	{ eng: 'joy', rus: 'радость / утеха' },
	{ eng: 'attempt', rus: 'пытаться / покушаться' },
	{ eng: 'trouble', rus: 'тревожить / беспокоить' },
	{ eng: 'bush', rus: 'куст / кустарник' },
	{ eng: 'mere', rus: 'простой / всего лишь' },
	{ eng: 'slope', rus: 'склон / наклон' },
	{ eng: 'separate', rus: 'отделять / отсоединять / разделять' },
	{ eng: 'wind', rus: 'наматывать / изгибаться / виться' },
	{ eng: 'bark', rus: 'лаять / рявкать' },
	{ eng: 'mud', rus: 'грязь / грязи' },
	{ eng: 'concern', rus: 'беспокойство / забота' },
	{ eng: 'hip', rus: 'бедро / вальма' },
	{ eng: 'theory', rus: 'теория / необоснованное предположение' },
	{ eng: 'tightly', rus: 'плотно / крепко / тесно' },
	{
		eng: 'gain',
		rus: 'получать / обретать / выгадывать / добиваться / набираться / набирать / снискать',
	},
	{ eng: 'mental', rus: 'умственный / психический' },
	{ eng: 'individual', rus: 'личность / человек' },
	{ eng: 'trial', rus: 'судебное разбирательство / испытание' },
	{ eng: 'commit', rus: 'совершать / поручать' },
	{ eng: 'stroke', rus: 'гладить' },
	{ eng: 'waist', rus: 'талия / пояс' },
	{ eng: 'limit', rus: 'ограничивать / лимитировать' },
	{ eng: 'abandon', rus: 'покидать / оставлять / отказываться от' },
	{ eng: 'justice', rus: 'справедливость / правосудие' },
	{ eng: 'chase', rus: 'гнаться' },
	{ eng: 'grant', rus: 'предоставлять / выдавать' },
	{ eng: 'impression', rus: 'впечатление / оттиск' },
	{ eng: 'tend', rus: 'иметь склонность / ухаживать' },
	{ eng: 'blame', rus: 'вина / порицание' },
	{ eng: 'chew', rus: 'жевать' },
	{ eng: 'tight', rus: 'крепко / плотно' },
	{ eng: 'panic', rus: 'паника' },
	{ eng: 'claim', rus: 'претензия / иск' },
	{ eng: 'invisible', rus: 'невидимый / незримый' },
	{ eng: 'desert', rus: 'покидать' },
	{ eng: 'faith', rus: 'вера / доверие' },
	{ eng: 'grip', rus: 'хватка / захват' },
	{ eng: 'innocent', rus: 'невиновный / невинный' },
	{ eng: 'beat', rus: 'ритм / удар' },
	{ eng: 'fate', rus: 'судьба / участь' },
	{ eng: 'resist', rus: 'сопротивляться / противостоять' },
	{ eng: 'suspicion', rus: 'подозрение / подозрительность' },
	{ eng: 'apart', rus: 'отделенный / разлученный' },
	{ eng: 'naturally', rus: 'естественно / разумеется' },
	{ eng: 'occupy', rus: 'занимать / оккупировать' },
	{ eng: 'outer', rus: 'внешний / наружный' },
	{ eng: 'liberty', rus: 'свобода' },
	{ eng: 'counter', rus: 'прилавок / стойка / счетчик' },
	{ eng: 'evidently', rus: 'очевидно / явно' },
	{ eng: 'clothing', rus: 'одежда / платье' },
	{ eng: 'doubt', rus: 'сомневаться' },
	{ eng: 'freedom', rus: 'свобода' },
	{ eng: 'inside', rus: 'внутренняя сторона / обочина' },
	{ eng: 'united', rus: 'объединенный / единый' },
	{ eng: 'tighten', rus: 'сжимать / затянуть' },
	{ eng: 'desperate', rus: 'отчаянный / полный отчаяния' },
	{ eng: 'suspect', rus: 'подозреваемый' },
	{ eng: 'lap', rus: 'колени / круг трека' },
	{ eng: 'chaos', rus: 'хаос' },
	{ eng: 'betray', rus: 'предавать / выдавать' },
	{ eng: 'naked', rus: 'голый / неприкрытый' },
	{ eng: 'determined', rus: 'решительный / полный решимости' },
	{ eng: 'warmth', rus: 'тепло / теплота' },
	{ eng: 'lane', rus: 'переулок / полоса движения' },
	{ eng: 'fence', rus: 'забор / ограда' },
	{ eng: 'speed', rus: 'ускорять / мчать' },
	{ eng: 'expose', rus: 'разоблачать / подвергать (действию)' },
	{ eng: 'impress', rus: 'впечатлять / производить впечатление' },
	{ eng: 'adjust', rus: 'приспосабливаться / поправлять / подгонять' },
	{ eng: 'stuck', rus: 'застрявший' },
	{ eng: 'obey', rus: 'повиноваться / слушаться' },
	{ eng: 'inspector', rus: 'инспектор' },
	{ eng: 'rate', rus: 'ставка / темп' },
	{ eng: 'eager', rus: 'чувствующий сильное желание / нетерпеливый' },
	{ eng: 'damp', rus: 'влажный / сырой' },
	{ eng: 'unlike', rus: 'в отличие от' },
	{ eng: 'rid', rus: 'избавлять / избавляться' },
	{ eng: 'victory', rus: 'победа' },
	{ eng: 'current', rus: 'текущий / современный' },
	{ eng: 'launch', rus: 'запускать / выпускать' },
	{ eng: 'investigation', rus: 'расследование / исследование' },
	{ eng: 'anyhow', rus: 'во всяком случае / все равно' },
	{ eng: 'melt', rus: 'таять / плавиться / растапливать' },
	{ eng: 'senior', rus: 'старший / вышестоящий' },
	{ eng: 'ache', rus: 'болеть / ныть' },
	{ eng: 'citizen', rus: 'гражданин / житель' },
	{ eng: 'whistle', rus: 'свистеть' },
	{ eng: 'agreement', rus: 'соглашение / договоренность' },
	{ eng: 'laser', rus: 'лазер / лазерная установка' },
	{ eng: 'sweat', rus: 'пот / потение' },
	{ eng: 'capable', rus: 'способный' },
	{ eng: 'courage', rus: 'смелость / мужество / храбрость' },
	{ eng: 'confidence', rus: 'уверенность / доверие' },
	{ eng: 'tray', rus: 'лоток / поднос' },
	{ eng: 'establish', rus: 'основывать / устанавливать' },
	{ eng: 'column', rus: 'столбец / колонна' },
	{ eng: 'hint', rus: 'намек / совет' },
	{ eng: 'mean', rus: 'скупой / злобный' },
	{ eng: 'foolish', rus: 'глупый / дурацкий' },
	{ eng: 'cease', rus: 'прекращать / переставать' },
	{ eng: 'affect', rus: 'влиять / затрагивать' },
	{ eng: 'responsibility', rus: 'ответственность / обязанность' },
	{ eng: 'professional', rus: 'профессионал / спортсмен-профессионал' },
	{ eng: 'tension', rus: 'натяжение / нервное напряжение' },
	{ eng: 'scent', rus: 'запах / след' },
	{ eng: 'nation', rus: 'нация / страна' },
	{ eng: 'react', rus: 'реагировать / воздействовать' },
	{ eng: 'sob', rus: 'рыдать / всхлипывать' },
	{ eng: 'bang', rus: 'хлопать / удариться' },
	{ eng: 'feel', rus: 'ощущение / атмосфера' },
	{ eng: 'splash', rus: 'брызгать / плескаться' },
	{ eng: 'young', rus: 'молодежь / детеныши' },
	{ eng: 'since', rus: 'с / поскольку' },
	{ eng: 'estate', rus: 'имущество / недвижимость' },
	{ eng: 'steer', rus: 'рулить / направлять / управлять' },
	{ eng: 'protection', rus: 'защита / покровительство' },
	{ eng: 'confusion', rus: 'замешательство / путаница' },
	{ eng: 'curiosity', rus: 'любопытство / редкость' },
	{ eng: 'represent', rus: 'представлять / олицетворять / изображать' },
	{ eng: 'aircraft', rus: 'самолет / авиация' },
	{ eng: 'weird', rus: 'странный' },
	{ eng: 'thigh', rus: 'бедро / поверхность бедра' },
	{ eng: 'satisfy', rus: 'удовлетворять / устраивать' },
	{ eng: 'sharply', rus: 'резко' },
	{ eng: 'successfully', rus: 'успешно' },
	{ eng: 'fortune', rus: 'состояние / фортуна' },
	{ eng: 'proof', rus: 'доказательство / проверка' },
	{ eng: 'impact', rus: 'влияние / воздействие' },
	{ eng: 'relieved', rus: 'чувствующий облегчение' },
	{ eng: 'string', rus: 'нитка / струна' },
	{ eng: 'craft', rus: 'ремесло / судно' },
	{ eng: 'existence', rus: 'существование / наличие' },
	{ eng: 'present', rus: 'предоставлять / преподносить' },
	{ eng: 'unconscious', rus: 'находящийся без сознания / потерявший сознание' },
	{ eng: 'evolution', rus: 'эволюция / развитие' },
	{ eng: 'pile', rus: 'складывать / накапливать' },
	{ eng: 'intention', rus: 'намерение / цель' },
	{ eng: 'torch', rus: 'факел / карманный фонарь' },
	{ eng: 'species', rus: 'биологический вид / разновидность' },
	{ eng: 'deadly', rus: 'смертельный / смертоносный / смертный' },
	{ eng: 'cart', rus: 'телега / тележка' },
	{ eng: 'widen', rus: 'расширять / увеличиваться' },
	{ eng: 'firmly', rus: 'прочно / твердо' },
	{ eng: 'aggressive', rus: 'агрессивный / напористый' },
	{ eng: 'puzzled', rus: 'озадаченный / недоуменный' },
	{ eng: 'clue', rus: 'подсказка / ключ к разгадке / улика' },
	{ eng: 'dash', rus: 'бросаться / мчаться' },
	{ eng: 'analysis', rus: 'анализ' },
	{ eng: 'complex', rus: 'сложный / комплексный' },
	{ eng: 'rumour', rus: 'слух / молва' },
	{ eng: 'strike', rus: 'забастовка / удар' },
	{ eng: 'clerk', rus: 'клерк / служащий' },
	{ eng: 'oak', rus: 'дуб' },
	{ eng: 'motor', rus: 'двигатель / мотор' },
	{ eng: 'mention', rus: 'упоминание / ссылка' },
	{ eng: 'official', rus: 'официальный / должностной' },
	{ eng: 'occasionally', rus: 'иногда / время от времени' },
	{ eng: 'precious', rus: 'драгоценный / дорогой' },
	{ eng: 'round', rus: 'раунд / ряд' },
	{ eng: 'suspicious', rus: 'подозрительный / сомнительный' },
	{ eng: 'stock', rus: 'акции / запас' },
	{ eng: 'legal', rus: 'правовой / юридический' },
	{ eng: 'concrete', rus: 'бетон' },
	{ eng: 'lack', rus: 'испытывать недостаток / недоставать' },
	{ eng: 'interior', rus: 'внутреннее пространство / интерьер' },
	{ eng: 'regret', rus: 'сожаление / раскаяние' },
	{ eng: 'stiff', rus: 'жесткий / резкий' },
	{ eng: 'unusually', rus: 'необычно / необыкновенно' },
	{ eng: 'equally', rus: 'столь же / одинаково / в равной степени' },
	{ eng: 'nevertheless', rus: 'тем не менее / однако' },
	{ eng: 'root', rus: 'корень' },
	{ eng: 'try', rus: 'попытка / проба' },
	{ eng: 'desperately', rus: 'отчаянно / в отчаянии' },
	{ eng: 'host', rus: 'хозяин / ведущий' },
	{ eng: 'lid', rus: 'крышка' },
	{ eng: 'wildly', rus: 'дико / бурно' },
	{ eng: 'furious', rus: 'разъяренный / взбешенный' },
	{ eng: 'sensation', rus: 'ощущение / сенсация' },
	{ eng: 'apparently', rus: 'по-видимому / судя по всему' },
	{ eng: 'dip', rus: 'окунать / опускать / макать' },
	{ eng: 'reckon', rus: 'считать / думать' },
	{ eng: 'satisfaction', rus: 'удовлетворение / сатисфакция' },
	{ eng: 'sack', rus: 'мешок / куль' },
	{ eng: 'unlock', rus: 'отпирать / разблокировать / открывать' },
	{ eng: 'minor', rus: 'незначительный / несовершеннолетний / мелкий' },
	{ eng: 'bump', rus: 'врезаться / ударять' },
	{ eng: 'cheer', rus: 'подбадривать / ободрять' },
	{ eng: 'shock', rus: 'шокировать / потрясать' },
	{ eng: 'purchase', rus: 'приобретать / покупать' },
	{ eng: 'solid', rus: 'твердый / сплошной / солидный' },
	{ eng: 'suicide', rus: 'самоубийство / самоубийца' },
	{ eng: 'tide', rus: 'волна / прилив' },
	{ eng: 'decade', rus: 'десятилетие / десяток' },
	{ eng: 'guilt', rus: 'вина / чувство вины' },
	{ eng: 'hook', rus: 'зацеплять / подсовывать' },
	{ eng: 'destruction', rus: 'разрушение / уничтожение' },
	{ eng: 'upright', rus: 'вертикальный / порядочный' },
	{ eng: 'haunt', rus: 'преследовать / часто посещать' },
	{ eng: 'resource', rus: 'ресурс / ресурсы' },
	{ eng: 'lobby', rus: 'вестибюль / холл' },
	{ eng: 'delicate', rus: 'тонкий / хрупкий' },
	{ eng: 'outside', rus: 'внешняя сторона' },
	{ eng: 'high', rus: 'максимум / высшая точка' },
	{ eng: 'amusement', rus: 'развлечение / веселье' },
	{ eng: 'ward', rus: 'больничная палата / подопечный' },
	{ eng: 'protest', rus: 'протест' },
	{ eng: 'version', rus: 'версия / вариант' },
	{ eng: 'endure', rus: 'терпеть / выдерживать' },
	{ eng: 'package', rus: 'пакет / упаковка' },
	{ eng: 'dumb', rus: 'глупый / немой' },
	{ eng: 'temper', rus: 'характер / вспыльчивость' },
	{ eng: 'gradually', rus: 'постепенно' },
	{ eng: 'steam', rus: 'пар / испарение' },
	{ eng: 'violent', rus: 'насильственный / сильный' },
	{ eng: 'mistake', rus: 'ошибаться / понимать неправильно' },
	{ eng: 'deliberately', rus: 'намеренно' },
	{ eng: 'legend', rus: 'легенда / надпись' },
	{ eng: 'ruin', rus: 'портить / разрушать' },
	{ eng: 'constant', rus: 'постоянный / константный' },
	{ eng: 'breed', rus: 'разводить / размножаться' },
	{ eng: 'bench', rus: 'скамейка / лавочка' },
	{ eng: 'overlook', rus: 'упускать из виду' },
	{ eng: 'injury', rus: 'травма / повреждение' },
	{ eng: 'stool', rus: 'табуретка / стул' },
	{ eng: 'junior', rus: 'младший' },
	{ eng: 'influence', rus: 'влияние' },
	{ eng: 'slice', rus: 'нарезать ломтиками / строгать / разрезать' },
	{ eng: 'formal', rus: 'формальный / официальный' },
	{ eng: 'hook', rus: 'крючок / хук' },
	{ eng: 'weakness', rus: 'слабость / недостаток' },
	{ eng: 'restore', rus: 'восстанавливать / реставрировать' },
	{ eng: 'cool', rus: 'охлаждать / остывать' },
	{ eng: 'intended', rus: 'намеченный / предполагаемый' },
	{ eng: 'regain', rus: 'получать обратно / восстанавливать' },
	{ eng: 'curve', rus: 'изгибаться / искривлять / сворачиваться / петлять' },
	{ eng: 'symbol', rus: 'символ / знак' },
	{ eng: 'thoroughly', rus: 'тщательно / основательно' },
	{ eng: 'equal', rus: 'равный' },
	{ eng: 'layer', rus: 'слой' },
	{ eng: 'rush', rus: 'прилив / спешка' },
	{ eng: 'passion', rus: 'страсть / страстность' },
	{ eng: 'shallow', rus: 'мелкий / неглубокий' },
	{ eng: 'revenge', rus: 'месть' },
	{ eng: 'firm', rus: 'твердый / крепкий' },
	{ eng: 'poison', rus: 'яд' },
	{ eng: 'skip', rus: 'пропускать / бежать вприпрыжку' },
	{ eng: 'discovery', rus: 'открытие / обнаружение' },
	{ eng: 'consciousness', rus: 'сознание / осознание' },
	{ eng: 'sympathy', rus: 'соболезнование / сочувствие / симпатия' },
	{ eng: 'factor', rus: 'фактор / множитель' },
	{ eng: 'practical', rus: 'практический / практичный' },
	{ eng: 'hammer', rus: 'молоток' },
	{ eng: 'loyalty', rus: 'верность / преданность' },
	{ eng: 'consequence', rus: 'последствие / следствие' },
	{ eng: 'dreadful', rus: 'страшный / ужасный' },
	{ eng: 'stamp', rus: 'топать / штамповать' },
	{ eng: 'advance', rus: 'продвижение / аванс' },
	{ eng: 'precisely', rus: 'точно / именно' },
	{ eng: 'automatically', rus: 'автоматически / машинально' },
	{ eng: 'treatment', rus: 'лечение / обращение' },
	{ eng: 'loyal', rus: 'верный / преданный' },
	{ eng: 'ridiculous', rus: 'нелепый / смешной' },
	{ eng: 'concerned', rus: 'обеспокоенный' },
	{ eng: 'risk', rus: 'рисковать / отваживаться' },
	{ eng: 'compound', rus: 'соединение / комплекс' },
	{ eng: 'store', rus: 'хранить / накапливать' },
	{ eng: 'whisky', rus: 'виски' },
	{ eng: 'procedure', rus: 'процедура / порядок' },
	{ eng: 'function', rus: 'функция / назначение' },
	{ eng: 'pitch', rus: 'бросать / устанавливать' },
	{ eng: 'advance', rus: 'продвигать / продвигаться' },
	{ eng: 'reference', rus: 'ссылка / упоминание' },
	{ eng: 'effective', rus: 'эффективный / действенный' },
	{ eng: 'soil', rus: 'почва / грунт' },
	{ eng: 'lifetime', rus: 'продолжительность жизни / целая жизнь' },
	{ eng: 'blush', rus: 'краснеть / заливаться румянцем' },
	{ eng: 'nonsense', rus: 'ерунда / чепуха' },
	{ eng: 'preserve', rus: 'сохранять / консервировать' },
	{ eng: 'absorb', rus: 'поглощать / впитывать' },
	{ eng: 'scheme', rus: 'схема / план' },
	{ eng: 'guard', rus: 'охранять / сторожить' },
	{ eng: 'ship', rus: 'отправлять куда-либо / перевозить груз' },
	{ eng: 'survivor', rus: 'оставшийся в живых / выживший' },
	{ eng: 'forbid', rus: 'запрещать / возбранять' },
	{ eng: 'aspect', rus: 'аспект / вид / точка зрения / сторона' },
	{ eng: 'basis', rus: 'основание / основа' },
	{ eng: 'emotional', rus: 'эмоциональный / волнующий' },
	{ eng: 'astonishment', rus: 'изумление / удивление' },
	{ eng: 'delight', rus: 'восторг / наслаждение' },
	{ eng: 'sometime', rus: 'когда-то / иногда / некогда' },
	{ eng: 'apparent', rus: 'очевидный / видимый' },
	{ eng: 'survival', rus: 'выживание / пережиток' },
	{ eng: 'chase', rus: 'погоня / преследование' },
	{ eng: 'meantime', rus: 'тем временем' },
	{ eng: 'seed', rus: 'семя / семечко' },
	{ eng: 'fantasy', rus: 'фантазия / фантастика' },
	{ eng: 'convinced', rus: 'уверенный' },
	{ eng: 'thoughtful', rus: 'задумчивый / вдумчивый' },
	{ eng: 'feed', rus: 'корм' },
	{ eng: 'conduct', rus: 'проводить / вести' },
	{ eng: 'tradition', rus: 'традиция' },
	{ eng: 'profit', rus: 'прибыль / доход' },
	{ eng: 'shift', rus: 'сдвиг / смена' },
	{ eng: 'approval', rus: 'одобрение' },
	{ eng: 'overcome', rus: 'преодолевать / одолевать' },
	{ eng: 'needle', rus: 'игла / спица' },
	{ eng: 'roughly', rus: 'грубо / приблизительно' },
	{ eng: 'storage', rus: 'хранение / хранилище' },
	{ eng: 'specific', rus: 'конкретный / определенный' },
	{ eng: 'remarkable', rus: 'замечательный / удивительный' },
	{ eng: 'appropriate', rus: 'подходящий / соответствующий' },
	{ eng: 'inquire', rus: 'спрашивать' },
	{ eng: 'protest', rus: 'протестовать / заявлять' },
	{ eng: 'error', rus: 'ошибка / погрешность' },
	{ eng: 'punishment', rus: 'наказание / кара' },
	{ eng: 'outfit', rus: 'одежда / наряд' },
	{ eng: 'untie', rus: 'развязывать / отвязывать' },
	{ eng: 'bar', rus: 'запирать' },
	{ eng: 'chart', rus: 'диаграмма / навигационная карта' },
	{ eng: 'uncertain', rus: 'неопределенный / неуверенный' },
	{ eng: 'violently', rus: 'яростно / сильно' },
	{ eng: 'literally', rus: 'буквально / без преувеличения' },
	{ eng: 'moving', rus: 'трогательный' },
	{ eng: 'astonished', rus: 'потрясенный / изумленный' },
	{ eng: 'compose', rus: 'собирать / сочинять / составлять' },
	{ eng: 'opponent', rus: 'противник / соперник' },
	{ eng: 'division', rus: 'разделение / отдел' },
	{ eng: 'current', rus: 'ток / течение' },
	{ eng: 'sadly', rus: 'грустно / печально' },
	{ eng: 'reserve', rus: 'заповедник / резерв' },
	{ eng: 'fool', rus: 'дурачить / обманывать' },
	{ eng: 'sufficient', rus: 'достаточный / существенный' },
	{ eng: 'activate', rus: 'активировать / приводить в действие' },
	{ eng: 'insult', rus: 'оскорбление / инсульт' },
	{ eng: 'reject', rus: 'отвергать / отклонять' },
	{ eng: 'rise', rus: 'подъем / рост' },
	{ eng: 'suspiciously', rus: 'подозрительно / с подозрением' },
	{ eng: 'assistance', rus: 'помощь' },
	{ eng: 'least', rus: 'наименьший / малейший' },
	{ eng: 'committee', rus: 'комитет / комиссия' },
	{ eng: 'seal', rus: 'печать / пломба / тюлень' },
	{ eng: 'plot', rus: 'сюжет / участок земли' },
	{ eng: 'remains', rus: 'останки / руины / развалины' },
	{ eng: 'amazement', rus: 'изумление / удивление' },
	{ eng: 'purchase', rus: 'покупка / приобретение' },
	{ eng: 'enthusiasm', rus: 'энтузиазм / восторженность' },
	{ eng: 'evil', rus: 'зло / порок' },
	{ eng: 'flow', rus: 'поток / течение' },
	{ eng: 'impatient', rus: 'нетерпеливый / относящийся нетерпимо к чему-либо' },
	{ eng: 'circular', rus: 'круглый / круговой' },
	{ eng: 'media', rus: 'СМИ (средства массовой информации) / пресса' },
	{ eng: 'brightly', rus: 'ярко' },
	{ eng: 'fix', rus: 'решение / местоположение' },
	{ eng: 'offence', rus: 'преступление / обида' },
	{ eng: 'strategy', rus: 'стратегия / оперативное искусство' },
	{ eng: 'ensure', rus: 'обеспечивать / гарантировать' },
	{ eng: 'scare', rus: 'паника / внезапный испуг' },
	{ eng: 'consideration', rus: 'рассмотрение / соображение' },
	{ eng: 'force', rus: 'заставлять / вынуждать' },
	{ eng: 'joint', rus: 'совместный / совмещенный' },
	{ eng: 'delight', rus: 'наслаждаться / восхищать' },
	{ eng: 'worm', rus: 'червь' },
	{ eng: 'growth', rus: 'рост / прирост' },
	{ eng: 'exception', rus: 'исключение / особая ситуация' },
	{ eng: 'pond', rus: 'пруд / водоем' },
	{ eng: 'profile', rus: 'профиль / краткий биографический очерк' },
	{ eng: 'wide', rus: 'широко' },
	{ eng: 'ton', rus: 'тонна / огромное количество' },
	{ eng: 'cooperate', rus: 'сотрудничать / содействовать' },
	{ eng: 'spread', rus: 'распространение / пастообразные продукты' },
	{ eng: 'transparent', rus: 'прозрачный' },
	{ eng: 'presumably', rus: 'предположительно / вероятно' },
	{ eng: 'furiously', rus: 'бешено / яростно' },
	{ eng: 'artificial', rus: 'искусственный / притворный' },
	{ eng: 'review', rus: 'пересматривать / рассматривать' },
	{ eng: 'sexual', rus: 'сексуальный / половой' },
	{ eng: 'substance', rus: 'вещество / содержание' },
	{ eng: 'dairy', rus: 'молочные продукты / маслодельня' },
	{ eng: 'elegant', rus: 'элегантный / изысканный' },
	{ eng: 'relatively', rus: 'относительно / сравнительно' },
	{ eng: 'affection', rus: 'привязанность / любовь' },
	{ eng: 'adopt', rus: 'усыновлять / принимать' },
	{ eng: 'liar', rus: 'лжец / врун' },
	{ eng: 'pitch', rus: 'тональность звука / поле' },
	{ eng: 'productive', rus: 'продуктивный / плодотворный' },
	{ eng: 'precise', rus: 'точный / четкий' },
	{ eng: 'newly', rus: 'вновь / недавно' },
	{ eng: 'moral', rus: 'моральный / нравственный' },
	{ eng: 'state', rus: 'утверждать / констатировать' },
	{ eng: 'necessarily', rus: 'обязательно / неизбежно' },
	{ eng: 'severe', rus: 'серьезный / суровый' },
	{ eng: 'protective', rus: 'защитный' },
	{ eng: 'trade', rus: 'торговать / обменивать' },
	{ eng: 'unfamiliar', rus: 'незнакомый / непривычный' },
	{ eng: 'low', rus: 'низкий уровень / падение в жизни (карьере)' },
	{ eng: 'determination', rus: 'определение / решительность' },
	{ eng: 'mentally', rus: 'умственно / мысленно' },
	{ eng: 'undoubtedly', rus: 'несомненно / безусловно' },
	{ eng: 'affair', rus: 'дело / любовная интрижка' },
	{ eng: 'challenge', rus: 'оспаривать / бросать вызов' },
	{ eng: 'remark', rus: 'замечать / отмечать' },
	{ eng: 'hurt', rus: 'боль / обида' },
	{ eng: 'related', rus: 'родственный' },
	{ eng: 'revolution', rus: 'революция / оборот' },
	{ eng: 'insult', rus: 'оскорблять' },
	{ eng: 'ray', rus: 'луч' },
	{ eng: 'cruise', rus: 'двигаться с крейсерской скоростью / проезжать' },
	{ eng: 'technical', rus: 'технический / специальный' },
	{ eng: 'third', rus: 'треть / третья часть' },
	{ eng: 'deer', rus: 'олень / лань' },
	{ eng: 'outline', rus: 'очертание / изложение / контур' },
	{ eng: 'virtually', rus: 'практически / фактически / почти полностью' },
	{ eng: 'convert', rus: 'превращать / переводить' },
	{ eng: 'discipline', rus: 'дисциплина / дисциплинированность' },
	{ eng: 'tragedy', rus: 'трагедия / трагизм' },
	{ eng: 'production', rus: 'производство / производительность' },
	{ eng: 'microphone', rus: 'микрофон' },
	{ eng: 'currently', rus: 'в настоящее время' },
	{ eng: 'justify', rus: 'оправдывать / объяснять' },
	{ eng: 'inspire', rus: 'вдохновлять / внушать' },
	{ eng: 'badge', rus: 'значок / знак' },
	{ eng: 'fire', rus: 'стрелять / увольнять' },
	{ eng: 'ultimate', rus: 'конечный / высший' },
	{ eng: 'rotten', rus: 'гнилой / тухлый' },
	{ eng: 'simultaneously', rus: 'одновременно' },
	{ eng: 'extent', rus: 'степень / экстент' },
	{ eng: 'function', rus: 'работать / функционировать' },
	{ eng: 'heat', rus: 'подогреть / нагревать' },
	{ eng: 'developed', rus: 'развитый' },
	{ eng: 'embarrassment', rus: 'смущение / затруднение' },
	{ eng: 'estimate', rus: 'оценивать / составлять смету' },
	{ eng: 'power', rus: 'питать энергией' },
	{ eng: 'dominate', rus: 'доминировать / преобладать' },
	{ eng: 'sadness', rus: 'печаль / уныние' },
	{ eng: 'encounter', rus: 'столкновение / неожиданная встреча' },
	{ eng: 'fortunate', rus: 'удачливый / счастливый' },
	{ eng: 'demonstrate', rus: 'демонстрировать / доказывать' },
	{ eng: 'miracle', rus: 'чудо / удивительная вещь' },
	{ eng: 'generate', rus: 'генерировать / производить' },
	{ eng: 'transform', rus: 'превращать / преобразовывать' },
	{ eng: 'hedge', rus: 'живая изгородь / изгородь' },
	{ eng: 'plot', rus: 'замышлять' },
	{ eng: 'script', rus: 'сценарий / подлинник' },
	{ eng: 'colony', rus: 'колония' },
	{ eng: 'analyse', rus: 'анализировать' },
	{ eng: 'disguise', rus: 'скрывать / маскировать' },
	{ eng: 'enclose', rus: 'закрывать со всех сторон / окружать' },
	{ eng: 'costume', rus: 'костюм' },
	{ eng: 'mixture', rus: 'смесь / микстура' },
	{ eng: 'surgery', rus: 'хирургия / хирургическая операция' },
	{ eng: 'fine', rus: 'прекрасно / отлично' },
	{ eng: 'flash', rus: 'вспышка' },
	{ eng: 'admiration', rus: 'восхищение' },
	{ eng: 'injured', rus: 'раненый' },
	{ eng: 'deceive', rus: 'обманывать / обмануть' },
	{ eng: 'drug', rus: 'лекарство / наркотик' },
	{ eng: 'guarantee', rus: 'гарантия / поручительство' },
	{ eng: 'copper', rus: 'медь / медная монета' },
	{ eng: 'wrong', rus: 'неправильность / неправота' },
	{ eng: 'editor', rus: 'редактор / монтажер' },
	{ eng: 'lord', rus: 'лорд / господин' },
	{ eng: 'define', rus: 'определять / устанавливать' },
	{ eng: 'elect', rus: 'избирать / выбирать' },
	{ eng: 'horn', rus: 'гудок / горн' },
	{ eng: 'harmless', rus: 'безвредный / безобидный' },
	{ eng: 'dealer', rus: 'дилер / торговец' },
	{ eng: 'mysterious', rus: 'мистический / таинственный' },
	{ eng: 'considerably', rus: 'изрядно / значительно' },
	{ eng: 'surrounding', rus: 'окружающий / окрестный' },
	{ eng: 'defender', rus: 'защитник / сторонник' },
	{ eng: 'evident', rus: 'очевидный / явный' },
	{ eng: 'unaware', rus: 'неосведомлённый / не знающий / не подозревающий' },
	{ eng: 'institute', rus: 'институт / учреждение' },
	{ eng: 'cycle', rus: 'цикл / велосипед' },
	{ eng: 'modest', rus: 'скромный / небольшой' },
	{ eng: 'basically', rus: 'в основном / по существу' },
	{ eng: 'punch', rus: 'пунш / удар (кулаком)' },
	{ eng: 'abandoned', rus: 'заброшенный / покинутый' },
	{ eng: 'dramatic', rus: 'драматический / резкий' },
	{ eng: 'eagle', rus: 'орел' },
	{ eng: 'devote', rus: 'посвящать / уделять' },
	{ eng: 'replacement', rus: 'замена' },
	{ eng: 'volunteer', rus: 'доброволец / волонтер' },
	{ eng: 'dizzy', rus: 'головокружительный / чувствующий головокружение' },
	{ eng: 'water', rus: 'поливать / поить' },
	{ eng: 'distinguish', rus: 'различать / отличать' },
	{ eng: 'rape', rus: 'насиловать' },
	{ eng: 'conspiracy', rus: 'заговор / конспирация' },
	{ eng: 'arrogant', rus: 'высокомерный' },
	{ eng: 'confession', rus: 'признание / исповедь' },
	{ eng: 'increasingly', rus: 'все больше и больше / в большей степени' },
	{ eng: 'industrial', rus: 'промышленный / индустриальный' },
	{ eng: 'deliberate', rus: 'преднамеренный / умышленный' },
	{ eng: 'correct', rus: 'исправлять / корректировать' },
	{ eng: 'behalf', rus: 'действие от лица кого-то' },
	{ eng: 'management', rus: 'руководство / управление / менеджмент' },
	{ eng: 'acid', rus: 'кислота' },
	{ eng: 'contrast', rus: 'контраст / отличие' },
	{ eng: 'proposal', rus: 'предложение / план' },
	{ eng: 'theft', rus: 'кража' },
	{ eng: 'introduction', rus: 'введение / внедрение' },
	{ eng: 'readily', rus: 'легко / охотно' },
	{ eng: 'strain', rus: 'напряжение / штамм / вид' },
	{ eng: 'vacant', rus: 'вакантный / незанятый' },
	{ eng: 'largely', rus: 'во многом / большей частью' },
	{ eng: 'renew', rus: 'возобновлять / обновлять' },
	{ eng: 'manufacture', rus: 'производить / изготовлять' },
	{ eng: 'thorough', rus: 'тщательный / полный' },
	{ eng: 'virtual', rus: 'виртуальный / фактический' },
	{ eng: 'strengthen', rus: 'укреплять' },
	{ eng: 'bent', rus: 'кривой' },
	{ eng: 'disappearance', rus: 'исчезновение' },
	{ eng: 'napkin', rus: 'салфетка / подгузник' },
	{ eng: 'frost', rus: 'мороз / иней' },
	{ eng: 'recovery', rus: 'восстановление / выздоровление' },
	{ eng: 'dimension', rus: 'измерение / аспект' },
	{ eng: 'amused', rus: 'веселый / насмешливый' },
	{ eng: 'bizarre', rus: 'странный / эксцентричный' },
	{ eng: 'effectively', rus: 'эффективно / продуктивно' },
	{ eng: 'transport', rus: 'перевозить / транспортировать' },
	{ eng: 'gardener', rus: 'садовник / садовод' },
	{ eng: 'contrary', rus: 'что-то противоположное / что-то обратное' },
	{ eng: 'harmony', rus: 'согласие / гармония' },
	{ eng: 'myth', rus: 'миф / вымысел' },
	{ eng: 'fascinating', rus: 'увлекательный' },
	{ eng: 'oval', rus: 'овальный' },
	{ eng: 'characteristic', rus: 'характеристика / особенность' },
	{ eng: 'sparkling', rus: 'блистательный' },
	{ eng: 'time', rus: 'рассчитывать время / назначать время' },
	{ eng: 'whisper', rus: 'шепот / слух' },
	{ eng: 'so-called', rus: 'так называемый' },
	{ eng: 'income', rus: 'доход' },
	{ eng: 'dose', rus: 'доза / порция' },
	{ eng: 'economy', rus: 'экономика / экономия' },
	{ eng: 'chimney', rus: 'дымоход / труба' },
	{ eng: 'essentially', rus: 'по существу / существенно' },
	{ eng: 'cure', rus: 'лечить' },
	{ eng: 'swan', rus: 'лебедь / бард' },
	{ eng: 'graduate', rus: 'оканчивать учебное заведение / получать диплом, степень' },
	{ eng: 'snore', rus: 'храпеть' },
	{ eng: 'guarantee', rus: 'гарантировать / обеспечивать' },
	{ eng: 'upset', rus: 'расстраивать / огорчать' },
	{ eng: 'inhabitant', rus: 'житель' },
	{ eng: 'rape', rus: 'изнасилование / рапс' },
	{ eng: 'transfer', rus: 'перевод / трансфер' },
	{ eng: 'harvest', rus: 'жатва / урожай' },
	{ eng: 'extension', rus: 'продление / расширение' },
	{ eng: 'sophisticated', rus: 'сложный' },
	{ eng: 'universal', rus: 'универсальный / всеобщий' },
	{ eng: 'alike', rus: 'похоже / одинаково' },
	{ eng: 'specialise', rus: 'специализироваться / специализировать' },
	{ eng: 'unwilling', rus: 'невольный / несклонный / нежелающий' },
	{ eng: 'hell', rus: 'ад / преисподняя' },
	{ eng: 'economic', rus: 'экономический / хозяйственный' },
	{ eng: 'estimate', rus: 'оценка / смета' },
	{ eng: 'invest', rus: 'инвестировать / вкладывать деньги' },
	{ eng: 'hire', rus: 'прокат / наем' },
	{ eng: 'respectable', rus: 'уважаемый / респектабельный / приличный' },
	{ eng: 'unsure', rus: 'неуверенный / ненадежный' },
	{ eng: 'medal', rus: 'медаль / орден' },
	{ eng: 'telescope', rus: 'телескоп / оптическая подзорная труба' },
	{ eng: 'feature', rus: 'включать / показывать' },
	{ eng: 'unnatural', rus: 'неестественный / необычный' },
	{ eng: 'wolf', rus: 'волк / хищник' },
	{ eng: 'master', rus: 'овладевать / усвоить' },
	{ eng: 'enthusiastic', rus: 'полный энтузиазма / восторженный' },
	{ eng: 'volcano', rus: 'вулкан / сопка' },
	{ eng: 'praise', rus: 'хвалить / восхвалять' },
	{ eng: 'entitle', rus: 'давать право / озаглавливать' },
	{ eng: 'rocket', rus: 'ракета / реактивный снаряд' },
	{ eng: 'underestimate', rus: 'недооценивать / занижать' },
	{ eng: 'following', rus: 'после / вследствие' },
	{ eng: 'enable', rus: 'давать возможность / разрешать' },
	{ eng: 'overtake', rus: 'обгонять / догонять' },
	{ eng: 'govern', rus: 'управлять / править' },
	{ eng: 'moonlight', rus: 'лунный свет' },
	{ eng: 'associated', rus: 'действующий совместно' },
	{ eng: 'childish', rus: 'детский / ребячливый' },
	{ eng: 'symptom', rus: 'симптом' },
	{ eng: 'delightful', rus: 'восхитительный / очаровательный' },
	{ eng: 'penalty', rus: 'штраф / наказание' },
	{ eng: 'interact', rus: 'взаимодействовать' },
	{ eng: 'genuinely', rus: 'неподдельно / искренне' },
	{ eng: 'gambling', rus: 'азартная игра / игорный бизнес' },
	{ eng: 'balanced', rus: 'балансированный' },
	{ eng: 'comment', rus: 'комментировать' },
	{ eng: 'access', rus: 'получать доступ' },
	{ eng: 'qualify', rus: 'квалифицировать / иметь право' },
	{ eng: 'conduct', rus: 'поведение / ведение' },
	{ eng: 'manual', rus: 'ручной / физический' },
	{ eng: 'lighting', rus: 'освещение / осветительные приборы' },
	{ eng: 'marker', rus: 'метка / фломастер / маркер' },
	{ eng: 'therapy', rus: 'терапия / лечение' },
	{ eng: 'extensive', rus: 'обширный / масштабный / большой' },
	{ eng: 'honesty', rus: 'честность / правдивость' },
	{ eng: 'offensive', rus: 'оскорбительный / наступательный' },
	{ eng: 'spiritual', rus: 'духовный / одухотворенный' },
	{ eng: 'intellectual', rus: 'интеллектуальный / умственный' },
	{ eng: 'risky', rus: 'рискованный' },
	{ eng: 'worthwhile', rus: 'стоящий / путный' },
	{ eng: 'episode', rus: 'эпизод / серия' },
	{ eng: 'bonus', rus: 'премия / бонус' },
	{ eng: 'organic', rus: 'органический / натуральный' },
	{ eng: 'advertising', rus: 'реклама / рекламный бизнес' },
	{ eng: 'misunderstand', rus: 'неправильно понять' },
	{ eng: 'supervise', rus: 'наблюдать / надзирать' },
	{ eng: 'electronics', rus: 'электроника / электронная аппаратура' },
	{ eng: 'crab', rus: 'краб' },
	{ eng: 'collector', rus: 'коллекционер / коллектор' },
	{ eng: 'tragic', rus: 'трагический' },
	{ eng: 'sneeze', rus: 'чихать / начихать' },
	{ eng: 'aluminium', rus: 'алюминий' },
	{ eng: 'infection', rus: 'инфекция / заражение' },
	{ eng: 'release', rus: 'освобождение / релиз' },
	{ eng: 'assess', rus: 'оценивать' },
	{ eng: 'compromise', rus: 'компрометировать / идти на компромисс / ставить под угрозу' },
	{ eng: 'rival', rus: 'конкурирующий' },
	{ eng: 'positively', rus: 'позитивно / определенно / положительно' },
	{ eng: 'supernatural', rus: 'сверхъестественный' },
	{ eng: 'trick', rus: 'обмануть / обхитрить' },
	{ eng: 'stiff', rus: 'до смерти / до изнеможения' },
	{ eng: 'envy', rus: 'завидовать' },
	{ eng: 'martial', rus: 'военный / воинственный' },
	{ eng: 'appreciation', rus: 'признательность / тонкое восприятие' },
	{ eng: 'continuous', rus: 'непрерывный / длительный' },
	{ eng: 'winding', rus: 'извилистый / вьющийся' },
	{ eng: 'repay', rus: 'возвращать / отплачивать' },
	{ eng: 'investor', rus: 'инвестор' },
	{ eng: 'theme', rus: 'тема / предмет' },
	{ eng: 'leak', rus: 'утечка / течь' },
	{ eng: 'cruelty', rus: 'жестокость / бессердечие' },
	{ eng: 'variation', rus: 'изменение / разновидность' },
	{ eng: 'commitment', rus: 'обязательство / совершение' },
	{ eng: 'finance', rus: 'финансы / финансовое дело' },
	{ eng: 'liver', rus: 'печень / печенка' },
	{ eng: 'will', rus: 'воля / желание / завещание' },
	{ eng: 'ambitious', rus: 'честолюбивый / целеустремленный' },
	{ eng: 'partial', rus: 'частичный / неполный' },
	{ eng: 'retirement', rus: 'отставка / выход на пенсию' },
	{ eng: 'psychology', rus: 'психология / психика' },
	{ eng: 'carbon', rus: 'углерод / уголь' },
	{ eng: 'encouragement', rus: 'поощрение / ободрение' },
	{ eng: 'kingdom', rus: 'царство / королевство' },
	{ eng: 'triangle', rus: 'треугольник / угольник для черчения' },
	{ eng: 'compromise', rus: 'компромисс / компрометация' },
	{ eng: 'edit', rus: 'редактировать' },
	{ eng: 'screen', rus: 'скрывать' },
	{ eng: 'abuse', rus: 'злоупотребление / оскорбление' },
	{ eng: 'slide', rus: 'слайд / горка' },
	{ eng: 'throughout', rus: 'повсюду / на протяжении' },
	{ eng: 'nursery', rus: 'детский сад / детская комната / питомник' },
	{ eng: 'award', rus: 'присуждение / премия' },
	{ eng: 'edition', rus: 'издание / редакция' },
	{ eng: 'pint', rus: 'пинта (GB 0,57 л) (US 0,473 л) / кружка' },
	{ eng: 'legally', rus: 'легально / юридически' },
	{ eng: 'poisonous', rus: 'ядовитый / отвратительный' },
	{ eng: 'academic', rus: 'академический / учебный' },
	{ eng: 'involvement', rus: 'участие / вовлечение' },
	{ eng: 'terrifying', rus: 'ужасающий / устрашающий' },
	{ eng: 'participate', rus: 'участвовать / принимать участие' },
	{ eng: 'trivial', rus: 'тривиальный / незначительный' },
	{ eng: 'navigation', rus: 'навигация / плавание' },
	{ eng: 'failed', rus: 'неудачный' },
	{ eng: 'share', rus: 'доля / акция' },
	{ eng: 'sexy', rus: 'сексуальный' },
	{ eng: 'flexible', rus: 'гибкий / свободный' },
	{ eng: 'criticism', rus: 'критика' },
	{ eng: 'expertise', rus: 'компетентность / экспертиза' },
	{ eng: 'emotionally', rus: 'эмоционально' },
	{ eng: 'demanding', rus: 'требующий усилий / требовательный' },
	{ eng: 'soaked', rus: 'промокший насквозь' },
	{ eng: 'whereas', rus: 'поскольку / тогда как' },
	{ eng: 'brother-in-law', rus: 'шурин / свояк' },
	{ eng: 'researcher', rus: 'исследователь' },
	{ eng: 'stunning', rus: 'великолепный' },
	{ eng: 'leopard', rus: 'леопард / барс' },
	{ eng: 'crucial', rus: 'ключевой / решающий' },
	{ eng: 'context', rus: 'контекст / ситуация' },
	{ eng: 'burglar', rus: 'грабитель / взломщик' },
	{ eng: 'irresponsible', rus: 'безответственный / несознательный' },
	{ eng: 'unattractive', rus: 'непривлекательный / малопривлекательный' },
	{ eng: 'extreme', rus: 'крайность / перепад' },
	{ eng: 'poverty', rus: 'бедность' },
	{ eng: 'map', rus: 'наносить на карту' },
	{ eng: 'desirable', rus: 'желательный' },
	{ eng: 'philosopher', rus: 'философ' },
	{ eng: 'implement', rus: 'осуществлять' },
	{ eng: 'depressing', rus: 'наводящий уныние' },
	{ eng: 'breakdown', rus: 'поломка / нарушение' },
	{ eng: 'bumper', rus: 'бампер / буфер' },
	{ eng: 'valid', rus: 'действительный / веский' },
	{ eng: 'tribe', rus: 'племя' },
	{ eng: 'deprive', rus: 'лишать / отнимать' },
	{ eng: 'stimulate', rus: 'стимулировать / возбуждать' },
	{ eng: 'critic', rus: 'критик' },
	{ eng: 'faculty', rus: 'факультет / способность' },
	{ eng: 'divorce', rus: 'разводиться / развестись' },
	{ eng: 'welfare', rus: 'благосостояние / благополучие' },
	{ eng: 'category', rus: 'категория / разряд' },
	{ eng: 'separation', rus: 'отделение / разделение' },
	{ eng: 'commerce', rus: 'коммерция / торговля' },
	{ eng: 'abstract', rus: 'абстрактный' },
	{ eng: 'initially', rus: 'первоначально / в начальной стадии' },
	{ eng: 'functional', rus: 'функционирующий / работоспособной' },
	{ eng: 'understandable', rus: 'понятный / ясный' },
	{ eng: 'obsessed', rus: 'одержимый' },
	{ eng: 'experiment', rus: 'экспериментировать / пробовать' },
	{ eng: 'tackle', rus: 'перехватывать / приниматься за / браться за' },
	{ eng: 'criticise', rus: 'критиковать / осуждать' },
	{ eng: 'bend', rus: 'изгиб / поворот' },
	{ eng: 'revolutionary', rus: 'революционный / вращающийся' },
	{ eng: 'amount', rus: 'составлять / достигать' },
	{ eng: 'stadium', rus: 'стадион / стадий' },
	{ eng: 'accidental', rus: 'случайный / неожиданный' },
	{ eng: 'rearrange', rus: 'переставлять / перестраивать' },
	{ eng: 'squash', rus: 'раздавливать / давить' },
	{ eng: 'helper', rus: 'помощник' },
	{ eng: 'bun', rus: 'булочка / пучок волос' },
	{ eng: 'trophy', rus: 'трофей / награда / приз' },
	{ eng: 'audio', rus: 'звуковой / аудио-' },
	{ eng: 'neighbouring', rus: 'соседний / близлежащий' },
	{ eng: 'stormy', rus: 'бурный / штормовой' },
	{ eng: 'daytime', rus: 'дневное время / день' },
	{ eng: 'optimistic', rus: 'оптимистичный / оптимистический' },
	{ eng: 'partnership', rus: 'партнерство / сотрудничество / товарищество' },
	{ eng: 'gig', rus: 'кабриолет / двуколка' },
	{ eng: 'punk', rus: 'панк' },
	{ eng: 'coastal', rus: 'береговой / прибрежный' },
	{ eng: 'viewer', rus: 'зритель / осмотрщик' },
	{ eng: 'advance', rus: 'предварительный / авансовый' },
	{ eng: 'athletic', rus: 'спортивный / атлетический' },
	{ eng: 'influence', rus: 'влиять / оказывать влияние' },
	{ eng: 'deadline', rus: 'крайний срок / предельный срок' },
	{ eng: 'preference', rus: 'предпочтение / преференция' },
	{ eng: 'model', rus: 'моделировать' },
	{ eng: 'enjoyment', rus: 'наслаждение / удовольствие' },
	{ eng: 'pedal', rus: 'педаль / ножной рычаг' },
	{ eng: 'favourable', rus: 'благоприятный / благосклонный' },
	{ eng: 'artistic', rus: 'художественный / артистический' },
	{ eng: 'tutor', rus: 'репетитор / наставник' },
	{ eng: 'unreasonable', rus: 'чрезмерный / неблагоразумный' },
	{ eng: 'profitable', rus: 'прибыльный / выгодный' },
	{ eng: 'sack', rus: 'увольнять / грабить' },
	{ eng: 'attachment', rus: 'привязанность / прикрепление' },
	{ eng: 'realistic', rus: 'реалистичный / реалистический' },
	{ eng: 'sporting', rus: 'спортивный / охотничий' },
	{ eng: 'regional', rus: 'региональный / областной' },
	{ eng: 'brilliantly', rus: 'блестяще / блистательно' },
	{ eng: 'caring', rus: 'заботливый' },
	{ eng: 'eyelash', rus: 'ресница / ресничка' },
	{ eng: 'separately', rus: 'отдельно / особо' },
	{ eng: 'irritating', rus: 'раздражающий / раздражительный' },
	{ eng: 'politeness', rus: 'вежливость / учтивость' },
	{ eng: 'reporting', rus: 'отчет / представление информации' },
	{ eng: 'export', rus: 'экспорт / вывоз' },
	{ eng: 'rehearsal', rus: 'репетиция / повторение' },
	{ eng: 'consequently', rus: 'следовательно / в результате' },
	{ eng: 'minority', rus: 'меньшинство / меньшая часть' },
	{ eng: 'carelessly', rus: 'беспечно / небрежно' },
	{ eng: 'residential', rus: 'жилой / связанный с местом жительства' },
	{ eng: 'meaningful', rus: 'многозначительный / значительный' },
	{ eng: 'conductor', rus: 'дирижер / проводник' },
	{ eng: 'energetic', rus: 'энергичный / активный' },
	{ eng: 'parachute', rus: 'парашют / купол парашюта' },
	{ eng: 'award', rus: 'присуждать / награждать' },
	{ eng: 'pudding', rus: 'пудинг / десерт' },
	{ eng: 'presidential', rus: 'президентский' },
	{ eng: 'fluent', rus: 'беглый / свободно говорящий' },
	{ eng: 'crossroad', rus: 'перекресток / перепутье / важная точка' },
	{ eng: 'rural', rus: 'сельский / деревенский' },
	{ eng: 'encouraging', rus: 'ободрительный / обнадеживающий' },
	{ eng: 'dissatisfaction', rus: 'недовольство / неудовлетворенность' },
	{ eng: 'imperative', rus: 'императив / повеление / повелительное наклонение' },
	{ eng: 'commission', rus: 'поручать / заказывать' },
	{ eng: 'outstanding', rus: 'выдающийся / незаурядный' },
	{ eng: 'unlimited', rus: 'неограниченный' },
	{ eng: 'toxic', rus: 'токсический / ядовитый' },
	{ eng: 'statistic', rus: 'статистика / статистические данные' },
	{ eng: 'choir', rus: 'хор / хоры' },
	{ eng: 'vividly', rus: 'ярко / живо' },
	{ eng: 'specify', rus: 'указывать / уточнять' },
	{ eng: 'continuously', rus: 'продолжительно / беспрерывно' },
	{ eng: 'update', rus: 'обновленная информация / последние данные' },
	{ eng: 'consumer', rus: 'потребитель / потребительский' },
	{ eng: 'naughty', rus: 'непослушный / озорной' },
	{ eng: 'mathematical', rus: 'математический' },
	{ eng: 'pancake', rus: 'блин / оладушек' },
	{ eng: 'informal', rus: 'неофициальный / неформальный' },
	{ eng: 'thesis', rus: 'диссертация / тезис' },
	{ eng: 'novelist', rus: 'писатель-романист' },
	{ eng: 'ban', rus: 'запрещать / налагать запрет' },
	{ eng: 'recreation', rus: 'отдых / развлечение' },
	{ eng: 'enthusiastically', rus: 'с восторгом / с энтузиазмом' },
	{ eng: 'faithfully', rus: 'верно' },
	{ eng: 'consultant', rus: 'консультант / консультант компании' },
	{ eng: 'canned', rus: 'консервированный / заготовленный заранее' },
	{ eng: 'national', rus: 'гражданин / соотечественник' },
	{ eng: 'significantly', rus: 'существенно / значительно' },
	{ eng: 'preferably', rus: 'предпочтительно / лучше' },
	{ eng: 'split', rus: 'раскол / прорезь' },
	{ eng: 'proposed', rus: 'предложенный' },
	{ eng: 'denim', rus: 'джинсовая ткань' },
	{ eng: 'stepmother', rus: 'мачеха' },
	{ eng: 'lifestyle', rus: 'стиль жизни / образ жизни' },
	{ eng: 'tornado', rus: 'смерч / торнадо' },
	{ eng: 'tomb', rus: 'могила / гробница' },
	{ eng: 'cruelly', rus: 'жестоко / мучительно' },
	{ eng: 'educational', rus: 'образовательный / учебный' },
	{ eng: 'soaking', rus: 'промокший до нитки' },
	{ eng: 'sister-in-law', rus: 'невестка / золовка' },
	{ eng: 'mother-in-law', rus: 'теща / свекровь' },
	{ eng: 'boost', rus: 'поддержка / повышение' },
	{ eng: 'manufacturer', rus: 'производитель' },
	{ eng: 'burglary', rus: 'кража со взломом / ограбление со взломом' },
	{ eng: 'willingness', rus: 'готовность' },
	{ eng: 'tablecloth', rus: 'скатерть' },
	{ eng: 'swing', rus: 'качели / замах' },
	{ eng: 'cite', rus: 'ссылаться / цитировать' },
	{ eng: 'unhappiness', rus: 'несчастье' },
	{ eng: 'zipper', rus: 'молния / ботинки или сапоги на молнии' },
	{ eng: 'decorative', rus: 'декоративный / фигурный' },
	{ eng: 'bothered', rus: 'обеспокоенный' },
	{ eng: 'conveniently', rus: 'удобно' },
	{ eng: 'bombing', rus: 'бомбежка / бомбардировка' },
	{ eng: 'info', rus: 'информация / сообщения' },
	{ eng: 'fossil', rus: 'окаменелость / ископаемое' },
	{ eng: 'surface', rus: 'всплывать / внезапно появляться' },
	{ eng: 'preferable', rus: 'предпочтительный / предпочитаемый' },
	{ eng: 'racial', rus: 'расовый' },
	{ eng: 'stress', rus: 'подчеркивать' },
	{ eng: 'tightness', rus: 'теснота / герметичность' },
	{ eng: 'inexperienced', rus: 'неопытный / желторотый' },
	{ eng: 'passionately', rus: 'горячо / неистово' },
	{ eng: 'overseas', rus: 'за морем / за границей' },
	{ eng: 'mixed', rus: 'смешанный / разнородный' },
	{ eng: 'waterproof', rus: 'водонепроницаемый / непромокаемый' },
	{ eng: 'splash', rus: 'всплеск / брызги' },
	{ eng: 'addict', rus: 'наркоман / поклонник' },
	{ eng: 'innocently', rus: 'невинно / наивно' },
	{ eng: 'petrified', rus: 'окаменелый' },
	{ eng: 'elegantly', rus: 'элегантно / изящно' },
	{ eng: 'graph', rus: 'график / диаграмма' },
	{ eng: 'last-minute', rus: 'последний / осуществляемый в последнюю минуту' },
	{ eng: 'shopkeeper', rus: 'лавочник / управляющий или владелец магазина' },
	{ eng: 'distinguished', rus: 'известный / выдающийся' },
	{ eng: 'highlight', rus: 'основной момент / подсветка' },
	{ eng: 'dynamic', rus: 'динамический / динамичный' },
	{ eng: 'friendliness', rus: 'дружелюбие' },
	{ eng: 'browse', rus: 'просматривать' },
	{ eng: 'morally', rus: 'морально / в нравственном отношении' },
	{ eng: 'addiction', rus: 'наркомания / зависимость' },
	{ eng: 'undressed', rus: 'раздетый / необработанный' },
	{ eng: 'gradual', rus: 'постепенный / последовательный' },
	{ eng: 'generously', rus: 'щедро / великодушно' },
	{ eng: 'gaming', rus: 'азартная игра / игра' },
	{ eng: 'feedback', rus: 'отзыв / отклик' },
	{ eng: 'dissatisfied', rus: 'неудовлетворенный / недовольный' },
	{ eng: 'picturesque', rus: 'живописный / колоритный' },
	{ eng: 'credit', rus: 'кредитовать / доверять' },
	{ eng: 'ban', rus: 'запрет / запрещение' },
	{ eng: 'screening', rus: 'скрининг / экранирование' },
	{ eng: 'appropriately', rus: 'соответствующим образом' },
	{ eng: 'marathon', rus: 'марафон / марафонский бег' },
	{ eng: 'designer', rus: 'дизайнерский / авторский' },
	{ eng: 'sponsor', rus: 'спонсор / поручитель' },
	{ eng: 'traditionally', rus: 'традиционно / по традиции' },
	{ eng: 'sponsor', rus: 'финансировать / спонсировать' },
	{ eng: 'terrorism', rus: 'терроризм' },
	{ eng: 'unclear', rus: 'неясный / непонятный' },
	{ eng: 'nutrient', rus: 'питательное вещество / вещество' },
	{ eng: 'teaspoon', rus: 'чайная ложка / чайная' },
	{ eng: 'adequately', rus: 'адекватно / в достаточной мере' },
	{ eng: 'self-confidence', rus: 'уверенность в себе / самоуверенность' },
	{ eng: 'terms', rus: 'условия / гонорар / выражения' },
	{ eng: 'prompt', rus: 'незамедлительный / проворный' },
	{ eng: 'toenail', rus: 'ноготь на пальце ноги / ноготь' },
	{ eng: 'inventor', rus: 'изобретатель' },
	{ eng: 'short-term', rus: 'кратковременный / краткосрочный' },
	{ eng: 'enquire', rus: 'спрашивать / исследовать' },
	{ eng: 'genetics', rus: 'генетика' },
	{ eng: 'title', rus: 'называть / называться' },
	{ eng: 'seminar', rus: 'семинар / научная конференция' },
	{ eng: 'unacceptable', rus: 'неприемлемый / нежелательный' },
	{ eng: 'tiredness', rus: 'усталость / утомление' },
	{ eng: 'varied', rus: 'разнообразный / различный' },
	{ eng: 'manufacturing', rus: 'производство / обрабатывающая промышленность' },
	{ eng: 'worrying', rus: 'тревожный' },
	{ eng: 'disorganised', rus: 'плохо организованный / неорганизованный' },
	{ eng: 'conjunction', rus: 'союз / конъюнкция' },
	{ eng: 'conservation', rus: 'сохранение / охрана природы' },
	{ eng: 'protester', rus: 'протестующий / протестант' },
	{ eng: 'composer', rus: 'композитор' },
	{ eng: 'ecological', rus: 'экологический / экологически чистый' },
	{ eng: 'rubber', rus: 'резиновый' },
	{ eng: 'secondly', rus: 'во-вторых / кроме того' },
	{ eng: 'saving', rus: 'спасение / экономия' },
	{ eng: 'publishing', rus: 'издательское дело / издательство' },
	{ eng: 'harmful', rus: 'вредный' },
	{ eng: 'artificially', rus: 'искусственно' },
	{ eng: 'psychologically', rus: 'психологически' },
	{ eng: 'daughter-in-law', rus: 'невестка / сноха' },
	{ eng: 'socialise', rus: 'общаться / обобществлять' },
	{ eng: 'unpopular', rus: 'непопулярный / не пользующийся любовью' },
	{ eng: 'disability', rus: 'инвалидность / неспособность' },
	{ eng: 'diverse', rus: 'разнообразный / разный' },
	{ eng: 'zip', rus: 'молния / свист' },
	{ eng: 'cardigan', rus: 'кардиган / джемпер' },
	{ eng: 'voting', rus: 'голосование / выборы' },
	{ eng: 'colon', rus: 'двоеточие' },
	{ eng: 'thermometer', rus: 'термометр / градусник' },
	{ eng: 'entrepreneur', rus: 'предприниматель / антрепренер' },
	{ eng: 'controversial', rus: 'спорный / дискуссионный' },
	{ eng: 'prawn', rus: 'большая креветка' },
	{ eng: 'plumber', rus: 'водопроводчик / паяльщик' },
	{ eng: 'creativity', rus: 'креативность / творческие способности' },
	{ eng: 'broadcast', rus: 'теле- или радиопередача / трансляция' },
	{ eng: 'catering', rus: 'общественное питание / поставка провизии и напитков' },
	{ eng: 'trillion', rus: 'триллион' },
	{ eng: 'fluently', rus: 'бегло / плавно' },
	{ eng: 'forecast', rus: 'прогнозировать / предсказывать' },
	{ eng: 'scientifically', rus: 'научно' },
	{ eng: 'booklet', rus: 'буклет / брошюра' },
	{ eng: 'seasonal', rus: 'сезонный' },
	{ eng: 'comedian', rus: 'комик / комедийный актер' },
	{ eng: 'bad-tempered', rus: 'вспыльчивый / раздражительный' },
	{ eng: 'unsuitable', rus: 'неподходящий / неподобающий' },
	{ eng: 'hourly', rus: 'почасовой / ежечасный' },
	{ eng: 'pessimistic', rus: 'пессимистический / пессимистичный' },
	{ eng: 'laziness', rus: 'лень / леность' },
	{ eng: 'leaflet', rus: 'листовка / листочек' },
	{ eng: 'export', rus: 'экспортировать / вывозить' },
	{ eng: 'upgrade', rus: 'модернизация / усовершенствование' },
	{ eng: 'aubergine', rus: 'баклажан' },
	{ eng: 'tonne', rus: 'тонна / метрическая тонна' },
	{ eng: 'cheeky', rus: 'нахальный / наглый' },
	{ eng: 'bossy', rus: 'шишковатый / выпуклый' },
	{ eng: 'availability', rus: 'наличие / пригодность' },
	{ eng: 'prevention', rus: 'профилактика / предупреждение' },
	{ eng: 'soundtrack', rus: 'звуковая дорожка / звуковое сопровождение' },
	{ eng: 'overseas', rus: 'заморский / заграничный' },
	{ eng: 'self-confident', rus: 'самоуверенный / уверенный в себе' },
	{ eng: 'double', rus: 'двойник / номер для двоих' },
	{ eng: 'additionally', rus: 'дополнительно / кроме того' },
	{ eng: 'alphabetical', rus: 'алфавитный / азбучный' },
	{ eng: 'dishonesty', rus: 'нечестность / обман' },
	{ eng: 'well-balanced', rus: 'уравновешенный / хорошо сбалансированный' },
	{ eng: 'spreadsheet', rus: 'таблица / электронная таблица' },
	{ eng: 'browser', rus: 'программа просмотра / покупатель' },
	{ eng: 'burgle', rus: 'грабить / быть взломщиком' },
	{ eng: 'cello', rus: 'виолончель' },
	{ eng: 'communicative', rus: 'общительный / коммуникативный' },
	{ eng: 'bookmark', rus: 'закладка / букмарк' },
	{ eng: 'racism', rus: 'расизм' },
	{ eng: 'programming', rus: 'программирование' },
	{ eng: 'alternatively', rus: 'или же / поочередно' },
	{ eng: 'culturally', rus: 'культурно' },
	{ eng: 'negatively', rus: 'отрицательно / негативно' },
	{ eng: 'nationwide', rus: 'общенародный / общенациональный / всенародный' },
	{ eng: 'optional', rus: 'необязательный / факультативный' },
	{ eng: 'overtime', rus: 'сверхурочно' },
	{ eng: 'stopover', rus: 'остановка / пересадка' },
	{ eng: 'unhelpful', rus: 'бесполезный / непродуктивный' },
	{ eng: 'thanks', rus: 'благодарность' },
	{ eng: 'debit', rus: 'дебет / дебетование' },
	{ eng: 'annually', rus: 'ежегодно' },
	{ eng: 'solo', rus: 'соло / сольный номер' },
	{ eng: 'overall', rus: 'общий / полный' },
	{ eng: 'breakable', rus: 'хрупкий / ломкий' },
	{ eng: 'prefix', rus: 'приставка / префикс' },
	{ eng: 'broadband', rus: 'система / широкополосная связь' },
	{ eng: 'plus', rus: 'плюс / преимущество' },
	{ eng: 'presenter', rus: 'предъявитель / ведущий программы' },
	{ eng: 'orchestral', rus: 'оркестровый' },
	{ eng: 'ecologically', rus: 'экологически / с экологической точки' },
	{ eng: 'affordable', rus: 'доступный / по средствам' },
	{ eng: 'environmentally', rus: 'экологично / экологически' },
	{ eng: 'apostrophe', rus: 'апостроф / апострофа' },
	{ eng: 'suffix', rus: 'суффикс / окончание' },
	{ eng: 'gymnastic', rus: 'гимнастический' },
	{ eng: 'hyphen', rus: 'дефис / соединительная черточка' },
	{ eng: 'semicolon', rus: 'точка с запятой' },
	{ eng: 'scales', rus: 'весы' },
	{ eng: 'transitive', rus: 'переходный / транзитивный' },
	{ eng: 'intransitive', rus: 'непереходный' },
	{ eng: 'nerves', rus: 'нервы / нервозность' },
	{ eng: 'means', rus: 'способ / средство' },
	{ eng: 'heaven', rus: 'небеса' },
	{ eng: 'swallow', rus: 'глоток / ласточка' },
	{ eng: 'presence', rus: 'присутствие' },
	{ eng: 'distributed', rus: 'распределенный' },
];
