export const C1 = [
	{ eng: 'grin', rus: 'ухмыляться / усмехаться' },
	{ eng: 'march', rus: 'маршировать' },
	{ eng: 'upwards', rus: 'вверх / выше' },
	{ eng: 'downwards', rus: 'вниз / книзу' },
	{ eng: 'labour', rus: 'труд / работа' },
	{ eng: 'draught', rus: 'сквозняк / тяга' },
	{ eng: 'embed', rus: 'вставлять / внедрять' },
	{ eng: 'heading', rus: 'заглавие / заголовок' },
	{ eng: 'inclined', rus: 'наклонный / склонный' },
	{ eng: 'accustomed', rus: 'привычный' },
	{ eng: 'frown', rus: 'хмуриться' },
	{ eng: 'spin', rus: 'крутить / вертеть' },
	{ eng: 'snap', rus: 'щелкать / огрызаться / ломать' },
	{ eng: 'peer', rus: 'вглядываться / всматриваться / таращиться' },
	{ eng: 'chamber', rus: 'камера' },
	{ eng: 'shrug', rus: 'пожимать плечами / пожимать' },
	{ eng: 'doorway', rus: 'дверной проем / порог' },
	{ eng: 'cop', rus: 'полицейский / коп' },
	{ eng: 'forth', rus: 'вперед / далее' },
	{ eng: 'toss', rus: 'подкидывать / подбрасывать / швырять' },
	{ eng: 'beast', rus: 'зверь / бестия' },
	{ eng: 'palm', rus: 'ладонь / пальма' },
	{ eng: 'flee', rus: 'спасаться бегством / сбежать' },
	{ eng: 'aboard', rus: 'на борту / внутри транспортного средства' },
	{ eng: 'clutch', rus: 'хватать / сжимать' },
	{ eng: 'rip', rus: 'рвать / распиливать вдоль волокон' },
	{ eng: 'tank', rus: 'бак / цистерна' },
	{ eng: 'sip', rus: 'пить маленькими глотками / отглотнуть / потягивать' },
	{ eng: 'scan', rus: 'осматривать / сканировать' },
	{ eng: 'fleet', rus: 'флот / парк' },
	{ eng: 'rod', rus: 'стержень / прут' },
	{ eng: 'empire', rus: 'империя / стиль ампир' },
	{ eng: 'grand', rus: 'грандиозный / большой' },
	{ eng: 'somewhat', rus: 'отчасти / слегка' },
	{ eng: 'grace', rus: 'грация / изящество' },
	{ eng: 'rank', rus: 'ранг / звание' },
	{ eng: 'grind', rus: 'молоть' },
	{ eng: 'halt', rus: 'прерывать / останавливать / прекращать' },
	{ eng: 'grasp', rus: 'понять / схватывать' },
	{ eng: 'bless', rus: 'благословлять / благословить' },
	{ eng: 'barrel', rus: 'бочка / баррель' },
	{ eng: 'plunge', rus: 'бросаться / погружаться' },
	{ eng: 'panel', rus: 'панель / комиссия' },
	{ eng: 'withdraw', rus: 'изымать / снимать' },
	{ eng: 'possess', rus: 'обладать / овладевать' },
	{ eng: 'twist', rus: 'крутить / искривить' },
	{ eng: 'holy', rus: 'святой / священный' },
	{ eng: 'rock', rus: 'качать / качаться' },
	{ eng: 'urge', rus: 'призывать / настаивать' },
	{ eng: 'lad', rus: 'парень' },
	{ eng: 'proceed', rus: 'приступать / продолжать' },
	{ eng: 'pursue', rus: 'преследовать / следовать курсу' },
	{ eng: 'dump', rus: 'сваливать / вываливать' },
	{ eng: 'harsh', rus: 'резкий / суровый' },
	{ eng: 'await', rus: 'ожидать / ждать' },
	{ eng: 'footstep', rus: 'шаг / поступь / ступенька' },
	{ eng: 'alongside', rus: 'рядом с' },
	{ eng: 'accomplish', rus: 'добиться / достичь' },
	{ eng: 'notion', rus: 'понятие / представление' },
	{ eng: 'shatter', rus: 'разрушать / раздробить' },
	{ eng: 'avenue', rus: 'проспект / авеню' },
	{ eng: 'aid', rus: 'помощь / поддержка' },
	{ eng: 'dismiss', rus: 'увольнять / отбрасывать' },
	{ eng: 'stroll', rus: 'гулять / прогуливаться' },
	{ eng: 'detect', rus: 'обнаруживать / замечать' },
	{ eng: 'gravity', rus: 'гравитация / серьезность' },
	{ eng: 'intense', rus: 'интенсивный / напряженный' },
	{ eng: 'wit', rus: 'остроумие' },
	{ eng: 'utterly', rus: 'крайне / совершенно' },
	{ eng: 'presently', rus: 'сейчас / в настоящее время' },
	{ eng: 'assign', rus: 'назначать / присваивать' },
	{ eng: 'resume', rus: 'возобновлять / возвращаться' },
	{ eng: 'vague', rus: 'смутный / неопределенный' },
	{ eng: 'pad', rus: 'подкладка / подушечка / блокнот' },
	{ eng: 'saint', rus: 'святой / праведник' },
	{ eng: 'hop', rus: 'прыгать / скакать на одной ноге' },
	{ eng: 'trace', rus: 'отслеживать' },
	{ eng: 'helpless', rus: 'беспомощный' },
	{ eng: 'instance', rus: 'пример / инстанция' },
	{ eng: 'noble', rus: 'благородный / знатный' },
	{ eng: 'deputy', rus: 'заместитель / депутат' },
	{ eng: 'merchant', rus: 'торговец / лавочник' },
	{ eng: 'acknowledge', rus: 'признавать / подтверждать' },
	{ eng: 'arise', rus: 'возникать / подниматься' },
	{ eng: 'sheer', rus: 'абсолютный / отвесный' },
	{ eng: 'inspect', rus: 'осматривать / инспектировать' },
	{ eng: 'suite', rus: 'апартаменты / комплект (из нескольких вещей)' },
	{ eng: 'random', rus: 'случайный' },
	{ eng: 'consult', rus: 'консультироваться / консультировать' },
	{ eng: 'vessel', rus: 'судно / сосуд' },
	{ eng: 'lawn', rus: 'газон / лужайка' },
	{ eng: 'buddy', rus: 'приятель / дружище' },
	{ eng: 'pulse', rus: 'пульс / импульс' },
	{ eng: 'occasional', rus: 'случающийся иногда / случайный' },
	{ eng: 'patrol', rus: 'патруль / патрулирование' },
	{ eng: 'neatly', rus: 'аккуратно / опрятно' },
	{ eng: 'triumph', rus: 'триумф' },
	{ eng: 'pose', rus: 'позировать / излагать' },
	{ eng: 'spine', rus: 'позвоночник / шип' },
	{ eng: 'senator', rus: 'сенатор' },
	{ eng: 'butt', rus: 'задница / приклад' },
	{ eng: 'bubble', rus: 'пузырь / финансовый пузырь' },
	{ eng: 'personnel', rus: 'персонал / кадры' },
	{ eng: 'resemble', rus: 'походить на / иметь сходство' },
	{ eng: 'survey', rus: 'обследовать / провести осмотр' },
	{ eng: 'anticipate', rus: 'предвидеть / предчувствовать' },
	{ eng: 'glory', rus: 'слава / великолепие' },
	{ eng: 'focus', rus: 'фокус / внимание' },
	{ eng: 'sin', rus: 'грех / прегрешение' },
	{ eng: 'realm', rus: 'область / сфера' },
	{ eng: 'reassure', rus: 'успокаивать' },
	{ eng: 'conquer', rus: 'завоевывать / покорять' },
	{ eng: 'confront', rus: 'противостоять / предъявлять' },
	{ eng: 'immense', rus: 'огромный / необъятный' },
	{ eng: 'impulse', rus: 'импульс / побуждение' },
	{ eng: 'print', rus: 'отпечаток / шрифт' },
	{ eng: 'chunk', rus: 'ломоть / кусок' },
	{ eng: 'reluctantly', rus: 'неохотно / с неохотой' },
	{ eng: 'determine', rus: 'определять' },
	{ eng: 'staircase', rus: 'лестница / лестничная клетка' },
	{ eng: 'status', rus: 'статус / общественное положение' },
	{ eng: 'trader', rus: 'торговец' },
	{ eng: 'dock', rus: 'док / пристань / причал / скамья подсудимых' },
	{ eng: 'stun', rus: 'оглушать / потрясти' },
	{ eng: 'coal', rus: 'уголь / уголек' },
	{ eng: 'just', rus: 'справедливый' },
	{ eng: 'restrain', rus: 'обуздывать / сдерживать' },
	{ eng: 'campaign', rus: 'кампания / поход' },
	{ eng: 'stake', rus: 'доля / ставка' },
	{ eng: 'superior', rus: 'лучший / превосходный / вышестоящий' },
	{ eng: 'burden', rus: 'бремя / тяготы' },
	{ eng: 'resolve', rus: 'разрешить / решать' },
	{ eng: 'limb', rus: 'конечность / ветвь' },
	{ eng: 'fabric', rus: 'ткань / материал' },
	{ eng: 'radar', rus: 'радар / радиолокатор' },
	{ eng: 'civil', rus: 'гражданский / государственный / вежливый' },
	{ eng: 'technician', rus: 'техник / специалист' },
	{ eng: 'canvas', rus: 'холст / парусина' },
	{ eng: 'hesitation', rus: 'нерешительность / колебание / неуверенность' },
	{ eng: 'rocky', rus: 'скалистый / каменистый' },
	{ eng: 'genius', rus: 'гений / гениальность' },
	{ eng: 'unfold', rus: 'разворачивать / развертываться / развиваться' },
	{ eng: 'humanity', rus: 'человечество / человечность' },
	{ eng: 'garment', rus: 'одежда / предмет одежды' },
	{ eng: 'soar', rus: 'взмывать / возвыситься' },
	{ eng: 'bulk', rus: 'масса / основная масса' },
	{ eng: 'instruct', rus: 'инструктировать / давать инструкции' },
	{ eng: 'logic', rus: 'логика / логические схемы' },
	{ eng: 'accelerate', rus: 'ускоряться / разгоняться' },
	{ eng: 'filthy', rus: 'грязный / мерзкий' },
	{ eng: 'principle', rus: 'принцип / правило' },
	{ eng: 'republic', rus: 'республика / группа людей с общими интересами' },
	{ eng: 'marine', rus: 'морской' },
	{ eng: 'forge', rus: 'ковать / подделывать' },
	{ eng: 'worthy', rus: 'достойный' },
	{ eng: 'vein', rus: 'вена / жила' },
	{ eng: 'fund', rus: 'фонд / капитал' },
	{ eng: 'desire', rus: 'желать / жаждать' },
	{ eng: 'amid', rus: 'среди / посреди' },
	{ eng: 'cluster', rus: 'скопление / набор' },
	{ eng: 'settlement', rus: 'поселение / урегулирование' },
	{ eng: 'render', rus: 'оказывать / приводить в какое-либо состояние' },
	{ eng: 'feast', rus: 'застолье / пир / угощение' },
	{ eng: 'log', rus: 'бревно / журнал' },
	{ eng: 'pony', rus: 'пони / подстрочник' },
	{ eng: 'banner', rus: 'знамя / баннер' },
	{ eng: 'confine', rus: 'ограничивать / держать взаперти' },
	{ eng: 'foundation', rus: 'основа / фундамент' },
	{ eng: 'nonetheless', rus: 'тем не менее / однако' },
	{ eng: 'deepen', rus: 'углублять / заглублять' },
	{ eng: 'dissolve', rus: 'растворять / растворить' },
	{ eng: 'machinery', rus: 'механизм / машины' },
	{ eng: 'presume', rus: 'предполагать / полагать' },
	{ eng: 'stark', rus: 'абсолютный / совершенно очевидный' },
	{ eng: 'reluctant', rus: 'не желающий / делающий что-либо неохотно' },
	{ eng: 'mechanism', rus: 'механизм / устройство' },
	{ eng: 'eliminate', rus: 'ликвидировать / устранять' },
	{ eng: 'destiny', rus: 'судьба / участь' },
	{ eng: 'conclude', rus: 'заключать / заканчивать' },
	{ eng: 'inevitable', rus: 'неизбежный / неизменный' },
	{ eng: 'blast', rus: 'взрыв / взрывная волна' },
	{ eng: 'convey', rus: 'передавать / выражать' },
	{ eng: 'awareness', rus: 'осведомленность / осознание' },
	{ eng: 'debris', rus: 'обломки / осколки' },
	{ eng: 'deed', rus: 'деяние / поступок' },
	{ eng: 'perceive', rus: 'воспринимать / чувствовать' },
	{ eng: 'outsider', rus: 'аутсайдер / посторонний' },
	{ eng: 'seemingly', rus: 'по-видимому' },
	{ eng: 'transmit', rus: 'передавать / транслировать' },
	{ eng: 'surveillance', rus: 'наблюдение / надзор' },
	{ eng: 'restless', rus: 'беспокойный / неугомонный' },
	{ eng: 'weaken', rus: 'ослаблять / ослабевать' },
	{ eng: 'trailer', rus: 'прицеп / трейлер' },
	{ eng: 'gene', rus: 'ген' },
	{ eng: 'vine', rus: 'лоза / виноградная лоза' },
	{ eng: 'sue', rus: 'предъявлять иск / подавать в суд' },
	{ eng: 'caution', rus: 'осторожность / предостережение' },
	{ eng: 'weave', rus: 'ткать / плести' },
	{ eng: 'surgeon', rus: 'хирург / военный врач' },
	{ eng: 'organ', rus: 'орган' },
	{ eng: 'starve', rus: 'голодать / умирать от голода' },
	{ eng: 'tactic', rus: 'тактика / действия' },
	{ eng: 'whip', rus: 'хлестать / стегать / сечь' },
	{ eng: 'appoint', rus: 'назначать / определять' },
	{ eng: 'scholar', rus: 'ученый / стипендиат' },
	{ eng: 'warrant', rus: 'ордер / основание' },
	{ eng: 'primitive', rus: 'примитивный / первобытный' },
	{ eng: 'knob', rus: 'ручка / кнопка' },
	{ eng: 'vest', rus: 'жилет' },
	{ eng: 'diminish', rus: 'уменьшать / уменьшить' },
	{ eng: 'inspection', rus: 'осмотр / инспекция' },
	{ eng: 'splendid', rus: 'великолепный / роскошный' },
	{ eng: 'physician', rus: 'врач / медик' },
	{ eng: 'necessity', rus: 'необходимость' },
	{ eng: 'loop', rus: 'петля' },
	{ eng: 'battlefield', rus: 'поле боя / поле сражения' },
	{ eng: 'mill', rus: 'мельница / завод' },
	{ eng: 'aide', rus: 'помощник' },
	{ eng: 'discard', rus: 'отбрасывать / выбрасывать' },
	{ eng: 'indication', rus: 'признак / указание' },
	{ eng: 'carriage', rus: 'вагон / карета' },
	{ eng: 'slot', rus: 'шлиц / щель' },
	{ eng: 'acquaintance', rus: 'знакомство / знакомый' },
	{ eng: 'implication', rus: 'причастность / значение' },
	{ eng: 'journal', rus: 'журнал / дневник' },
	{ eng: 'riot', rus: 'бунт / мятеж' },
	{ eng: 'engage', rus: 'привлекать / заниматься' },
	{ eng: 'overwhelm', rus: 'ошеломить / сокрушить' },
	{ eng: 'youngster', rus: 'юноша / подросток' },
	{ eng: 'compel', rus: 'заставлять / принуждать' },
	{ eng: 'asset', rus: 'имущество / ценное качество' },
	{ eng: 'angle', rus: 'угол / ракурс / точка зрения' },
	{ eng: 'privilege', rus: 'привилегия / честь' },
	{ eng: 'hatred', rus: 'ненависть / отвращение' },
	{ eng: 'kidnap', rus: 'похищать людей' },
	{ eng: 'distress', rus: 'горе / бедствие' },
	{ eng: 'shuttle', rus: 'челнок / шаттл' },
	{ eng: 'puzzle', rus: 'озадачивать' },
	{ eng: 'dispose', rus: 'располагать / распоряжаться' },
	{ eng: 'scare', rus: 'пугать' },
	{ eng: 'warrior', rus: 'воин / воитель' },
	{ eng: 'thrill', rus: 'трепет / нервное возбуждение' },
	{ eng: 'sphere', rus: 'сфера / шар' },
	{ eng: 'polish', rus: 'полировать' },
	{ eng: 'ash', rus: 'пепел / зола / ясень' },
	{ eng: 'bronze', rus: 'бронза / изделия из бронзы' },
	{ eng: 'radiation', rus: 'излучение / радиация' },
	{ eng: 'sacrifice', rus: 'жертва / жертвоприношение' },
	{ eng: 'bishop', rus: 'епископ / слон (в шахматах)' },
	{ eng: 'emperor', rus: 'император' },
	{ eng: 'unite', rus: 'объединять / объединяться' },
	{ eng: 'mansion', rus: 'особняк / дворец' },
	{ eng: 'trigger', rus: 'триггер / спусковой крючок' },
	{ eng: 'slash', rus: 'хлестать / разрезать' },
	{ eng: 'oblige', rus: 'обязывать / обязать' },
	{ eng: 'warehouse', rus: 'склад / амбар' },
	{ eng: 'brass', rus: 'латунь' },
	{ eng: 'sacred', rus: 'священный / святой' },
	{ eng: 'rifle', rus: 'винтовка / нарезное оружие' },
	{ eng: 'witch', rus: 'ведьма / колдун' },
	{ eng: 'straw', rus: 'солома / соломинка' },
	{ eng: 'peasant', rus: 'крестьянин' },
	{ eng: 'veil', rus: 'вуаль / завеса' },
	{ eng: 'well', rus: 'колодец / источник' },
	{ eng: 'serial', rus: 'серийный / последовательный' },
	{ eng: 'complicate', rus: 'усложнять / осложнять' },
	{ eng: 'crown', rus: 'корона / темя' },
	{ eng: 'exhaust', rus: 'исчерпывать / истощать' },
	{ eng: 'demon', rus: 'демон / дьявол' },
	{ eng: 'monk', rus: 'монах' },
	{ eng: 'fascinate', rus: 'очаровывать / завораживать' },
	{ eng: 'irritate', rus: 'раздражать / вызывать раздражение' },
	{ eng: 'self', rus: 'личность / собственная личность' },
	{ eng: 'conceal', rus: 'скрывать / прятать' },
	{ eng: 'honour', rus: 'чтить / почитать / удостаивать чести' },
	{ eng: 'ease', rus: 'облегчать / ослаблять / ослабевать' },
	{ eng: 'hate', rus: 'ненависть / предмет ненависти' },
	{ eng: 'hunt', rus: 'охота' },
	{ eng: 'narrow', rus: 'сузить' },
	{ eng: 'address', rus: 'обращаться / адресовать' },
	{ eng: 'jam', rus: 'заедать / глушить' },
	{ eng: 'surge', rus: 'вздыматься / резко увеличиваться' },
	{ eng: 'ally', rus: 'союзник / сторонник' },
	{ eng: 'screw', rus: 'привинчивать / прикручивать' },
	{ eng: 'glimpse', rus: 'проблеск / быстрый взгляд' },
	{ eng: 'pump', rus: 'качать / выкачивать' },
	{ eng: 'probe', rus: 'исследовать / расспрашивать' },
	{ eng: 'alarm', rus: 'встревожить / тревожить' },
	{ eng: 'twist', rus: 'твист / поворот' },
	{ eng: 'halt', rus: 'остановка / прекращение' },
	{ eng: 'monitor', rus: 'осуществлять мониторинг / отслеживать' },
	{ eng: 'lounge', rus: 'гостиная / шезлонг' },
	{ eng: 'spare', rus: 'пощадить / избавляться' },
	{ eng: 'embrace', rus: 'объятия' },
	{ eng: 'picture', rus: 'представлять' },
	{ eng: 'grin', rus: 'широкая улыбка / усмешка' },
	{ eng: 'praise', rus: 'похвала / хвала' },
	{ eng: 'venture', rus: 'отважиться / рисковать' },
	{ eng: 'blast', rus: 'взрывать / дуть' },
	{ eng: 'away', rus: 'удаленный / не на своем поле' },
	{ eng: 'superior', rus: 'начальник' },
	{ eng: 'tune', rus: 'настраивать / регулировать' },
	{ eng: 'filter', rus: 'фильтровать / процеживать' },
	{ eng: 'spy', rus: 'шпионить / заниматься шпионажем' },
	{ eng: 'much', rus: 'многое' },
	{ eng: 'say', rus: 'слово / свое слово' },
	{ eng: 'sharp', rus: 'резко / остро' },
	{ eng: 'upward', rus: 'восходящий / направленный вверх' },
	{ eng: 'erect', rus: 'строить / возвести' },
	{ eng: 'military', rus: 'военнослужащие / военные' },
	{ eng: 'shed', rus: 'проливать / сбрасывать' },
	{ eng: 'last', rus: 'в последний раз / на последнем месте' },
	{ eng: 'exhaust', rus: 'выхлоп / выхлопные газы' },
	{ eng: 'shoot', rus: 'побег / росток' },
	{ eng: 'rear', rus: 'тыл / задняя сторона' },
	{ eng: 'trigger', rus: 'спустить курок / инициировать' },
	{ eng: 'dead', rus: 'совершенно / замертво' },
	{ eng: 'spell', rus: 'заклинание / заклятие' },
	{ eng: 'this', rus: 'так' },
	{ eng: 'rear', rus: 'воспитывать / растить' },
	{ eng: 'through', rus: 'сквозной / прямой' },
	{ eng: 'alert', rus: 'предупреждать / объявлять тревогу' },
	{ eng: 'fit', rus: 'припадок / пригонка' },
	{ eng: 'realisation', rus: 'осознание / реализация' },
	{ eng: 'grid', rus: 'сетка / решетка' },
	{ eng: 'glorious', rus: 'славный / великолепный' },
	{ eng: 'negotiate', rus: 'вести переговоры' },
	{ eng: 'precaution', rus: 'предосторожность / предостережение' },
	{ eng: 'insert', rus: 'вставлять' },
	{ eng: 'tactical', rus: 'тактический / боевой' },
	{ eng: 'blind', rus: 'штора / слепой' },
	{ eng: 'mingle', rus: 'смешивать / общаться' },
	{ eng: 'unload', rus: 'разгружать' },
	{ eng: 'insane', rus: 'безумный / душевнобольной' },
	{ eng: 'volunteer', rus: 'вызываться добровольно' },
	{ eng: 'assumption', rus: 'предположение / допущение' },
	{ eng: 'regardless', rus: 'несмотря ни на что / не обращая внимания ни на что' },
	{ eng: 'mass', rus: 'массовый / повальный' },
	{ eng: 'speculation', rus: 'предположение / спекуляция' },
	{ eng: 'chilly', rus: 'прохладный' },
	{ eng: 'graceful', rus: 'изящный / грациозный' },
	{ eng: 'distort', rus: 'искажать / извращать' },
	{ eng: 'fulfil', rus: 'выполнять / удовлетворять' },
	{ eng: 'spectacle', rus: 'спектакль / представление' },
	{ eng: 'annoyance', rus: 'раздражение / досада' },
	{ eng: 'alien', rus: 'чуждый / чужой' },
	{ eng: 'evolve', rus: 'развиваться / эволюционировать' },
	{ eng: 'impose', rus: 'налагать / навязывать' },
	{ eng: 'numerous', rus: 'многочисленный / многие' },
	{ eng: 'brutal', rus: 'суровый / жестокий' },
	{ eng: 'joint', rus: 'сустав / сочленение' },
	{ eng: 'vain', rus: 'тщетный / напрасный / тщеславный' },
	{ eng: 'innocence', rus: 'невинность / невиновность' },
	{ eng: 'academy', rus: 'академия / школа' },
	{ eng: 'appetite', rus: 'аппетит / склонность' },
	{ eng: 'stem', rus: 'стебель / стержень' },
	{ eng: 'array', rus: 'множество / матрица' },
	{ eng: 'index', rus: 'индекс / алфавитный указатель' },
	{ eng: 'drain', rus: 'осушать / дренировать' },
	{ eng: 'prior', rus: 'предварительный / прежний' },
	{ eng: 'undertake', rus: 'предпринимать / брать на себя обязательство' },
	{ eng: 'set', rus: 'постоянный / преднамеренный / устоявшийся' },
	{ eng: 'descent', rus: 'спуск / снижение' },
	{ eng: 'explosive', rus: 'взрывчатый / взрывной' },
	{ eng: 'terrain', rus: 'местность / территория' },
	{ eng: 'foul', rus: 'грязный / вонючий' },
	{ eng: 'plug', rus: 'затыкать / вставлять' },
	{ eng: 'openly', rus: 'открыто / откровенно' },
	{ eng: 'manipulate', rus: 'манипулировать / воздействовать' },
	{ eng: 'pyramid', rus: 'пирамида' },
	{ eng: 'onwards', rus: 'продвигающийся вперед' },
	{ eng: 'federal', rus: 'федеральный / союзный' },
	{ eng: 'vertical', rus: 'вертикальный / отвесный' },
	{ eng: 'distinct', rus: 'хорошо различимый / отчетливый / явный / четкий' },
	{ eng: 'thread', rus: 'нить / резьба' },
	{ eng: 'manuscript', rus: 'рукопись' },
	{ eng: 'uncover', rus: 'раскрывать / открывать' },
	{ eng: 'distraction', rus: 'отвлекающий фактор / отвлечение' },
	{ eng: 'permit', rus: 'разрешение / пропуск / допуск' },
	{ eng: 'stir', rus: 'размешивать / помешивать' },
	{ eng: 'divine', rus: 'божественный / святой' },
	{ eng: 'magnetic', rus: 'магнитный / притягательный' },
	{ eng: 'mat', rus: 'коврик / циновка' },
	{ eng: 'partially', rus: 'частично / отчасти' },
	{ eng: 'fluid', rus: 'жидкость' },
	{ eng: 'capability', rus: 'способность / возможности' },
	{ eng: 'predator', rus: 'хищник / грабитель' },
	{ eng: 'rotate', rus: 'вращать / чередовать' },
	{ eng: 'nap', rus: 'дремота / ворс' },
	{ eng: 'officially', rus: 'официально / формально' },
	{ eng: 'corporate', rus: 'корпоративный / общий' },
	{ eng: 'cargo', rus: 'груз / груз корабля' },
	{ eng: 'perspective', rus: 'перспектива / точка зрения' },
	{ eng: 'reinforce', rus: 'подкреплять / усиливать' },
	{ eng: 'genetic', rus: 'генетический / генный' },
	{ eng: 'mode', rus: 'режим / способ' },
	{ eng: 'recruit', rus: 'рекрутировать / вербовать' },
	{ eng: 'rebellion', rus: 'восстание / мятеж' },
	{ eng: 'sole', rus: 'единственный / исключительный' },
	{ eng: 'anchor', rus: 'якорь' },
	{ eng: 'accusation', rus: 'обвинение / обвинительный акт' },
	{ eng: 'supposedly', rus: 'предположительно / по общему мнению' },
	{ eng: 'neutral', rus: 'нейтральный / беспристрастный' },
	{ eng: 'multiple', rus: 'множественный / многократный' },
	{ eng: 'domain', rus: 'область / сфера' },
	{ eng: 'posture', rus: 'осанка / поза' },
	{ eng: 'sector', rus: 'сектор / участок' },
	{ eng: 'cocktail', rus: 'коктейль / смесь' },
	{ eng: 'anchor', rus: 'закреплять / бросать якорь' },
	{ eng: 'tobacco', rus: 'табак' },
	{ eng: 'exaggerate', rus: 'преувеличивать / муссировать' },
	{ eng: 'engagement', rus: 'помолвка / зацепление' },
	{ eng: 'junk', rus: 'хлам / барахло' },
	{ eng: 'purely', rus: 'чисто / исключительно' },
	{ eng: 'testimony', rus: 'свидетельское показание' },
	{ eng: 'frustrated', rus: 'несостоявшийся' },
	{ eng: 'leadership', rus: 'руководство' },
	{ eng: 'countless', rus: 'бесчисленный / многочисленный' },
	{ eng: 'neglect', rus: 'пренебрегать / не уделять внимание' },
	{ eng: 'patrol', rus: 'патрулировать / барражировать' },
	{ eng: 'boundary', rus: 'граница / черта' },
	{ eng: 'administration', rus: 'администрация / управление делами' },
	{ eng: 'blessing', rus: 'счастье / благо' },
	{ eng: 'significance', rus: 'значимость / важность / значение' },
	{ eng: 'beloved', rus: 'любимый / возлюбленный' },
	{ eng: 'ultimately', rus: 'в конечном счете / в конце концов' },
	{ eng: 'warfare', rus: 'война' },
	{ eng: 'fibre', rus: 'волокно / нить' },
	{ eng: 'violate', rus: 'нарушать / попирать' },
	{ eng: 'succession', rus: 'преемственность / право наследования' },
	{ eng: 'executive', rus: 'исполнительная власть / руководящий работник' },
	{ eng: 'blend', rus: 'смешивать / сочетаться' },
	{ eng: 'mainland', rus: 'материк / большой остров' },
	{ eng: 'paradise', rus: 'рай / благодать' },
	{ eng: 'convention', rus: 'условность / официальная встреча' },
	{ eng: 'grave', rus: 'серьезный' },
	{ eng: 'dam', rus: 'плотина / дамба' },
	{ eng: 'assurance', rus: 'уверенность / заверение' },
	{ eng: 'component', rus: 'компонент / деталь' },
	{ eng: 'refresh', rus: 'освежать / подновить' },
	{ eng: 'token', rus: 'знак / жетон' },
	{ eng: 'proportion', rus: 'доля / часть' },
	{ eng: 'fascination', rus: 'очарование / увлечение' },
	{ eng: 'notify', rus: 'уведомлять / извещать' },
	{ eng: 'devastate', rus: 'опустошать / разорять' },
	{ eng: 'drift', rus: 'дрейфовать / смещаться' },
	{ eng: 'establishment', rus: 'учреждение / установление' },
	{ eng: 'essence', rus: 'суть / эссенция' },
	{ eng: 'hence', rus: 'следовательно / отсюда' },
	{ eng: 'complex', rus: 'комплекс / совокупность' },
	{ eng: 'stale', rus: 'несвежий / черствый' },
	{ eng: 'probability', rus: 'вероятность' },
	{ eng: 'archive', rus: 'архив / архивирование' },
	{ eng: 'assassination', rus: 'убийство / политическое убийство' },
	{ eng: 'hospitality', rus: 'гостеприимство / радушие' },
	{ eng: 'charter', rus: 'устав / чартер' },
	{ eng: 'sufficiently', rus: 'достаточно' },
	{ eng: 'deposit', rus: 'депонировать / вносить' },
	{ eng: 'label', rus: 'прикреплять ярлык / маркировать' },
	{ eng: 'untouched', rus: 'нетронутый / незатронутый' },
	{ eng: 'undergo', rus: 'претерпевать / подвергаться' },
	{ eng: 'bass', rus: 'бас / окунь' },
	{ eng: 'projection', rus: 'проекция / прогноз' },
	{ eng: 'reminder', rus: 'напоминание / повторное уведомление' },
	{ eng: 'protocol', rus: 'протокол / правила этикета' },
	{ eng: 'screw', rus: 'винт / шуруп' },
	{ eng: 'quote', rus: 'цитировать / ссылаться' },
	{ eng: 'commissioner', rus: 'комиссар / член комиссии' },
	{ eng: 'preliminary', rus: 'предварительный / первоначальный' },
	{ eng: 'obstacle', rus: 'препятствие / помеха' },
	{ eng: 'repeatedly', rus: 'неоднократно / несколько раз' },
	{ eng: 'proclaim', rus: 'провозглашать / объявлять' },
	{ eng: 'proceeding', rus: 'разбирательство / процессуальное действие' },
	{ eng: 'ministry', rus: 'министерство / пастырство' },
	{ eng: 'compassion', rus: 'сострадание / сочувствие' },
	{ eng: 'tendency', rus: 'тенденция / склонность' },
	{ eng: 'precision', rus: 'точность / четкость' },
	{ eng: 'imprison', rus: 'заключать в тюрьму / лишать свободы' },
	{ eng: 'breach', rus: 'нарушение / разрыв' },
	{ eng: 'enhance', rus: 'усиливать / повышать' },
	{ eng: 'sincere', rus: 'искренний / душевный' },
	{ eng: 'dispute', rus: 'спор / пререкания' },
	{ eng: 'authorise', rus: 'разрешать / санкционировать' },
	{ eng: 'imitate', rus: 'подражать / имитировать' },
	{ eng: 'hysterical', rus: 'истерический / истеричный' },
	{ eng: 'saying', rus: 'поговорка / пословица' },
	{ eng: 'confer', rus: 'совещаться / предоставлять' },
	{ eng: 'arena', rus: 'арена / место действия' },
	{ eng: 'gadget', rus: 'приспособление / безделушка' },
	{ eng: 'consent', rus: 'согласие' },
	{ eng: 'restrict', rus: 'ограничивать / держать в определенных пределах' },
	{ eng: 'perfection', rus: 'совершенство / совершенствование' },
	{ eng: 'stretch', rus: 'протяжение / натяжка' },
	{ eng: 'greed', rus: 'жадность' },
	{ eng: 'faction', rus: 'фракция' },
	{ eng: 'broadly', rus: 'широко / в общих чертах' },
	{ eng: 'dump', rus: 'свалка / отвал' },
	{ eng: 'boom', rus: 'гул / увеличение' },
	{ eng: 'aid', rus: 'оказывать поддержку / способствовать' },
	{ eng: 'feminine', rus: 'женский / женственный' },
	{ eng: 'confidential', rus: 'конфиденциальный / доверительный' },
	{ eng: 'equation', rus: 'уравнение / выравнивание' },
	{ eng: 'proposition', rus: 'предложение / утверждение' },
	{ eng: 'utility', rus: 'утилита / коммунальное или муниципальное предприятие' },
	{ eng: 'overly', rus: 'слишком / чрезмерно' },
	{ eng: 'executive', rus: 'исполнительный' },
	{ eng: 'excess', rus: 'избыток / превышение' },
	{ eng: 'dime', rus: 'монета в 10 центов / десятицентовик' },
	{ eng: 'thankful', rus: 'благодарный / благодарственный' },
	{ eng: 'whilst', rus: 'хотя / в то время как' },
	{ eng: 'log', rus: 'регистрировать / вносить в судовой или бортовой журнал' },
	{ eng: 'prolong', rus: 'продлевать / продлить' },
	{ eng: 'toll', rus: 'пошлина / потери' },
	{ eng: 'unnoticed', rus: 'незамеченный / незаметный' },
	{ eng: 'incapable', rus: 'неспособный / недееспособный' },
	{ eng: 'enforce', rus: 'принуждать / обеспечивать соблюдение' },
	{ eng: 'supervisor', rus: 'руководитель / надзиратель' },
	{ eng: 'rehearse', rus: 'репетировать / повторять' },
	{ eng: 'hydrogen', rus: 'водород' },
	{ eng: 'classify', rus: 'классифицировать / засекретить' },
	{ eng: 'horizontal', rus: 'горизонтальный' },
	{ eng: 'applaud', rus: 'аплодировать / одобрять' },
	{ eng: 'auto', rus: 'автомобиль / автоматический пистолет' },
	{ eng: 'overturn', rus: 'опрокидывать / опровергать' },
	{ eng: 'bribe', rus: 'взятка / подкуп' },
	{ eng: 'archaeologist', rus: 'археолог' },
	{ eng: 'similarly', rus: 'так же / подобным образом' },
	{ eng: 'installation', rus: 'установка / оборудование' },
	{ eng: 'enforcement', rus: 'принуждение' },
	{ eng: 'misfortune', rus: 'несчастье / неудача' },
	{ eng: 'limitation', rus: 'ограничение / ограниченность' },
	{ eng: 'transit', rus: 'транзит / перевозка' },
	{ eng: 'bully', rus: 'хулиган / задира' },
	{ eng: 'induce', rus: 'вызывать / побуждать' },
	{ eng: 'terminate', rus: 'завершать / прекращать' },
	{ eng: 'slavery', rus: 'рабство / неволя' },
	{ eng: 'comply', rus: 'подчиняться / исполнять' },
	{ eng: 'reassuring', rus: 'успокоительный' },
	{ eng: 'workshop', rus: 'мастерская / семинар' },
	{ eng: 'solitude', rus: 'одиночество' },
	{ eng: 'disapproval', rus: 'неодобрение / осуждение' },
	{ eng: 'complication', rus: 'осложнение / сложность' },
	{ eng: 'craft', rus: 'изготавливать / создавать' },
	{ eng: 'corruption', rus: 'коррупция / развращение' },
	{ eng: 'initiative', rus: 'инициатива / почин' },
	{ eng: 'whatsoever', rus: 'абсолютно / вообще' },
	{ eng: 'pointless', rus: 'бессмысленный / тупой' },
	{ eng: 'irrelevant', rus: 'не имеющий отношения к чему-либо / неуместный' },
	{ eng: 'group', rus: 'группировать / сгруппировать' },
	{ eng: 'pregnancy', rus: 'беременность / богатство' },
	{ eng: 'homeland', rus: 'родина' },
	{ eng: 'attain', rus: 'достигать' },
	{ eng: 'refusal', rus: 'отказ / право первого выбора' },
	{ eng: 'unreal', rus: 'нереальный / ненастоящий' },
	{ eng: 'adviser', rus: 'советник / консультант' },
	{ eng: 'disorder', rus: 'расстройство / беспорядок' },
	{ eng: 'legendary', rus: 'легендарный' },
	{ eng: 'transaction', rus: 'транзакция / торговая или денежная операция' },
	{ eng: 'transformation', rus: 'преобразование / трансформация' },
	{ eng: 'collective', rus: 'коллективный / совместный' },
	{ eng: 'administrator', rus: 'администратор / управляющий' },
	{ eng: 'corrupt', rus: 'портить / повреждать' },
	{ eng: 'breach', rus: 'нарушать / проламывать' },
	{ eng: 'diesel', rus: 'дизель / дизельное топливо' },
	{ eng: 'associate', rus: 'связывать / ассоциировать' },
	{ eng: 'accepted', rus: 'общепринятый' },
	{ eng: 'launch', rus: 'запуск / катер' },
	{ eng: 'elite', rus: 'элита' },
	{ eng: 'regard', rus: 'уважение / отношение' },
	{ eng: 'unity', rus: 'единство / согласие' },
	{ eng: 'circulate', rus: 'циркулировать / распространяться' },
	{ eng: 'designate', rus: 'обозначать / назначать' },
	{ eng: 'contradict', rus: 'противоречить / возражать' },
	{ eng: 'amateur', rus: 'любитель / дилетант' },
	{ eng: 'simplicity', rus: 'простота / несложность' },
	{ eng: 'processor', rus: 'процессор / обработчик' },
	{ eng: 'exceed', rus: 'превышать / превосходить' },
	{ eng: 'memo', rus: 'служебная записка / меморандум' },
	{ eng: 'minimal', rus: 'минимальный / очень маленький' },
	{ eng: 'guerrilla', rus: 'партизан / партизанская война' },
	{ eng: 'cutting', rus: 'черенок / вырезка' },
	{ eng: 'passing', rus: 'прохождение / смерть' },
	{ eng: 'shipping', rus: 'отправление / перевозка груза' },
	{ eng: 'detached', rus: 'отдельный / стоящий особняком' },
	{ eng: 'deserted', rus: 'пустынный / безлюдный' },
	{ eng: 'frustrating', rus: 'печальный' },
	{ eng: 'compelling', rus: 'неопровержимый' },
	{ eng: 'refreshing', rus: 'занятный' },
	{ eng: 'suited', rus: 'подходящий' },
	{ eng: 'opening', rus: 'вступительный' },
	{ eng: 'minimise', rus: 'минимизировать / сводить до минимума' },
	{ eng: 'glamour', rus: 'роскошь / шик' },
	{ eng: 'endeavour', rus: 'стараться / предпринимать' },
	{ eng: 'summarise', rus: 'суммировать / резюмировать' },
	{ eng: 'characterise', rus: 'характеризовать' },
	{ eng: 'developer', rus: 'строитель / строительная фирма' },
	{ eng: 'reconstruction', rus: 'реконструкция / воссоздание' },
	{ eng: 'marketplace', rus: 'маркетплейс / торговая площадка' },
	{ eng: 'premier', rus: 'первый / главный' },
	{ eng: 'escalate', rus: 'обостряться / подниматься' },
	{ eng: 'mislead', rus: 'вводить в заблуждение / сбивать с пути' },
	{ eng: 'configuration', rus: 'конфигурация' },
	{ eng: 'invaluable', rus: 'неоценимый / бесценный' },
	{ eng: 'tranquil', rus: 'спокойный' },
	{ eng: 'documentation', rus: 'документация / бумаги' },
	{ eng: 'tasteless', rus: 'безвкусный / пресный' },
	{ eng: 'regulator', rus: 'регулятор / инспектор' },
	{ eng: 'presumption', rus: 'презумпция / предположение' },
	{ eng: 'consolidate', rus: 'консолидировать / укреплять' },
	{ eng: 'appliance', rus: 'прибор / бытовой прибор' },
	{ eng: 'harassment', rus: 'домогательство / притеснение' },
	{ eng: 'modification', rus: 'модификация / изменение' },
	{ eng: 'infrastructure', rus: 'инфраструктура' },
	{ eng: 'rebellious', rus: 'непокорный' },
	{ eng: 'moderate', rus: 'умеренный / небольшой' },
	{ eng: 'poll', rus: 'опрос / голосование' },
	{ eng: 'prestige', rus: 'престиж' },
	{ eng: 'unmarried', rus: 'неженатый / незамужняя' },
	{ eng: 'innovation', rus: 'инновация / нововведение' },
	{ eng: 'vulnerability', rus: 'уязвимость / ранимость' },
	{ eng: 'register', rus: 'реестр / регистр' },
	{ eng: 'disrespect', rus: 'неуважение / непочтительность' },
	{ eng: 'subsequently', rus: 'впоследствии / потом' },
	{ eng: 'commodity', rus: 'товар / продукт' },
	{ eng: 'specification', rus: 'спецификация / очки' },
	{ eng: 'bump', rus: 'шишка / ухаб' },
	{ eng: 'inevitably', rus: 'неизбежно / неминуемо' },
	{ eng: 'unify', rus: 'унифицировать / объединять' },
	{ eng: 'hospitable', rus: 'гостеприимный / открытый' },
	{ eng: 'deficiency', rus: 'дефицит / нехватка' },
	{ eng: 'voluntary', rus: 'добровольный / благотворительный' },
	{ eng: 'premise', rus: 'предпосылка / помещение' },
	{ eng: 'scholarship', rus: 'стипендия / ученость' },
	{ eng: 'archaeology', rus: 'археология' },
	{ eng: 'exaggeration', rus: 'преувеличение / гипербола' },
	{ eng: 'shameful', rus: 'позорный / постыдный' },
	{ eng: 'aggression', rus: 'агрессия / нападение' },
	{ eng: 'indictment', rus: 'обвинительный акт / обвинение' },
	{ eng: 'migration', rus: 'миграция / переселение' },
	{ eng: 'swap', rus: 'менять / обмениваться' },
	{ eng: 'drastic', rus: 'радикальный / решительный' },
	{ eng: 'modestly', rus: 'умеренно / скромно' },
	{ eng: 'comprehensive', rus: 'исчерпывающий / всесторонний' },
	{ eng: 'compliance', rus: 'согласие / соответствие' },
	{ eng: 'oneself', rus: 'себя / сам' },
	{ eng: 'simplify', rus: 'упрощать' },
	{ eng: 'poorly', rus: 'плохо / неудачно' },
	{ eng: 'ensue', rus: 'следовать / происходить' },
	{ eng: 'drastically', rus: 'кардинально / коренным образом' },
	{ eng: 'speechless', rus: 'немой / безмолвный' },
	{ eng: 'layout', rus: 'макет / оформление' },
	{ eng: 'constitution', rus: 'конституция / телосложение' },
	{ eng: 'meditation', rus: 'медитация / размышление' },
	{ eng: 'mundane', rus: 'мирской / скучный' },
	{ eng: 'clone', rus: 'клон / полное подобие' },
	{ eng: 'luxurious', rus: 'роскошный / расточительный' },
	{ eng: 'magistrate', rus: 'судья' },
	{ eng: 'shorten', rus: 'сокращать / укорачивать' },
	{ eng: 'outlet', rus: 'выход / выходное отверстие' },
	{ eng: 'radical', rus: 'радикальный / коренной' },
	{ eng: 'detain', rus: 'задерживать / удерживать' },
	{ eng: 'doctrine', rus: 'доктрина' },
	{ eng: 'auction', rus: 'аукцион / торг' },
	{ eng: 'evaluate', rus: 'оценивать / определять качество' },
	{ eng: 'administrative', rus: 'административный / управленческий' },
	{ eng: 'striker', rus: 'забастовщик / ударник' },
	{ eng: 'pathway', rus: 'путь / тропа' },
	{ eng: 'detection', rus: 'обнаружение' },
	{ eng: 'exclude', rus: 'исключать / не допускать' },
	{ eng: 'derive', rus: 'получать / происходить' },
	{ eng: 'invoke', rus: 'применять / призывать' },
	{ eng: 'chaotic', rus: 'хаотичный / хаотический' },
	{ eng: 'rotation', rus: 'вращение / чередование' },
	{ eng: 'exhibit', rus: 'выставлять / проявлять' },
	{ eng: 'coverage', rus: 'охват / репортаж' },
	{ eng: 'destructive', rus: 'разрушительный / вредный' },
	{ eng: 'trustworthy', rus: 'заслуживающий доверия' },
	{ eng: 'delegate', rus: 'делегат / представитель' },
	{ eng: 'petition', rus: 'ходатайство / прошение' },
	{ eng: 'unthinkable', rus: 'немыслимый / невообразимый' },
	{ eng: 'pledge', rus: 'залог / обещание' },
	{ eng: 'excessive', rus: 'чрезмерный / излишний' },
	{ eng: 'tedious', rus: 'утомительный / скучный' },
	{ eng: 'uncommon', rus: 'редкий / необычный' },
	{ eng: 'simulate', rus: 'симулировать / имитировать / моделировать' },
	{ eng: 'occurrence', rus: 'происшествие / случай' },
	{ eng: 'intake', rus: 'потребление' },
	{ eng: 'coolness', rus: 'прохлада / невозмутимость' },
	{ eng: 'fixture', rus: 'зажимное приспособление / приспособление' },
	{ eng: 'extinct', rus: 'потухший / вымерший' },
	{ eng: 'correspondence', rus: 'корреспонденция / переписка' },
	{ eng: 'reconstruct', rus: 'реконструировать / воссоздавать' },
	{ eng: 'reconsider', rus: 'пересматривать / реконструировать' },
	{ eng: 'congregation', rus: 'собрание / прихожане' },
	{ eng: 'embark', rus: 'начинать / садиться на корабль' },
	{ eng: 'span', rus: 'пролет / интервал' },
	{ eng: 'insignificant', rus: 'незначительный / несущественный' },
	{ eng: 'solely', rus: 'исключительно / единственно' },
	{ eng: 'suburban', rus: 'пригородный / окраинный' },
	{ eng: 'costly', rus: 'дорогой / ценный' },
	{ eng: 'overload', rus: 'перегружать / форсировать' },
	{ eng: 'comparatively', rus: 'сравнительно / относительно' },
	{ eng: 'protein', rus: 'белок / протеин' },
	{ eng: 'incidentally', rus: 'кстати / между прочим' },
	{ eng: 'residue', rus: 'остаток / осадок' },
	{ eng: 'footage', rus: 'метраж / отснятый материал' },
	{ eng: 'commonly', rus: 'обычно / обыкновенно' },
	{ eng: 'illustration', rus: 'иллюстрация / пример' },
	{ eng: 'masculine', rus: 'мужской / мужественный' },
	{ eng: 'purity', rus: 'чистота' },
	{ eng: 'hardship', rus: 'трудности / лишения' },
	{ eng: 'alteration', rus: 'изменение / переделка' },
	{ eng: 'evoke', rus: 'вызывать / вызывать воспоминания' },
	{ eng: 'align', rus: 'выравнивать / располагать по линии' },
	{ eng: 'prosperity', rus: 'процветание' },
	{ eng: 'idol', rus: 'идол / божество' },
	{ eng: 'morality', rus: 'мораль / моралите' },
	{ eng: 'coalition', rus: 'коалиция / объединение' },
	{ eng: 'integrate', rus: 'интегрировать / объединять' },
	{ eng: 'impersonal', rus: 'безличный / безразличный' },
	{ eng: 'juvenile', rus: 'юношеский / детский' },
	{
		eng: 'cater',
		rus: 'угождать / поставлять провизию и обслуживать гостей какого-либо мероприятия',
	},
	{ eng: 'optical', rus: 'оптический / зрительный' },
	{ eng: 'aftermath', rus: 'последствия / отава' },
	{ eng: 'vocal', rus: 'вокальный / голосовой' },
	{ eng: 'notorious', rus: 'пресловутый / пользующийся дурной славой' },
	{ eng: 'contend', rus: 'утверждать / бороться' },
	{ eng: 'comprise', rus: 'включать / содержать' },
	{ eng: 'deteriorate', rus: 'ухудшаться' },
	{ eng: 'evaluation', rus: 'оценка' },
	{ eng: 'pastor', rus: 'пастор / духовный пастырь' },
	{ eng: 'germ', rus: 'микроб / зародыш' },
	{ eng: 'beware', rus: 'остерегаться / беречься' },
	{ eng: 'respective', rus: 'соответственный / соответствующий' },
	{ eng: 'outlook', rus: 'перспектива / мировоззрение' },
	{ eng: 'detention', rus: 'задержание' },
	{ eng: 'hormone', rus: 'гормон' },
	{ eng: 'competence', rus: 'компетентность / компетенция' },
	{ eng: 'transcript', rus: 'расшифровка / письменный вариант' },
	{ eng: 'walker', rus: 'ходок' },
	{ eng: 'denounce', rus: 'денонсировать / осуждать' },
	{ eng: 'closeness', rus: 'близость / плотность' },
	{ eng: 'liability', rus: 'ответственность / обязательство' },
	{ eng: 'omit', rus: 'пропускать / не включать' },
	{ eng: 'edible', rus: 'съедобный / годный в пищу' },
	{ eng: 'trustee', rus: 'попечитель / доверительный собственник' },
	{ eng: 'outweigh', rus: 'перевешивать / быть тяжелее' },
	{ eng: 'asylum', rus: 'убежище / психиатрическая больница' },
	{ eng: 'mustard', rus: 'горчица / то, что придает остроту' },
	{ eng: 'imaginative', rus: 'образный / художественный' },
	{ eng: 'readjust', rus: 'приспосабливаться / поправлять' },
	{ eng: 'spokesman', rus: 'представитель / оратор' },
	{ eng: 'orientation', rus: 'ориентация / ориентировка' },
	{ eng: 'mysteriously', rus: 'таинственно / загадочно' },
	{ eng: 'municipal', rus: 'муниципальный / городской' },
	{ eng: 'talkative', rus: 'разговорчивый / болтливый' },
	{ eng: 'correspondent', rus: 'корреспондент' },
	{ eng: 'ozone', rus: 'озон / воздействие озона' },
	{ eng: 'drawback', rus: 'недостаток / препятствие' },
	{ eng: 'consumption', rus: 'потребление / расход' },
	{ eng: 'influential', rus: 'влиятельный / важный' },
	{ eng: 'subjective', rus: 'субъективный / свойственный подлежащему' },
	{ eng: 'psychiatric', rus: 'психиатрический' },
	{ eng: 'shyness', rus: 'застенчивость' },
	{ eng: 'nominate', rus: 'назначать / выдвигать чью-либо кандидатуру' },
	{ eng: 'rudely', rus: 'грубо' },
	{ eng: 'ratio', rus: 'соотношение / отношение' },
	{ eng: 'citizenship', rus: 'гражданство / гражданственность' },
	{ eng: 'pipeline', rus: 'трубопровод' },
	{ eng: 'unquestionably', rus: 'бесспорно / несомненно' },
	{ eng: 'hectic', rus: 'беспокойный / лихорадочный' },
	{ eng: 'usefulness', rus: 'полезность' },
	{ eng: 'mobilize', rus: 'мобилизовать' },
	{ eng: 'architectural', rus: 'архитектурный' },
	{ eng: 'integral', rus: 'неотъемлемый / интегральный' },
	{ eng: 'dual', rus: 'двойной / двойственный' },
	{ eng: 'stamina', rus: 'выносливость' },
	{ eng: 'contestant', rus: 'участник соревнования / конкурент' },
	{ eng: 'eligible', rus: 'подходящий / имеющий право' },
	{ eng: 'linear', rus: 'линейный / линеарный' },
	{ eng: 'ballot', rus: 'избирательный бюллетень / голосование' },
	{ eng: 'notwithstanding', rus: 'вопреки / несмотря на' },
	{ eng: 'allegation', rus: 'заявление / утверждение' },
	{ eng: 'radically', rus: 'радикально / в корне' },
	{ eng: 'congressional', rus: 'относящийся к конгрессу США / относящийся к конгрессу' },
	{ eng: 'rudeness', rus: 'грубость' },
	{ eng: 'controversy', rus: 'спор' },
	{ eng: 'enrich', rus: 'обогащать / улучшать' },
	{ eng: 'restart', rus: 'возобновлять / перезагружать' },
	{ eng: 'indigenous', rus: 'туземный / местный' },
	{ eng: 'untrue', rus: 'неверный / ложный' },
	{ eng: 'nomination', rus: 'назначение / выдвижение кандидата' },
	{ eng: 'ideology', rus: 'идеология / мировоззрение' },
	{ eng: 'chatty', rus: 'болтливый / непринужденный' },
	{ eng: 'discontent', rus: 'недовольство / досада' },
	{ eng: 'comeback', rus: 'возвращение / возмездие' },
	{ eng: 'effectiveness', rus: 'эффективность / действенность' },
	{ eng: 'secular', rus: 'светский / мирской' },
	{ eng: 'takeover', rus: 'захват / поглощение' },
	{ eng: 'accused', rus: 'обвиняемый / подсудимый' },
	{ eng: 'rate', rus: 'оценивать / определять' },
	{ eng: 'reign', rus: 'царствование / правление' },
	{ eng: 'premises', rus: 'помещение / площадь' },
	{ eng: 'trek', rus: 'путешествие / поход' },
	{ eng: 'span', rus: 'охватывать / соединять берега' },
	{ eng: 'variable', rus: 'переменная / переменная величина' },
	{ eng: 'import', rus: 'импорт / ввоз' },
	{ eng: 'articulate', rus: 'формулировать / излагать' },
	{ eng: 'rank', rus: 'оценивать / ранжировать' },
	{ eng: 'objective', rus: 'цель / задача' },
	{ eng: 'mature', rus: 'созревать / взрослеть' },
	{ eng: 'documentary', rus: 'документальный фильм' },
	{ eng: 'liberal', rus: 'либерал' },
	{ eng: 'crawl', rus: 'кроль / ползание' },
	{ eng: 'serial', rus: 'сериал / периодическое издание' },
	{ eng: 'relative', rus: 'относительный / соответствующий' },
	{ eng: 'gross', rus: 'оптом' },
	{ eng: 'amateur', rus: 'любительский / самодеятельный' },
	{ eng: 'reverse', rus: 'задний ход / реверс' },
	{ eng: 'well-being', rus: 'благополучие / здоровье' },
	{ eng: 'disclosure', rus: 'раскрытие' },
	{ eng: 'turnover', rus: 'оборот / оборот капитала' },
	{ eng: 'shortcoming', rus: 'недостаток / дефект' },
	{ eng: 'sensibly', rus: 'разумно / здраво' },
	{ eng: 'insecure', rus: 'небезопасный / неуверенный в себе' },
	{ eng: 'selfishness', rus: 'эгоизм / эгоистичность' },
	{ eng: 'flair', rus: 'способность / чутье' },
	{ eng: 'excellence', rus: 'превосходство / мастерство' },
	{ eng: 'collaborate', rus: 'сотрудничать / сотрудничать с врагом' },
	{ eng: 'provider', rus: 'поставщик' },
	{ eng: 'notably', rus: 'особенно / заметно' },
	{ eng: 'satisfactorily', rus: 'удовлетворительно' },
	{ eng: 'transparency', rus: 'прозрачность / диапозитив' },
	{ eng: 'day-to-day', rus: 'повседневный' },
	{ eng: 'grade', rus: 'сортировать / градуировать' },
	{ eng: 'postal', rus: 'почтовый' },
	{ eng: 'selective', rus: 'селективный / избирательный' },
	{ eng: 'contention', rus: 'конкуренция / утверждение' },
	{ eng: 'accordance', rus: 'соответствие / согласие' },
	{ eng: 'inefficient', rus: 'неэффективный / неумелый' },
	{ eng: 'progression', rus: 'развитие / продвижение' },
	{ eng: 'internally', rus: 'внутренне' },
	{ eng: 'resident', rus: 'проживающий / постоянно живущий' },
	{ eng: 'alleged', rus: 'мнимый' },
	{ eng: 'format', rus: 'формат / вид' },
	{ eng: 'exclusion', rus: 'исключение / недопущение' },
	{ eng: 'linguistic', rus: 'лингвистический / языковой' },
	{ eng: 'mandatory', rus: 'обязательный / принудительный' },
	{ eng: 'retail', rus: 'розничная торговля / розничная продажа' },
	{ eng: 'misuse', rus: 'злоупотреблять / неправильно употреблять' },
	{ eng: 'exploitation', rus: 'эксплуатация / разработка месторождения' },
	{ eng: 'collaboration', rus: 'сотрудничество / коллаборационизм' },
	{ eng: 'shareholder', rus: 'акционер / держатель акций' },
	{ eng: 'earnings', rus: 'заработок / доход' },
	{ eng: 'unsuccessfully', rus: 'безуспешно / неуспешно' },
	{ eng: 'digestion', rus: 'пищеварение / усвоение' },
	{ eng: 'appealing', rus: 'привлекательный' },
	{ eng: 'tribunal', rus: 'суд / трибунал' },
	{ eng: 'long-standing', rus: 'давний / давнишний' },
	{ eng: 'itinerary', rus: 'путеводитель / маршрут' },
	{ eng: 'universally', rus: 'универсально / везде' },
	{ eng: 'waffle', rus: 'вафля / пустая болтовня' },
	{ eng: 'renovate', rus: 'реконструировать / обновлять' },
	{ eng: 'duo', rus: 'дуэт / актерская пара' },
	{ eng: 'down-to-earth', rus: 'реалистичный / приземленный' },
	{ eng: 'generic', rus: 'общий / родовой' },
	{ eng: 'unveil', rus: 'раскрывать / обнародовать' },
	{ eng: 'compatible', rus: 'совместимый / сочетаемый' },
	{ eng: 'unsafe', rus: 'небезопасный / опасный / незащищенный' },
	{ eng: 'overestimate', rus: 'переоценивать / составлять раздутую смету' },
	{ eng: 'objectively', rus: 'объективно / реально' },
	{ eng: 'prestigious', rus: 'престижный / авторитетный' },
	{ eng: 'complement', rus: 'дополнять / подчеркивать' },
	{ eng: 'beneficiary', rus: 'лицо / глава церковного прихода' },
	{ eng: 'subscription', rus: 'подписка / подписная цена' },
	{ eng: 'endorsement', rus: 'индоссамент / передаточная надпись' },
	{ eng: 'militant', rus: 'воинственный / воинствующий' },
	{ eng: 'obligatory', rus: 'обязательный' },
	{ eng: 'substitution', rus: 'замена / подстановка' },
	{ eng: 'recreate', rus: 'отдыхать / воссоздавать' },
	{ eng: 'idealistic', rus: 'идеалистический / идеалистичный' },
	{ eng: 'fatty', rus: 'жирный / жировой' },
	{ eng: 'activist', rus: 'активист / сторонник активных мер' },
	{ eng: 'processing', rus: 'обработка / процессинг' },
	{ eng: 'flawed', rus: 'некорректный' },
	{ eng: 'cosmopolitan', rus: 'многонациональный / космополитический' },
	{ eng: 'mandate', rus: 'мандат / наказ' },
	{ eng: 'insensitive', rus: 'нечувствительный / равнодушный' },
	{ eng: 'redundancy', rus: 'сокращение штатов / избыток' },
	{ eng: 'activation', rus: 'активация / активизация' },
	{ eng: 'dissertation', rus: 'диссертация / трактат' },
	{ eng: 'enthusiast', rus: 'энтузиаст / восторженный человек' },
	{ eng: 'time-consuming', rus: 'трудоемкий / отнимающий много времени' },
	{ eng: 'opposed', rus: 'противоположный / противный' },
	{ eng: 'therapeutic', rus: 'терапевтический / лечебный' },
	{ eng: 'cultivation', rus: 'выращивание / культивирование' },
	{ eng: 'clarification', rus: 'прояснение / очищение' },
	{ eng: 'copyright', rus: 'авторское право / издательское право' },
	{ eng: 'sewing', rus: 'шитье / пошив' },
	{ eng: 'recruitment', rus: 'вербовка / набор новобранцев' },
	{ eng: 'contender', rus: 'претендент / соперник' },
	{ eng: 'high-profile', rus: 'широко известный' },
	{ eng: 'subtitle', rus: 'подзаголовок / субтитры' },
	{ eng: 'pronounced', rus: 'весьма заметный / явно выраженный / весьма ощутимый' },
	{ eng: 'technologically', rus: 'технологически / технологично' },
	{ eng: 'exhaustive', rus: 'исчерпывающий / истощающий' },
	{ eng: 'ranking', rus: 'ранжирование / расстановка' },
	{ eng: 'moderation', rus: 'умеренность / сдержанность' },
	{ eng: 'applicable', rus: 'применимый' },
	{ eng: 'ideological', rus: 'идеологический' },
	{ eng: 'hygiene', rus: 'гигиена / средства гигиены' },
	{ eng: 'differentiate', rus: 'дифференцировать / отличать' },
	{ eng: 'legislative', rus: 'законодательный / законопослушный' },
	{ eng: 'problematic', rus: 'проблематичный / сложный' },
	{ eng: 'obese', rus: 'тучный' },
	{ eng: 'addictive', rus: 'вырабатывающий привыкание / вызывающий привыкание' },
	{ eng: 'justified', rus: 'справедливый' },
	{ eng: 'teamwork', rus: 'совместная работа / сыгранность' },
	{ eng: 'debut', rus: 'дебют / первое выступление' },
	{ eng: 'misbehave', rus: 'плохо себя вести / дурно вести себя' },
	{ eng: 'cholesterol', rus: 'холестерин' },
	{ eng: 'arguably', rus: 'возможно / спорно' },
	{ eng: 'unwillingness', rus: 'нежелание' },
	{ eng: 'critique', rus: 'критика / критический отзыв' },
	{ eng: 'decision-making', rus: 'принятие решений' },
	{ eng: 'fundraising', rus: 'сбор средств / фандрайзинг' },
	{ eng: 'damaging', rus: 'разрушительный' },
	{ eng: 'payable', rus: 'подлежащий уплате / подлежащий оплате' },
	{ eng: 'inconsiderate', rus: 'не считающийся с другими / неосмотрительный' },
	{ eng: 'cognitive', rus: 'познавательный / когнитивный' },
	{ eng: 'soy', rus: 'соя' },
	{ eng: 'affluent', rus: 'богатый / полноводный' },
	{ eng: 'inclusion', rus: 'включение / инклюзия' },
	{ eng: 'environmentalist', rus: 'сторонник защиты окружающей среды / эколог' },
	{ eng: 'cutting-edge', rus: 'передовой / современный' },
	{ eng: 'literacy', rus: 'грамотность / распространение грамотности' },
	{ eng: 'spokesperson', rus: 'представитель / докладчик' },
	{ eng: 'industrialised', rus: 'промышленно развитый' },
	{ eng: 'unspoiled', rus: 'девственный / неиспорченный' },
	{ eng: 'subscriber', rus: 'абонент / подписчик' },
	{ eng: 'biased', rus: 'тенденциозный' },
	{ eng: 'inedible', rus: 'несъедобный / непищевой' },
	{ eng: 'nutritious', rus: 'питательный / полезный' },
	{ eng: 'deprived', rus: 'бедный / лишенный собственности' },
	{ eng: 'educator', rus: 'воспитатель / педагог' },
	{ eng: 'electoral', rus: 'избирательный / выборный' },
	{ eng: 'unjustified', rus: 'неоправданный / неправомерный' },
	{ eng: 'inclusive', rus: 'включающий в себя / включительно' },
	{ eng: 'renewable', rus: 'возобновляемый / продлеваемый' },
	{ eng: 'benchmark', rus: 'отметка уровня / эталон' },
	{ eng: 'intensively', rus: 'интенсивно' },
	{ eng: 'cutback', rus: 'сокращение / снижение' },
	{ eng: 'extrovert', rus: 'экстраверт / экстроверт' },
	{ eng: 'bilingual', rus: 'двуязычный / говорящий на двух языках' },
	{ eng: 'suitability', rus: 'пригодность / соответствие' },
	{ eng: 'obesity', rus: 'ожирение / полнота' },
	{ eng: 'sustainable', rus: 'устойчивый / поддерживаемый' },
	{ eng: 'industrialisation', rus: 'индустриализация' },
	{ eng: 'accountability', rus: 'подотчетность / ответственность' },
	{ eng: 'techno', rus: 'техно' },
	{ eng: 'gerund', rus: 'герундий' },
	{ eng: 'racially', rus: 'расово' },
	{ eng: 'readership', rus: 'круг читателей / читатели' },
	{ eng: 'comprehensively', rus: 'исчерпывающе / вразумительно' },
	{ eng: 'overdrawn', rus: 'в минусе' },
	{ eng: 'prevalence', rus: 'распространенность / преобладание' },
	{ eng: 'disadvantaged', rus: 'неблагополучный / неимущий' },
	{ eng: 'overdraft', rus: 'превышение остатка счета / превышение кредита' },
	{ eng: 'vocational', rus: 'профессиональный' },
	{ eng: 'refund', rus: 'возвращать деньги / возвращать' },
	{ eng: 'privatise', rus: 'приватизировать' },
	{ eng: 'generalise', rus: 'обобщать / распространять' },
	{ eng: 'thought-provoking', rus: 'наводящий на размышления' },
	{ eng: 'redevelop', rus: 'перестраивать / перестроить' },
	{ eng: 'swop', rus: 'обмениваться / обменивать' },
	{ eng: 'privatisation', rus: 'приватизация' },
	{ eng: 'unaffordable', rus: 'непосильный / недоступный' },
	{ eng: 'coordinate', rus: 'координата' },
];
